import {readStored} from '../helpers/storage.js';
import {test,expect} from '@playwright/test';
import {readdir} from 'node:fs/promises';
import {defaultConfig,hashData} from '../../src/training/config.js';
import {emptyLearningRecord} from '../../src/lessons/learning-records.js';
const workerFile=async()=>'/rl-island/assets/'+(await readdir('dist/assets')).find(f=>/^training.worker-.*\.js$/.test(f));
test('failed neural run is visibly saved, survives refresh, grants no completion, and resets to live training',async({page})=>{
 test.setTimeout(60000);await page.goto('#/');const config=defaultConfig('09');config.deep.batch=4;const cp=await page.evaluate(({url,config,configHash})=>new Promise((resolve,reject)=>{const w=new Worker(url,{type:'module'});w.onmessage=({data})=>{if(data.event==='ready'){w.terminate();resolve(data.snapshot.checkpoint);}else if(data.event==='error'){w.terminate();reject(Error(data.error));}};w.postMessage({protocol:1,runId:'fault-fixture',commandId:1,configHash,command:'initialize',payload:{config}});}),{url:await workerFile(),config,configHash:hashData(config)});
 // Explicit fault-injection fixture: force excessive finite Q, never claim natural benchmark divergence.
 for(const weights of [cp.parameters.deep.online,cp.parameters.deep.target]){weights.forEach(row=>row.fill(0));weights[5].fill(100000);}for(const row of Object.values(cp.parameters.q))row.fill(100000);
 const id='qa-fault-injection',progress={schemaVersion:1,lastLesson:'09',lessons:{'09':{...emptyLearningRecord(),stage:2,prediction:{answer:'Developer QA fault injection: deliberately excessive finite weights test stop/recovery; not a trained student result.',at:new Date().toISOString()},activeRunId:id,runIds:[id],configVersion:1}}},runs={[id]:cp};const backup={format:'rl-island-learning',schemaVersion:1,kind:'self-reported-learning-artifact',createdAt:new Date().toISOString(),progress,runs,digest:hashData({progress,runs})};
 await page.goto('#/notebook');await page.locator('#learning-backup-file').setInputFiles({name:'fault-injection.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#confirm-learning-import').click();await expect(page.locator('#learning-transfer-status')).toContainText('replaced');await page.goto('#/lesson/09');const action=name=>page.getByRole('button',{name,exact:true});await expect(action('Train batch')).toBeEnabled();await page.getByLabel('Batch real interactions',{exact:true}).fill('4');await action('Train batch').click();await expect(page.getByRole('alert')).toContainText('Run stopped at interaction 4');await expect(page.getByRole('alert')).toContainText('excessive Q magnitude');await expect(page.locator('#run-facts')).toContainText('0 numerical updates');await expect(page.locator('.neural-metrics dd').nth(2)).toHaveText('Stopped');await page.reload();await expect(page.getByRole('alert')).toContainText('Run stopped at interaction 4');expect((await readStored(page,'rl-island:model-free-progress:v1')).lessons['09'].completedAt).toBeNull();await page.locator('#advanced-inspector').screenshot({path:'evidence/task-11/screenshots/deep-failure-fault-injection.png'});await page.locator('.learning-config summary').click();await action('Reset learning').click();await action('Start fresh learning').click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.locator('#run-facts')).toContainText('0 training interactions');await page.getByLabel('Batch real interactions',{exact:true}).fill('20');await action('Train batch').click();await expect(page.locator('#run-facts')).toContainText('17 numerical updates');
});
test('asynchronous neural initialization rejects stale generation when experiments are replaced',async({page})=>{await page.goto('#/');const deep=defaultConfig('09'),early=defaultConfig('04');const result=await page.evaluate(async({url,deep,early,deepHash,earlyHash})=>{const w=new Worker(url,{type:'module'}),messages=[];let resolver;const next=()=>new Promise(resolve=>resolver=resolve);w.onmessage=({data})=>{messages.push(data);if(data.event==='ready'||data.event==='error')resolver?.(data);};const send=(runId,commandId,config,configHash)=>w.postMessage({protocol:1,runId,commandId,configHash,command:'initialize',payload:{config}});try{const first=next();send('stale-deep',1,deep,deepHash);send('current-early',2,early,earlyHash);const ready=await first;const later=next();send('current-deep',3,deep,deepHash);const loaded=await later;return {ready:ready.runId,loaded:loaded.runId,events:messages.map(m=>({runId:m.runId,event:m.event})),runtime:loaded.snapshot.checkpoint.parameters.deep.runtime};}finally{w.terminate();}},{url:await workerFile(),deep,early,deepHash:hashData(deep),earlyHash:hashData(early)});expect(result.ready).toBe('current-early');expect(result.loaded).toBe('current-deep');expect(result.events.some(e=>e.runId==='stale-deep')).toBe(false);expect(result.runtime.backend).toBe('cpu');});
