import {readStored} from '../helpers/storage.js';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {imitationWinner} from '../../src/imitation/experiment.js';
import {hashData} from '../../src/training/config.js';
const key='rl-island:model-free-progress:v1',dir='evidence/task-11/screenshots';
const stage=(p,n)=>p.locator('[data-imitation-stage="'+n+'"]').click();
const button=(p,name)=>p.getByRole('button',{name,exact:true});
const axe=async p=>expect((await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);
const picture=async(p,name)=>{await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:dir+'/'+name+'.png',fullPage:true,animations:'disabled'});};
async function predict(p){await stage(p,1);await p.locator('[data-imitation-form="prediction"] textarea').fill('Developer QA prediction, not a student result: lower-path labels may not teach upper-state choices. Compare measured returns at equal new RL budgets.');await button(p,'Save prediction').click();await stage(p,2);}
async function demos(p){await button(p,'Start trajectory').click();await p.keyboard.press('ArrowRight');await expect(p.locator('#demonstration-state')).toContainText('(1,1)');await p.reload();await expect(p.locator('#demonstration-state')).toContainText('(1,1)');await p.locator('#demonstration-board').focus();await p.keyboard.press('ArrowRight');await p.keyboard.press('ArrowUp');await expect(p.locator('#demonstration-state')).toContainText('terminated');await p.locator('#demo-split').selectOption('holdout');await button(p,'Start trajectory').click();await button(p,'Move right').click();await button(p,'Move right').click();await expect(p.locator('#demo-dataset')).toContainText('3 training pairs · 2 held-out pairs');}
async function fit(p){await button(p,'Fit behavior cloning').click();await expect(p.locator('#imitation-status')).toContainText('Supervised fit complete');await expect(p.locator('.imitation-lab')).toContainText('360 training-example passes');}
async function setup(p){await p.goto('#/lesson/11');await predict(p);await demos(p);await fit(p);}
test.beforeAll(()=>mkdir(dir,{recursive:true}));
test('complete lesson 11 with manual aligned demonstrations, real fitting, comparison, refresh and safe backups',async({page,browser})=>{
 test.setTimeout(240000);const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.setViewportSize({width:1440,height:1000});await page.goto('#/notebook');await page.locator('#learning-backup-file').setInputFiles('evidence/task-07/browser-qa-deep.json');await page.locator('#confirm-learning-import').click();await expect(page.locator('#learning-transfer-status')).toContainText('replaced');const before=(await readStored(page,key));
 await page.goto('#/lesson/11');await stage(page,4);await expect(page.getByRole('heading',{name:'Save a prediction first',exact:true})).toBeVisible();await expect(page.locator('.imitation-lab')).toHaveCount(0);await stage(page,0);await page.locator('[data-imitation-form="observe"] select').selectOption({index:1});await button(page,'Check understanding').click();await expect(page.locator('#imitation-status')).toContainText('Correct.');await picture(page,'imitation-observe');await predict(page);await demos(page);await page.locator('#demo-dataset details').first().locator('summary').click();await expect(page.locator('#demo-dataset')).toContainText('Aligned manual transitions');await picture(page,'imitation-manual-alignment');
 const download=page.waitForEvent('download');await button(page,'Export demonstrations').click();await (await download).saveAs('evidence/task-11/manual-qa-demonstrations.json');await fit(page);await axe(page);await picture(page,'imitation-fitted-desktop');const afterFit=(await readStored(page,key)).lessons['11'].imitation.sessions[0].fit;expect(afterFit.history.at(-1).train.loss).toBeLessThan(.1);expect(afterFit.history.at(-1).holdout.loss).toBeCloseTo(Math.log(4));await page.reload();await expect(page.locator('.imitation-lab')).toContainText('360 training-example passes');
 await stage(page,3);await page.locator('[name="answer0"]').fill('.375');await page.locator('[name="answer1"]').fill('-.125');await button(page,'Check both calculations').click();await expect(page.locator('#imitation-status')).toContainText('Correct.');await picture(page,'imitation-mathematics');
 await stage(page,4);await page.locator('[data-imitation-form="compare"] textarea').fill('QA prediction: imitation may help the lower start; upper-start results will be measured, not assumed.');await button(page,'Save prediction and run comparison').click();await expect(page.locator('.imitation-comparison')).toContainText('complete · 10/10 RL agents',{timeout:120000});await axe(page);await picture(page,'imitation-comparison-desktop');const c=(await readStored(page,key)).lessons['11'].imitation.sessions[0].comparison;expect(c.runs.every(r=>r.checkpoint.interactions===600&&r.checkpoint.parameters.updates===600&&r.novel.trainingUpdates===0)).toBe(true);expect(c.baseline.novel.trace[0].unseen).toBe(true);expect(c.baseline.novel.trace[0].decision.probabilities).toEqual([.25,.25,.25,.25]);await writeFile('evidence/task-11/comparison-summary.json',JSON.stringify({source:'Actual browser runs with developer QA demonstrations; not student results.',winner:imitationWinner(c),datasetHash:c.datasetHash,budget:c.budget,fit:afterFit,baseline:c.baseline,runs:c.runs.map(r=>({variant:r.variant,seed:r.seed,interactions:r.checkpoint.interactions,updates:r.checkpoint.parameters.updates,familiar:r.familiar.rows,novel:r.novel.rows}))},null,2));
 await stage(page,5);await page.locator('[name="winner"]').selectOption(imitationWinner(c));await page.locator('[name="concept"]').selectOption({index:2});await button(page,'Submit challenge').click();await expect(page.locator('#imitation-status')).toContainText('Not yet.');await page.locator('[name="winner"]').selectOption(imitationWinner(c));await page.locator('[name="concept"]').selectOption({index:1});await button(page,'Submit challenge').click();await expect(page.getByRole('heading',{name:'Lesson complete',exact:true})).toBeVisible();await page.locator('[name="reflection"]').fill('QA reflection <img src=x onerror=alert(1)>: fitting and return are separate. This is not graded student evidence.');await button(page,'Save reflection').click();await expect(page.locator('#imitation-status')).toContainText('without automatic grading');await picture(page,'imitation-complete-desktop');await page.reload();await expect(page.getByRole('heading',{name:'Lesson complete',exact:true})).toBeVisible();const after=(await readStored(page,key));for(const id of ['04','05','06','07','08','09','10'])expect(after.lessons[id]).toEqual(before.lessons[id]);await page.goto('#/island');await expect(page.locator('[data-lesson-status="Not available yet"]')).toHaveCount(0);await expect(page.locator('[data-lesson-status="Complete"]')).toHaveCount(8);await picture(page,'eleven-available-island');await page.goto('#/notebook');await expect(page.locator('.learning-notebook')).toContainText('10 embedded RL checkpoints');await expect(page.locator('.reflection-text')).toContainText(['<img src=x onerror=alert(1)>']);await expect(page.locator('.learning-notebook img')).toHaveCount(0);const exported=page.waitForEvent('download');await button(page,'Export learning data (04–11)').click();await (await exported).saveAs('evidence/task-11/browser-qa-imitation.json');
 const context=await browser.newContext({baseURL:'http://127.0.0.1:4173/rl-island/'}),other=await context.newPage();try{await other.goto('#/notebook');await other.locator('#learning-backup-file').setInputFiles('evidence/task-11/browser-qa-imitation.json');await expect(other.getByRole('dialog')).toBeVisible({timeout:30000});await other.locator('#confirm-learning-import').click();await expect(other.locator('#learning-transfer-status')).toContainText('replaced',{timeout:30000});await other.goto('#/lesson/11');await expect(other.getByRole('heading',{name:'Lesson complete',exact:true})).toBeVisible();const restored=(await readStored(other,key)).lessons['11'];expect(restored).toEqual(after.lessons['11']);}finally{await context.close();}expect(errors).toEqual([]);expect(requests.filter(x=>!x.startsWith('http://127.0.0.1:4173/'))).toEqual([]);expect(requests.some(x=>/learner-.*\.js/.test(x))).toBe(false);
});
test('demonstration import is reviewable, isolated, bounded, and rejects misalignment',async({page})=>{test.setTimeout(60000);await page.goto('#/lesson/11');await predict(page);await demos(page);const state=(await readStored(page,key)).lessons['11'],dataset=state.imitation.sessions[0].dataset;const data={format:'rl-island-demonstrations',schemaVersion:1,kind:'self-reported-manual-trajectories',dataset,digest:hashData(dataset)};const imported=structuredClone(data);imported.dataset.trajectories[0].traces[0].observation.x=1;imported.digest=hashData(imported.dataset);await page.locator('#demo-import').setInputFiles({name:'misaligned.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await expect(page.locator('#imitation-status')).toContainText('alignment');await expect(page.getByRole('dialog')).not.toBeVisible();await page.locator('#demo-import').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await expect(page.getByRole('dialog')).toBeVisible();expect(((await readStored(page,key)).lessons['11'].imitation.sessions).length).toBe(1);await button(page,'Add imported experiment').click();await expect(page.locator('.imitation-lab')).toContainText('experiment 2 / 3');const sessions=(await readStored(page,key)).lessons['11'].imitation.sessions;expect(sessions[0]).toEqual(sessions[1]);await fit(page);await page.reload();await expect(page.locator('.imitation-lab')).toContainText('experiment 2 / 3');});
test('comparison controls cancel without granting completion and preserve the immutable fitted session',async({page})=>{test.setTimeout(90000);await setup(page);await stage(page,4);await page.locator('[name="budget"]').fill('1500');await page.locator('[data-imitation-form="compare"] textarea').fill('QA cancellation probe.');await button(page,'Save prediction and run comparison').click();await expect(button(page,'Pause')).toBeEnabled();await button(page,'Pause').click();await expect(page.locator('#imitation-status')).toContainText('worker paused');await button(page,'Resume').click();await expect(button(page,'Pause')).toBeEnabled();await button(page,'Cancel comparison').click();await expect(page.locator('.imitation-comparison')).toContainText('cancelled');expect(((await readStored(page,key)).lessons['11']).completedAt).toBeNull();await button(page,'New experiment').click();await expect(page.locator('.imitation-lab')).toContainText('experiment 2 / 3');const sessions=(await readStored(page,key)).lessons['11'].imitation.sessions;expect(sessions[0].fit).not.toBeNull();expect(sessions[1].fit).toBeNull();});
for(const width of [320,390,768])test('touch controls, fitted tables and accessible layout '+width,async({page})=>{test.setTimeout(90000);await page.setViewportSize({width,height:900});await setup(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await axe(page);await picture(page,'imitation-fitted-'+width);await page.locator('.imitation-lab').screenshot({path:dir+'/imitation-inspector-'+width+'.png'});});
test('all eleven routes expose all six instructional stages with honest initial completion',async({page})=>{test.setTimeout(90000);const audit=[];for(let n=1;n<=11;n++){const id=String(n).padStart(2,'0');await page.goto('#/lesson/'+id);await expect(page.locator('#lesson-runtime')).not.toBeEmpty();const nav=page.getByRole('navigation',{name:'Lesson stages'});await expect(nav.getByRole('button')).toHaveCount(6);await expect(page.getByText('This lesson is unfinished',{exact:true})).toHaveCount(0);await expect(page.getByText('Coming soon',{exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Lesson complete',exact:true})).toHaveCount(0);audit.push({id,title:await page.locator('h1').innerText(),stages:await nav.getByRole('button').allTextContents(),initialComplete:false});}await writeFile('evidence/task-11/eleven-route-audit.json',JSON.stringify(audit,null,2));});

test('malformed fitted arrays are rejected before any learning backup replacement',async({page})=>{test.setTimeout(60000);const backup=JSON.parse(await readFile('evidence/task-11/browser-qa-imitation.json','utf8')),r=backup.progress.lessons['11'],session=r.imitation.sessions[0];session.comparison=null;r.completedAt=null;r.attempts=r.attempts.filter(a=>a.stage!=='challenge');session.fit.history=Object.fromEntries(session.fit.history.map((v,i)=>[i,v]));backup.digest=hashData({progress:backup.progress,runs:backup.runs});await page.goto('#/notebook');const before=await page.evaluate(k=>localStorage.getItem(k),key);await page.locator('#learning-backup-file').setInputFiles({name:'qa-malformed-array.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await expect(page.locator('#learning-transfer-status')).toContainText('Supervised fit differs');await expect(page.getByRole('dialog')).not.toBeVisible();expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(before);});
