import {readStored} from '../helpers/storage.js';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {observedWinner} from '../../src/evaluation/comparison.js';
const dir='evidence/task-11/screenshots',key='rl-island:model-free-progress:v1';
const stage=(p,n)=>p.locator('[data-learning-stage="'+n+'"]').click();
const action=(p,name)=>p.getByRole('button',{name,exact:true});
const picture=async(p,name)=>{await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:dir+'/'+name+'.png',fullPage:true,animations:'disabled'});};
const axe=async p=>expect((await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);
async function predict(p){await stage(p,1);await p.locator('[data-learning-form="prediction"] textarea').fill('Developer QA prediction only: a positive advantage should increase the selected action probability. Compare actual seed variability without assuming a winner.');await action(p,'Save prediction').click();}
async function open(p){await p.goto('#/lesson/08');await predict(p);await stage(p,2);await expect(action(p,'Step')).toBeEnabled();}
async function train(p,n){const before=Number((await p.locator('#run-facts').innerText()).match(/(\d+) completed\/capped episodes/)[1]);await p.getByLabel('Batch episodes',{exact:true}).fill(String(n));await action(p,'Train batch').click();await expect(p.locator('#run-facts')).toContainText((before+n)+' completed/capped episodes',{timeout:90000});await expect(action(p,'Train batch')).toBeEnabled();}
test.beforeAll(()=>mkdir(dir,{recursive:true}));
test('complete lesson 08, real three-method experiment, refresh and backward-compatible backup',async({page,browser})=>{
 test.setTimeout(360000);const errors=[],remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173/'))remote.push(r.url());});await page.setViewportSize({width:1440,height:900});await page.goto('#/notebook');await page.locator('#learning-backup-file').setInputFiles('evidence/task-05/browser-qa-advanced.json');await page.locator('#confirm-learning-import').click();await expect(page.locator('#learning-transfer-status')).toContainText('replaced');const old=(await readStored(page,key)).lessons;
 await page.goto('#/lesson/08');await stage(page,4);await expect(page.getByRole('heading',{name:'Save a prediction first',exact:true})).toBeVisible();await expect(page.locator('.learning-lab')).toHaveCount(0);await stage(page,0);await page.locator('[data-learning-check="observe"] select').selectOption({index:1});await action(page,'Check understanding').click();await expect(page.locator('#learning-feedback')).toContainText('Correct.');await predict(page);await stage(page,2);await expect(action(page,'Step')).toBeEnabled();await expect(page.locator('.policy-compass meter')).toHaveCount(4);await action(page,'Step').focus();await page.keyboard.press('Space');await expect(page.locator('#learning-explanation')).toContainText('categorical sampling');await expect(page.locator('#learning-explanation')).toContainText('Actor and baseline remain fixed');const partial=await page.locator('#learning-fingerprint').innerText();await page.reload();await expect(page.locator('#learning-fingerprint')).toHaveText(partial);await action(page,'Episode').click();await expect(page.locator('#run-facts')).toContainText('1 completed/capped episodes');await train(page,60);await expect(page.locator('#learning-explanation')).toContainText('Actual complete suffix return');await expect(page.locator('#learning-explanation')).toContainText('Δθ');await page.locator('#advanced-inspector').screenshot({path:dir+'/policy-actor-critic-inspector.png'});await page.locator('#learning-explanation').screenshot({path:dir+'/reinforce-actual-update.png'});await picture(page,'lesson-08-play-desktop');await axe(page);
 const digest=await page.locator('#learning-fingerprint').innerText();await action(page,'Evaluate').click();await expect(page.locator('#evaluation-rule')).toContainText('Frozen learned softmax policy');await expect(page.locator('#evaluation-rule')).toContainText('five fresh episodes');expect(await page.locator('#learning-fingerprint').innerText()).toBe(digest);await page.reload();await expect(page.locator('#learning-fingerprint')).toHaveText(digest);await expect(page.locator('#evaluation-rule')).toContainText('five fresh episodes');
 await stage(page,3);await pMath(page,'.289335756','.05805');await picture(page,'lesson-08-mathematics');await stage(page,4);await page.locator('[data-learning-form="comparison"] textarea').fill('QA prior comparison prediction: the baseline may change variance; observed discounted evaluation will decide the measured ranking.');await action(page,'Save prediction and run comparison').click();await expect(page.locator('#comparison-output')).toContainText('complete · 15 / 15',{timeout:180000});await expect(action(page,'Train batch')).toBeEnabled();await expect(page.locator('#comparison-output')).toContainText('Frozen softmax discounted return');await picture(page,'lesson-08-experiment-desktop');await axe(page);
 const comparison=(await readStored(page,key)).lessons['08'].comparisons.at(-1);expect(comparison.runs.every(r=>Object.keys(r.parameters.q).length===0&&r.evaluation.trainingUpdates===0)).toBe(true);expect(new Set(comparison.runs.map(r=>r.algorithm)).size).toBe(3);
 await stage(page,5);await page.locator('[data-learning-check="challenge"] [name="winner"]').selectOption(observedWinner(comparison));await page.locator('[data-learning-check="challenge"] [name="concept"]').selectOption({index:2});await action(page,'Submit challenge').click();await expect(page.locator('#learning-feedback')).toContainText('Not yet.');await page.locator('[data-learning-check="challenge"] [name="winner"]').selectOption(observedWinner(comparison));await page.locator('[data-learning-check="challenge"] [name="concept"]').selectOption({index:1});await action(page,'Submit challenge').click();await expect(page.getByRole('heading',{name:'Lesson complete',exact:true})).toBeVisible();await page.locator('[data-learning-form="reflection"] textarea').fill('Developer QA reflection: saved as text, not evidence of student learning or automatically graded understanding.');await action(page,'Save reflection').click();await expect(page.locator('#learning-feedback')).toContainText('without automatic grading');await picture(page,'lesson-08-complete-desktop');const all=(await readStored(page,key)).lessons;for(const id of ['04','05','06','07'])expect(all[id]).toEqual(old[id]);
 await page.goto('#/island');await expect(page.locator('[data-lesson-status="Complete"]')).toHaveCount(5);await expect(page.locator('[data-lesson-status="Not available yet"]')).toHaveCount(0);await picture(page,'policy-island-desktop');await page.goto('#/notebook');await axe(page);const download=page.waitForEvent('download');await action(page,'Export learning data (04–11)').click();await (await download).saveAs('evidence/task-11/browser-qa-policy.json');
 const context=await browser.newContext({baseURL:'http://127.0.0.1:4173/rl-island/'}),other=await context.newPage();try{await other.goto('#/notebook');await other.locator('#learning-backup-file').setInputFiles('evidence/task-11/browser-qa-policy.json');await other.locator('#confirm-learning-import').click();await expect(other.locator('#learning-transfer-status')).toContainText('replaced');await other.goto('#/lesson/08');await expect(other.getByRole('heading',{name:'Lesson complete',exact:true})).toBeVisible();await stage(other,2);await expect(other.locator('#learning-fingerprint')).toHaveText(digest);await other.goto('#/lesson/11');await expect(other.getByRole('heading',{name:'Observe: learn from demonstrated actions',exact:true})).toBeVisible();}finally{await context.close();}expect(errors).toEqual([]);expect(remote).toEqual([]);
});
async function pMath(p,a,b){await p.locator('[data-learning-check="math"] [name="answer0"]').fill(a);await p.locator('[data-learning-check="math"] [name="answer1"]').fill(b);await action(p,'Check both calculations').click();await expect(p.locator('#learning-feedback')).toContainText('Correct.');}
test('actor-critic step, terminal trace, reset meanings, worker pause/resume/cancel and cap skip',async({page})=>{
 test.setTimeout(120000);await open(page);await page.locator('.learning-config summary').click();await page.getByLabel('Method',{exact:true}).selectOption('actor-critic');await page.getByLabel('Discount gamma').fill('0');await page.getByLabel('Actor / critic step size alpha').fill('0.001');await action(page,'Start new experiment with these settings').click();await action(page,'Step').click();await expect(page.locator('#learning-explanation')).toContainText('Actual TD target');await expect(page.locator('#advanced-inspector')).toContainText('Critic updates: 1');await page.locator('#learning-explanation').screenshot({path:dir+'/actor-critic-actual-update.png'});await train(page,30);await expect(page.locator('#learning-explanation')).toContainText('True terminal');await page.locator('.learning-config summary').click();const parameters=await page.locator('#advanced-inspector details').innerText();await action(page,'Reset episode').click();await expect(page.locator('#learning-feedback')).toContainText('learned parameters preserved');expect(await page.locator('#advanced-inspector details').innerText()).toBe(parameters);
 await page.getByLabel('Batch episodes',{exact:true}).fill('1000');await action(page,'Train batch').click();await expect(page.locator('#learning-status')).toContainText('Worker: training');await action(page,'Pause').click();await expect(page.locator('#learning-status')).toContainText('Worker: paused');const paused=await page.locator('#learning-fingerprint').innerText();await page.waitForTimeout(200);expect(await page.locator('#learning-fingerprint').innerText()).toBe(paused);await page.evaluate(()=>new Promise(resolve=>{const status=document.querySelector('#learning-status');const observer=new MutationObserver(()=>{if(status.textContent.includes('Worker: training')){observer.disconnect();document.querySelector('[data-learning-action="cancel"]').click();resolve();}});observer.observe(status,{childList:true,subtree:true});document.querySelector('[data-learning-action="resume"]').click();}));await expect(page.locator('#learning-feedback')).toContainText('Job cancelled.');await expect(action(page,'Step')).toBeEnabled();await action(page,'Reset learning').click();await action(page,'Start fresh learning').click();await expect(page.locator('#run-facts')).toContainText('0 training interactions');await expect(page.locator('#advanced-inspector')).toContainText('Critic updates: 0');
 await page.locator('.learning-config summary').click();await page.getByLabel('Method',{exact:true}).selectOption('reinforce');await page.getByLabel('External episode cap').fill('1');await action(page,'Start new experiment with these settings').click();await action(page,'Episode').click();await expect(page.locator('#learning-explanation')).toContainText('Incomplete return skipped');await expect(page.locator('#run-facts')).toContainText('0 numerical updates');await expect(page.locator('#advanced-inspector')).toContainText('Baseline is exactly zero');await page.reload();await expect(page.locator('#run-facts')).toContainText('1 incomplete policy returns skipped');await axe(page);
});
test('all three policy methods produce identical seeded results across display speeds',async({page})=>{
 test.setTimeout(240000);const results=[];for(const algorithm of ['reinforce','reinforce-baseline','actor-critic']){const digests=[];for(const speed of ['100','800','0']){await page.goto('#/');await page.evaluate(k=>localStorage.removeItem(k),key);await page.reload();await open(page);if(algorithm!=='reinforce-baseline'){await page.locator('.learning-config summary').click();await page.getByLabel('Method',{exact:true}).selectOption(algorithm);await action(page,'Start new experiment with these settings').click();}await page.getByLabel('Animation / display speed').selectOption(speed);await train(page,30);digests.push(await page.locator('#learning-fingerprint').innerText());}expect(new Set(digests).size).toBe(1);results.push({algorithm,episodes:30,speeds:[100,800,0],digests});}await writeFile('evidence/task-11/policy-animation-replay.json',JSON.stringify({source:'Actual Chromium workers; developer QA, not student results.',results},null,2));
});
for(const width of [320,390,768])test('policy probabilities and update inspector fit accessible viewport '+width,async({page})=>{test.setTimeout(90000);await page.setViewportSize({width,height:900});await open(page);await train(page,10);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await axe(page);await picture(page,'lesson-08-'+width);await page.locator('#advanced-inspector').screenshot({path:dir+'/policy-inspector-'+width+'.png'});});
