import {record,integer,validateScenario,stateFields} from '../environment/schema.js';
import {validateSeed} from '../environment/rng.js';
import {validateDeepConfig} from '../agents/deep/schema.js';
import {stateTableSize} from '../agents/features.js';
/** @typedef {import('../training/config.js').Config} Config */
export const METHODS=['q','sarsa','dyna','linear-sarsa','actor-critic','reinforce','reinforce-baseline','td','mc','linear-td','dqn'];
/** @param {string} method */
export const versionFor=method=>method==='dqn'?'deep-v1':['reinforce','reinforce-baseline','actor-critic'].includes(method)?'policy-v1':method==='dyna'||method.startsWith('linear-')?'features-planning-v1':'tabular-v1';
/** @returns {import('../environment/types.js').Scenario} */
export const laboratoryScenario=()=>validateScenario({schemaVersion:1,id:'laboratory-island',name:'My island',description:'Editable laboratory task.',grid:['...G','.#..','....'],start:{x:0,y:2},slip:0,rewards:{step:-.05,collision:0,goal:1.05,hazard:-1,collectible:.2},features:{collectibles:false,battery:null,horizon:null},observation:'full'});
/** Geometric reachability ignores consumable budgets; it is not a guarantee of success.
 * @param {import('../environment/types.js').Scenario} s */
export function reachableGoal(s){const queue=[s.start],seen=new Set();for(let i=0;i<queue.length;i++){const {x,y}=queue[i],key=x+','+y;if(seen.has(key))continue;seen.add(key);if(s.grid[y][x]==='G')return true;for(const [dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]])if(s.grid[y+dy]?.[x+dx]&&s.grid[y+dy][x+dx]!=='#')queue.push({x:x+dx,y:y+dy});}return false;}
/** @param {import('../environment/types.js').Scenario} s */
export function taskSize(s){return stateTableSize({width:s.grid[0].length,height:s.grid.length,walls:s.grid.join('').split('#').length-1,collectibles:s.grid.join('').split('C').length-1,battery:s.features.battery,horizon:s.features.horizon,actions:4});}
/** @param {string} method @param {import('../environment/types.js').Scenario} s */
export function incompatibility(method,s){const dynamic=stateFields(s).length>2,partial=s.observation==='position'&&dynamic;if(method==='dyna'&&(s.slip!==0||partial))return 'Dyna-Q requires deterministic movement and full Markov observations; its model stores one observed outcome.';if(method.startsWith('linear-')&&partial)return 'Linear encoders require every enabled state variable. Use full observation; the aliased feature option is a separate explicit ablation.';if(method==='dqn'&&dynamic)return 'The current DQN display/checkpoint path supports position-only tasks. Disable collectibles, battery and finite horizon, or select another method.';return '';}
/** @param {unknown} raw @returns {Config} */
export function validateLaboratoryConfig(raw){const c=record(raw,['schemaVersion','algorithmVersion','experimentVersion','lesson','algorithm','policy','gamma','alpha','epsilon','epsilonSchedule','seed','rolloutLimit','scenario','representation','planningSteps','deep','allowUnreachable']);if(c.schemaVersion!==1||c.lesson!=='lab'||!METHODS.includes(String(c.algorithm))||c.algorithmVersion!==versionFor(String(c.algorithm)))throw Error('Unsupported laboratory algorithm/version.');integer(c.experimentVersion,1,1000000);validateSeed(c.seed);integer(c.rolloutLimit,1,200);if(!['right','uniform'].includes(String(c.policy))||c.epsilonSchedule!=='constant'||typeof c.allowUnreachable!=='boolean')throw Error('Declare a fixed policy, constant exploration and unreachable-map intent.');for(const [k,min,max]of /** @type {[string,number,number][]} */([['gamma',0,.99],['alpha',.001,1],['epsilon',0,1]]))if(typeof c[k]!=='number'||!Number.isFinite(c[k])||Number(c[k])<min||Number(c[k])>max)throw Error('Invalid '+k+'.');const scenario=validateScenario(c.scenario);if(scenario.grid.length>12||scenario.grid[0].length>12)throw Error('Laboratory maps are bounded to 2–12 rows and columns.');if(Object.values(scenario.rewards).some(v=>Math.abs(v)>100))throw Error('Laboratory rewards must lie in [-100,100].');if(taskSize(scenario).states>50000n)throw Error('State upper bound exceeds 50,000. Reduce map size, collectibles, battery or horizon.');if(!reachableGoal(scenario)&&!c.allowUnreachable)throw Error('No geometric path reaches a goal. Fix the walls or explicitly allow an intentional unreachable experiment.');const why=incompatibility(String(c.algorithm),scenario);if(why)throw Error(why);if(c.algorithmVersion==='policy-v1'&&(c.epsilon!==0||c.policy!=='uniform'))throw Error('Softmax policy methods require epsilon 0 and policy uniform (fixed-policy setting unused).');if(String(c.algorithm).startsWith('linear-')){if(!['informative','aliased','local-goal'].includes(String(c.representation)))throw Error('Choose informative, aliased or local-goal linear features.');if(c.representation==='local-goal'&&(stateFields(scenario).length!==2||scenario.observation!=='full'||scenario.grid.join('').split('G').length!==2))throw Error('Local-goal features require a static full-observation task with one goal.');}else if(c.representation!==undefined)throw Error('Feature representation belongs to linear methods only.');if(c.algorithm==='dyna')integer(c.planningSteps,0,20);else if(c.planningSteps!==undefined)throw Error('Planning updates belong to Dyna-Q only.');if(c.algorithm==='dqn')validateDeepConfig(/** @type {import('../agents/deep/schema.js').DeepConfig} */(c.deep));else if(c.deep!==undefined)throw Error('Neural configuration belongs to DQN only.');return structuredClone(/** @type {Config} */({...c,scenario}));}
/** @param {import('../training/config.js').Algorithm} [algorithm] @param {import('../environment/types.js').Scenario} [scenario] @returns {Config} */
export function laboratoryConfig(algorithm='q',scenario=laboratoryScenario()){return validateLaboratoryConfig({schemaVersion:1,algorithmVersion:versionFor(algorithm),experimentVersion:1,lesson:'lab',algorithm,policy:'uniform',gamma:.9,alpha:.2,epsilon:versionFor(algorithm)==='policy-v1'?0:.2,epsilonSchedule:'constant',seed:11,rolloutLimit:80,scenario,allowUnreachable:false,...(algorithm.startsWith('linear-')?{representation:'informative'}:{}),...(algorithm==='dyna'?{planningSteps:5}:{}),...(algorithm==='dqn'?{deep:{replay:true,target:true,capacity:256,batch:16,targetEvery:40}}:{})});}
/** New-layout tests only have an explicit compatible shared linear feature representation.
 * @param {Config} source @param {Config} target @param {'known'|'adaptation'|'zero-shot'} track */
export function validateTrack(source,target,track){validateLaboratoryConfig(source);validateLaboratoryConfig(target);if(track==='known'){if(JSON.stringify(source)!==JSON.stringify(target))throw Error('Known-map evaluation must preserve the trained configuration.');return;}if(!['adaptation','zero-shot'].includes(track))throw Error('Unsupported evaluation track.');if(source.algorithm!=='linear-sarsa'||target.algorithm!=='linear-sarsa'||source.representation!=='local-goal'||target.representation!=='local-goal')throw Error('New-layout transfer requires local-goal linear SARSA features (goal direction and local geometry). Coordinate Q-tables, actors and neural coordinate models have no supported transfer contract here.');if(source.scenario.observation!=='full'||target.scenario.observation!=='full'||stateFields(source.scenario).length!==2||stateFields(target.scenario).length!==2||source.scenario.grid.length!==target.scenario.grid.length||source.scenario.grid[0].length!==target.scenario.grid[0].length)throw Error('Transfer requires static fully observed maps with identical dimensions and feature normalization.');if(JSON.stringify(source.scenario.grid)===JSON.stringify(target.scenario.grid))throw Error('Choose a different layout for a new-map track.');if(JSON.stringify(source.scenario.rewards)!==JSON.stringify(target.scenario.rewards)||source.gamma!==target.gamma)throw Error('Keep rewards and discount fixed in a layout-transfer test.');}
