import {setTrainingActive} from '../app/activity.js';
import {escapeHtml as h} from '../ui/escape.js';
import {laboratoryConfig,validateLaboratoryConfig,versionFor} from './config.js';
import {newArtifact,newComparison,runComparison,transferCheckpoint,challengePass} from './records.js';
import {editor,workspaceOutput,evaluationView,comparisonView,expeditionView} from './view.js';
import {exportArchive} from './store.js';
import {TrainingCoordinator} from '../training/coordinator.js';
import {evaluationSeeds} from '../evaluation/frozen.js';
import {hashData} from '../training/config.js';
import {IslandEnvironment} from '../environment/engine.js';
import {createIslandRenderer} from '../rendering/island-renderer.js';
/** @typedef {import('./records.js').Artifact} Artifact */
/** Shared selection between Notebook and laboratory routes; no imported route/code is executed. */
export const laboratorySelection={id:''};
/** @param {HTMLElement} root @param {string} selector @returns {HTMLElement} */
const el=(root,selector)=>{const node=root.querySelector(selector);if(!(node instanceof HTMLElement))throw Error('Missing laboratory control '+selector);return node;};
/** @param {HTMLElement} root @param {string} selector */
const value=(root,selector)=>/** @type {HTMLInputElement} */(el(root,selector)).value;
/** @param {HTMLFormElement} form */
export function configFromForm(form){const d=new FormData(form),get=(/** @type {string} */k)=>String(d.get(k)??/** @type {HTMLInputElement|null} */(form.elements.namedItem(k))?.value??''),num=(/** @type {string} */k)=>Number(get(k)),grid=get('grid').trim().split(/\r?\n/),algorithm=/** @type {import('../training/config.js').Algorithm} */(get('algorithm')),s={...laboratoryConfig().scenario,name:get('title').trim(),grid,start:{x:num('x'),y:num('y')},slip:num('slip'),rewards:{step:num('step'),collision:num('collision'),goal:num('goal'),hazard:num('hazard'),collectible:num('collectible')},features:{collectibles:grid.some(row=>row.includes('C')),battery:get('battery')===''?null:num('battery'),horizon:get('horizon')===''?null:num('horizon')},observation:get('observation')};return validateLaboratoryConfig({...laboratoryConfig(),algorithm,algorithmVersion:versionFor(algorithm),scenario:s,policy:get('policy'),alpha:num('alpha'),gamma:num('gamma'),epsilon:num('epsilon'),seed:num('seed'),rolloutLimit:num('cap'),allowUnreachable:d.has('unreachable'),...(algorithm.startsWith('linear-')?{representation:get('representation')}:{}),...(algorithm==='dyna'?{planningSteps:num('planningSteps')}:{}),...(algorithm==='dqn'?{deep:{replay:true,target:true,capacity:256,batch:16,targetEvery:40}}:{})});}
/** @param {string} text @param {string} name @param {string} [type] */
export function download(text,name,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
/** @param {HTMLElement} root @param {'sandbox'|'compare'|'expedition'} mode @param {import('./store.js').LaboratoryStore} store */
export function mountLaboratory(root,mode,store){const abort=new AbortController();let disposed=false,busy=false,cancelled=false,operation='',workerMode='idle',previewing=false,rawPage=0,comparisonPaused=false;
 let resumeComparison=()=>{};
 /** @type {Promise<void>} */let pauseRequest=Promise.resolve();
 async function comparisonGate(){while(comparisonPaused&&!cancelled&&!disposed)await new Promise(resolve=>{resumeComparison=()=>resolve(undefined);});}
/** @type {Artifact|null} */let active=null;
/** @type {TrainingCoordinator|null} */let coordinator=null;
 const status=el(root,'#lab-status'),dialog=/** @type {HTMLDialogElement} */(el(root,'#lab-reset-dialog'));
 const say=(/** @type {string} */text)=>{if(!disposed)status.textContent=text;};
 function fields(){const method=value(root,'[name="algorithm"]'),softmax=['actor-critic','reinforce','reinforce-baseline'].includes(method);for(const [name,enabled]of [['policy',['td','mc','linear-td'].includes(method)],['representation',method.startsWith('linear-')],['planningSteps',method==='dyna'],['epsilon',!softmax]]){const control=/** @type {HTMLInputElement} */(el(root,'[name="'+name+'"]'));control.disabled=!enabled;}if(softmax){/** @type {HTMLInputElement} */(el(root,'[name="epsilon"]')).value='0';/** @type {HTMLSelectElement} */(el(root,'[name="policy"]')).value='uniform';}}
 function controls(){if(disposed)return;const focused=document.activeElement,effectiveMode=comparisonPaused?'paused':workerMode;for(const button of root.querySelectorAll('button[data-lab]')){const b=/** @type {HTMLButtonElement} */(button),action=b.dataset.lab,ready=Boolean(active&&coordinator),sealed=Boolean(active?.expedition||active?.comparison||active?.failure);b.disabled=['pause','resume','cancel'].includes(action??'')?!busy||!coordinator||(action==='pause'&&(operation==='compare'?comparisonPaused:!['training','evaluating'].includes(workerMode)))||(action==='resume'&&effectiveMode!=='paused'):['step','episode','train','resetEpisode'].includes(action??'')?busy||!ready||sealed||previewing:['save','evaluate','export','resetLearning','reflect','compare','expedition'].includes(action??'')?busy||!active||previewing&&['evaluate','compare','expedition'].includes(action??''):busy;}const submit=root.querySelector('#lab-editor button[type="submit"]');if(submit instanceof HTMLButtonElement)submit.disabled=busy;if(focused instanceof HTMLButtonElement&&root.contains(focused)&&focused.disabled){const action=effectiveMode==='paused'?'resume':['training','evaluating'].includes(workerMode)?'pause':busy?'cancel':'step';const next=root.querySelector('[data-lab="'+action+'"]');const target=next instanceof HTMLButtonElement&&!next.disabled?next:el(root,'#lab-identity');target.tabIndex=target instanceof HTMLButtonElement?0:-1;target.focus({preventScroll:true});}}
 function output(){if(disposed||!active)return;el(root,'#lab-identity').textContent=`${active.title} · ${active.kind} · version ${active.config.experimentVersion} · ${hashData(active.config)} · source training wall ${active.wallMs.toFixed(1)} ms`;el(root,'#lab-output').innerHTML=(active.failure?`<p role="alert">Run stopped: ${h(active.failure)}. Reset learning starts a separate experiment.</p>`:'')+workspaceOutput(active.config,active.checkpoint,rawPage)+active.evaluations.map(e=>`<p>Evaluation after ${e.interactions} real interactions and ${e.updates} learner updates; evaluation wall ${e.wallMs.toFixed(1)} ms.</p>${evaluationView(e.result)}`).join('');const canvas=/** @type {HTMLCanvasElement} */(el(root,'#lab-map'));const env=active.checkpoint?IslandEnvironment.deserialize(active.checkpoint.environment):new IslandEnvironment(active.config.scenario,{seed:active.config.seed,rolloutLimit:active.config.rolloutLimit});createIslandRenderer(canvas).draw(active.config.scenario,env.getState());if(root.querySelector('#lab-comparison-output'))el(root,'#lab-comparison-output').innerHTML=active.comparison?comparisonView(active.comparison):'<p>No comparison results yet.</p>';if(root.querySelector('#lab-expedition-output'))el(root,'#lab-expedition-output').innerHTML=expeditionView(active);controls();}
 async function save(){if(!active)return;active.updatedAt=new Date().toISOString();await store.put(active);laboratorySelection.id=active.id;say(store.message);await savedList();}
 async function savedList(){const list=await store.summaries();if(disposed)return;const select=/** @type {HTMLSelectElement} */(el(root,'#lab-saved'));select.replaceChildren(new Option('Choose a saved record',''),...list.map(a=>new Option(a.kind+' · '+a.title+' · '+a.updatedAt,a.id)));if(active)select.value=active.id;}
 function worker(){coordinator?.dispose();coordinator=new TrainingCoordinator(message=>{if(disposed)return;workerMode=message.mode;controls();if(message.snapshot&&!['compare','expedition'].includes(operation)&&active&&!active.comparison&&!active.expedition)active.checkpoint=message.snapshot.checkpoint;if(message.event==='progress'&&!comparisonPaused)say(`${operation||'Worker'}: ${message.mode} · ${message.snapshot?.checkpoint.interactions??0} real interactions. ${active?.comparison?active.comparison.runs.filter(r=>r.status==='complete').length+'/'+active.comparison.runs.length+' agents finished.':''}`);if(message.event==='paused')say('Worker paused; parameters retained. Resume or cancel.');if(message.event==='error'){if(operation==='compare'&&message.error==='Nothing running to pause.')return;if(active)active.failure=message.error??'Worker failed.';say(message.error??'Worker failed.');}});return coordinator;}
 async function reopen(a=/** @type {Artifact} */(active)){active=structuredClone(a);previewing=false;rawPage=0;if(active.comparison?.status==='pending'){active.comparison.status='cancelled';for(const r of active.comparison.runs)if(r.status==='pending')r.status='cancelled';}el(root,'#lab-editor-container').innerHTML=editor(active.config);fields();/** @type {HTMLTextAreaElement} */(root.querySelector('[name="prediction"]')).value=active.prediction;/** @type {HTMLTextAreaElement} */(el(root,'#lab-reflection')).value=active.reflection;operation='';await worker().initialize(active.config,active.checkpoint??undefined);output();laboratorySelection.id=active.id;await savedList();el(root,'#lab-identity').tabIndex=-1;el(root,'#lab-identity').focus({preventScroll:true});say('Record reopened. Saved configuration and checkpoint restored; changing the editor requires a new experiment. '+store.message);}
 /** @param {()=>Promise<void>} fn */
 async function job(fn){if(busy)throw Error('Pause or cancel the active job first.');busy=true;cancelled=false;setTrainingActive(root,true);controls();try{await fn();}catch(error){if(active?.failure)await save();throw error;}finally{setTrainingActive(root,false);comparisonPaused=false;resumeComparison();busy=false;operation='';if(!disposed){output();controls();}}}
 async function create(kind=/** @type {Artifact['kind']} */('experiment')){const form=/** @type {HTMLFormElement} */(el(root,'#lab-editor')),config=configFromForm(form),prediction=String(new FormData(form).get('prediction')??'').trim();if(kind!=='scenario'&&!prediction)throw Error('Save a prediction before training.');const a=newArtifact({...config,experimentVersion:(active?.config.experimentVersion??0)+1},kind);a.prediction=prediction;active=a;await reopen(a);await save();}
 async function act(/** @type {string} */action){if(action==='showActive'){previewing=false;output();say('Active saved configuration restored.');return;}if(action==='jumpWork'){el(root,'.lab-work').scrollIntoView({block:'start',behavior:'instant'});return;}if(action==='resetNo'){dialog.close();return;}if(['pause','resume','cancel'].includes(action)){
  if(!coordinator)throw Error('No active worker.');const current=coordinator;
  if(operation==='compare'&&action==='pause'){
   comparisonPaused=true;
   pauseRequest=(async()=>{if(['training','evaluating'].includes(workerMode))try{await current.command('pause');}catch(error){if(!(error instanceof Error)||error.message!=='Nothing running to pause.'){comparisonPaused=false;resumeComparison();throw error;}}})();
   await pauseRequest;controls();if(comparisonPaused)say('Comparison paused; current parameters retained. Resume or cancel before the next phase.');return;
  }
  if(operation==='compare'&&action==='resume'){
   await pauseRequest;if(workerMode==='paused')await current.command('resume');comparisonPaused=false;resumeComparison();controls();say('Comparison resumed.');return;
  }
  if(action==='cancel'){cancelled=true;comparisonPaused=false;resumeComparison();}
  await current.command(action);return;
 }if(action==='resetLearning'){dialog.showModal();return;}if(action==='resetYes'){dialog.close();await job(async()=>{if(!active)return;const a=newArtifact({...active.config,experimentVersion:active.config.experimentVersion+1});a.prediction=active.prediction;await reopen(a);await save();});return;}if(action==='preview'){const c=configFromForm(/** @type {HTMLFormElement} */(el(root,'#lab-editor')));previewing=true;el(root,'#lab-output').innerHTML='<p><strong>Preview only.</strong> Create a new experiment to train this configuration.</p>'+(active?'<button class="button secondary" data-lab="showActive">Return to active experiment</button>':'')+workspaceOutput(c,null);controls();const canvas=/** @type {HTMLCanvasElement} */(el(root,'#lab-map'));createIslandRenderer(canvas).draw(c.scenario,new IslandEnvironment(c.scenario).getState());say('Valid configuration. Preview only; existing experiment unchanged until Create new experiment.');return;}if(action==='load'){await job(async()=>{const a=await store.get(value(root,'#lab-saved'));if(!a)throw Error('Select a saved record.');await reopen(a);});return;}if(action==='scenario'){await job(()=>create('scenario'));return;}if(!active)throw Error('Create or reopen an experiment first.');if(action.startsWith('replicate:')){await job(async()=>{if(!active)return;const index=Number(action.split(':')[1]),replicate=active.comparison?.runs[index];if(!replicate?.checkpoint)throw Error('This replicate has no resumable checkpoint.');const a=newArtifact(replicate.checkpoint.config);a.checkpoint=structuredClone(replicate.checkpoint);a.prediction=active.prediction;a.wallMs=replicate.wallMs;a.title=(replicate.method+' · seed '+replicate.seed+' · '+active.title).slice(0,80);a.provenance='Exact continuation from comparison '+active.id+', replicate '+index+', parameters '+hashData(replicate.checkpoint.parameters);await reopen(a);await save();});return;}if(action==='export'){download(exportArchive([active]),'rl-island-laboratory.json');return;}if(action==='reflect'){active.reflection=value(root,'#lab-reflection');await save();return;}if(action==='save'){await save();return;}
 await job(async()=>{if(!active||!coordinator)return;if(action==='compare'){operation='compare';const sourceConfig=active.config;const methods=[...root.querySelectorAll('#lab-methods input:checked')].map(n=>/** @type {HTMLInputElement} */(n).value),seeds=value(root,'#lab-seeds').split(',').map(x=>Number(x.trim())),prediction=value(root,'#lab-comparison-prediction').trim();if(!prediction)throw Error('Save a comparison prediction before results.');const configs=methods.map(method=>{const c=laboratoryConfig(/** @type {import('../training/config.js').Algorithm} */(method));return validateLaboratoryConfig({...c,scenario:sourceConfig.scenario,allowUnreachable:sourceConfig.allowUnreachable,alpha:sourceConfig.alpha,gamma:sourceConfig.gamma,epsilon:c.algorithmVersion==='policy-v1'?0:sourceConfig.epsilon,rolloutLimit:sourceConfig.rolloutLimit,...(method.startsWith('linear-')?{representation:value(root,'[name="representation"]')}:{}),...(method==='dyna'?{planningSteps:Number(value(root,'[name="planningSteps"]'))}:{})});});const comparison=newComparison(configs,seeds,Number(value(root,'#lab-comparison-budget'))),a=newArtifact(configs[0],'comparison');a.prediction=prediction;a.comparison=comparison;active=a;await save();const current=worker();await runComparison(current,comparison,()=>cancelled||disposed,()=>{if(!disposed)el(root,'#lab-comparison-output').innerHTML=comparisonView(comparison);},comparisonGate);await save();return;}
 if(action==='expedition'){if(!active.checkpoint||active.checkpoint.interactions===0)throw Error('Train a source agent first.');operation='expedition';const a=newArtifact(active.config,'expedition');a.prediction=active.prediction;a.reflection=active.reflection;a.checkpoint=structuredClone(active.checkpoint);a.wallMs=active.wallMs;const track=/** @type {import('./records.js').Expedition['track']} */(value(root,'#lab-track')),target=track==='known'?structuredClone(a.config):validateLaboratoryConfig({...a.config,seed:7002,scenario:{...a.config.scenario,grid:value(root,'#lab-target-grid').trim().split(/\r?\n/)}}),initial=transferCheckpoint(active.checkpoint,target,track),budget=track==='adaptation'?Number(value(root,'#lab-adaptation-budget')):0;if(track==='adaptation'&&(!Number.isInteger(budget)||budget<60||budget>5000))throw Error('Adaptation budget must be 60–5,000.');a.expedition={track,target,budget,sourceHash:hashData(active.checkpoint.parameters),checkpoint:null,result:null,wallMs:0,attempts:[]};active=a;await save();const current=worker(),start=performance.now();await current.initialize(target,initial);if(track==='adaptation'){const result=await current.command('trainInteractions',{interactions:budget});if(cancelled||disposed||result.event!=='completed')return;const checkpoint=result.snapshot?.checkpoint;if(!checkpoint)throw Error('Missing target checkpoint.');a.expedition.checkpoint=checkpoint;}else a.expedition.checkpoint=initial;const response=await current.command('evaluate',{seeds:evaluationSeeds(7001)});if(!cancelled&&response.evaluation)a.expedition.result=response.evaluation;a.expedition.wallMs=performance.now()-start;await save();return;}
 if(active.comparison||active.expedition)throw Error('This evidence record is sealed. Create a new experiment to train or evaluate again.');operation=action;const start=performance.now(),command=action==='train'?'trainInteractions':action;let response;try{response=await coordinator.command(command,action==='train'?{interactions:Number(value(root,'#lab-batch'))}:action==='evaluate'?{seeds:evaluationSeeds(9001)}:{});}catch(error){if(action!=='evaluate')active.wallMs+=performance.now()-start;throw error;}if(response.evaluation){if(active.evaluations.length>=20)throw Error('Evaluation history is full; create a new experiment.');active.evaluations.push({result:response.evaluation,interactions:active.checkpoint?.interactions??0,updates:active.checkpoint?.parameters.updates??0,wallMs:performance.now()-start});}if(action!=='evaluate')active.wallMs+=performance.now()-start;await save();});}
 root.addEventListener('click',event=>{const pager=event.target instanceof Element?event.target.closest('[data-raw-page]'):null;if(pager instanceof HTMLButtonElement){rawPage=Number(pager.dataset.rawPage);output();el(root,'#raw-page-status').focus();return;}const button=event.target instanceof Element?event.target.closest('[data-lab]'):null;if(button instanceof HTMLElement)void act(button.dataset.lab??'').catch(error=>say(error.message));},{signal:abort.signal});
 root.addEventListener('submit',event=>{if(!(event.target instanceof HTMLFormElement))return;event.preventDefault();const form=event.target;if(form.id==='lab-editor')void job(()=>create()).catch(error=>say(error.message));if(form.id==='lab-challenge')void(async()=>{if(!active?.expedition?.result)throw Error('Complete a declared evaluation before the challenge.');if(active.expedition.attempts.length>=20)throw Error('Attempt history full; create a new expedition.');const d=new FormData(form),answers=['frozen','state','track'].map(k=>String(d.get(k)));active.expedition.attempts.push({answers,passed:challengePass(active,answers),at:new Date().toISOString()});await save();output();})().catch(error=>say(error.message));},{signal:abort.signal});
 root.addEventListener('change',event=>{if(event.target instanceof HTMLSelectElement&&event.target.name==='algorithm'){fields();say('Only relevant method settings are editable. Softmax uses ε=0 and samples its learned policy. Create a new experiment to apply edits.');}},{signal:abort.signal});fields();
 void(async()=>{await savedList();const a=laboratorySelection.id?await store.get(laboratorySelection.id):null;if(disposed)return;if(a)await job(()=>reopen(a));else {say(store.message);controls();}})().catch(error=>say(error.message));
 return ()=>{disposed=true;cancelled=true;comparisonPaused=false;resumeComparison();setTrainingActive(root,false);abort.abort();dialog.close();coordinator?.dispose();if(active){if(active.comparison?.status==='pending'){active.comparison.status='cancelled';for(const r of active.comparison.runs)if(r.status==='pending')r.status='cancelled';}void store.put(active).catch(()=>{});}};
}
