import {escapeHtml as h} from '../ui/escape.js';
import {exportProgress,importProgress} from '../persistence/progress.js';
import {parseBoundedJson} from '../persistence/bounded-json.js';
import {hashData} from '../training/config.js';
import {exactRecord} from '../training/validation.js';
import {exportArchive,importArchive,exportCsv} from './store.js';
import {download,laboratorySelection} from './controller.js';
/** @typedef {import('./records.js').Artifact} Artifact */
export const notebookArchiveView=()=>`<section class="card lab-archive"><p class="eyebrow">Unified local archive</p><h2>Find and reopen your work</h2><p>Small indexes use localStorage; models, experiment histories and laboratory scenarios use versioned IndexedDB. Lesson backups remain supported below. Export is a backup, not an authenticated grade. Free text is stored without automatic understanding or grading.</p><div class="lab-fields"><label class="field">Filter records<select id="archive-kind">${['all','scenario','experiment','comparison','expedition','agent','prediction','reflection','lesson'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field">Search titles and notes<input id="archive-search" type="search" maxlength="100"></label></div><div class="actions"><button class="button primary" id="archive-json">Export all Notebook JSON</button><button class="button secondary" id="archive-csv">Export all Notebook CSV</button><button class="button secondary" id="archive-lab-csv">Export laboratory raw CSV</button></div><label class="field">Import supported Notebook or laboratory JSON<input id="archive-file" type="file" accept=".json,application/json"></label><p id="archive-status" role="status"></p><div id="archive-records"></div><dialog id="archive-import-dialog" aria-labelledby="archive-import-title"><h2 id="archive-import-title">Review validated records</h2><p id="archive-import-summary"></p><label class="lab-check"><input id="archive-replace" type="checkbox">Replace laboratory records with matching IDs (otherwise duplicates are rejected)</label><p>Notebook backups replace the contained lesson records. Laboratory-only imports leave lessons unchanged. Imported records are inert data; no code or URLs run.</p><button class="button secondary" id="archive-cancel">Cancel import</button><button class="button primary" id="archive-confirm">Import reviewed records</button></dialog><dialog id="archive-delete-dialog" aria-labelledby="archive-delete-title"><h2 id="archive-delete-title">Delete this laboratory record?</h2><p>Export a backup first. Lesson records and unrelated ACML data are preserved.</p><button class="button secondary" id="archive-delete-no">Keep record</button><button class="button primary" id="archive-delete-yes">Delete record</button></dialog></section>`;
/** @param {import('../persistence/progress.js').ProgressStore} foundations @param {import('../persistence/learning-store.js').LearningStore} learning @param {Artifact[]} records */
export async function notebookExport(foundations,learning,records){const payload={foundation:JSON.parse(exportProgress(foundations.data)),learning:JSON.parse(await learning.export()),laboratory:JSON.parse(exportArchive(records))},text=JSON.stringify({format:'rl-island-notebook',schemaVersion:1,kind:'self-reported-evidence',payload,digest:hashData(payload)});if(new TextEncoder().encode(text).length>33554432)throw Error('Notebook exceeds 32 MiB; use separate exports.');return text;}
/** @param {string} text @param {import('../persistence/learning-store.js').LearningStore} learning */
export function notebookImport(text,learning){const raw=parseBoundedJson(text,33554432);if(raw?.format==='rl-island-laboratory')return {records:importArchive(text),foundation:null,learning:null};const v=exactRecord(raw,['format','schemaVersion','kind','payload','digest']);if(v.format!=='rl-island-notebook'||v.schemaVersion!==1||v.kind!=='self-reported-evidence')throw Error('Unsupported Notebook JSON. Use the labeled legacy import controls for legacy lesson backups.');const p=exactRecord(v.payload,['foundation','learning','laboratory']);if(v.digest!==hashData(p))throw Error('Notebook checksum mismatch.');return {records:importArchive(JSON.stringify(p.laboratory)),foundation:importProgress(JSON.stringify(p.foundation)),learning:learning.parseImport(JSON.stringify(p.learning))};}
/** @param {string} text @param {import('../persistence/learning-store.js').LearningStore} learning */
export function notebookCsv(text,learning){const v=notebookImport(text,learning),rows=/** @type {unknown[][]} */([['source','record_id','record_kind','validated_raw_json']]);for(const [id,r]of Object.entries(v.foundation?.lessons??{}))rows.push(['foundation',id,'lesson',JSON.stringify(r)]);for(const [id,r]of Object.entries(v.learning?.progress.lessons??{}))rows.push(['sampled-learning',id,'lesson',JSON.stringify(r)]);for(const [id,r]of Object.entries(v.learning?.runs??{}))rows.push(['sampled-learning',id,'agent-checkpoint',JSON.stringify(r)]);for(const r of v.records)rows.push(['laboratory',r.id,r.kind,JSON.stringify(r)]);return rows.map(row=>row.map(x=>{let text=String(x);if(/^\s*[=+@-]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}).join(',')).join('\r\n');}
/** @param {HTMLElement} root @param {import('./store.js').LaboratoryStore} store @param {import('../persistence/progress.js').ProgressStore} foundations @param {import('../persistence/learning-store.js').LearningStore} learning */
export function mountArchive(root,store,foundations,learning){const abort=new AbortController();let disposed=false,version=0,deleting='';
/** @type {Artifact[]} */let records=[];
/** @type {ReturnType<typeof notebookImport>|null} */let pending=null;
 const get=(/** @type {string} */id)=>/** @type {HTMLElement} */(root.querySelector('#'+id)),status=get('archive-status'),dialog=/** @type {HTMLDialogElement} */(get('archive-import-dialog')),deleteDialog=/** @type {HTMLDialogElement} */(get('archive-delete-dialog')),input=/** @type {HTMLInputElement} */(get('archive-file'));
 function render(){if(disposed)return;const kind=/** @type {HTMLSelectElement} */(get('archive-kind')).value,search=/** @type {HTMLInputElement} */(get('archive-search')).value.toLowerCase();const matching=records.filter(a=>(kind==='all'||a.kind===kind||kind==='agent'&&(a.checkpoint||a.comparison?.runs.some(r=>r.checkpoint))||kind==='prediction'&&a.prediction||kind==='reflection'&&a.reflection)&&[a.title,a.prediction,a.reflection,a.config.algorithm].join(' ').toLowerCase().includes(search));const lessonEntries=[...Object.entries(foundations.data.lessons),...Object.entries(learning.data.lessons)].filter(([,r])=>['all','lesson'].includes(kind)||kind==='prediction'&&r.prediction||kind==='reflection'&&r.reflection||kind==='experiment'&&('experiments' in r&&r.experiments.length||'runIds' in r&&(r.runIds.length||r.imitation?.sessions.length))||kind==='comparison'&&('comparisons' in r&&(r.comparisons.length||r.imitation?.sessions.some(s=>s.comparison)))||kind==='agent'&&('runIds' in r&&r.runIds.length||'imitation' in r&&r.imitation?.sessions.some(s=>s.fit))).filter(([id,r])=>(id+' '+r.prediction?.answer+' '+r.reflection).toLowerCase().includes(search));get('archive-records').innerHTML=matching.map(a=>`<article class="notebook-entry"><p class="eyebrow">${h(a.kind)} · ${h(a.updatedAt)}</p><h3>${h(a.title)}</h3><p>${h(a.provenance)}</p><p>${h(a.config.algorithm)} · ${a.checkpoint?.interactions??0} source interactions · ${a.comparison?.runs.length??0} requested comparison replicates</p><p>Prediction: ${h(a.prediction||'Not recorded')}</p><p>Reflection: ${h(a.reflection||'Not recorded')}</p><div class="actions"><button class="button secondary" data-reopen="${h(a.id)}">Reopen record</button><button class="button secondary" data-export-record="${h(a.id)}">Export record JSON</button><button class="button secondary" data-delete-record="${h(a.id)}">Delete record</button></div></article>`).join('')+lessonEntries.map(([id,r])=>`<article class="notebook-entry"><p class="eyebrow">Lesson ${h(id)}</p><p>Prediction: ${h(r.prediction?.answer??'Not recorded')}</p><p>Reflection: ${h(r.reflection||'Not recorded')}</p><a href="#/lesson/${h(id)}">Reopen lesson ${h(id)} and its saved experiments</a></article>`).join('')||'<p>No matching records. Create a scenario or complete a lesson activity to begin.</p>';}
 async function refresh(){records=await store.all();if(disposed)return;render();status.textContent=store.message;}
 root.addEventListener('input',event=>{if(event.target instanceof HTMLElement&&['archive-kind','archive-search'].includes(event.target.id))render();},{signal:abort.signal});
 root.addEventListener('click',event=>{const b=event.target instanceof Element?event.target.closest('button'):null;if(!b)return;void(async()=>{if(b.dataset.reopen){const a=records.find(a=>a.id===b.dataset.reopen);if(!a)return;laboratorySelection.id=a.id;location.hash=a.kind==='comparison'?'#/compare':a.kind==='expedition'?'#/expedition':'#/sandbox';}if(b.dataset.exportRecord){const a=records.find(a=>a.id===b.dataset.exportRecord);if(a)download(exportArchive([a]),'rl-island-record.json');}if(b.dataset.deleteRecord){deleting=b.dataset.deleteRecord;deleteDialog.showModal();}if(b.id==='archive-delete-no'){deleting='';deleteDialog.close();}if(b.id==='archive-delete-yes'&&deleting){await store.remove(deleting);deleting='';deleteDialog.close();await refresh();}if(b.id==='archive-json'||b.id==='archive-csv'){const text=await notebookExport(foundations,learning,records);if(disposed)return;download(b.id==='archive-json'?text:notebookCsv(text,learning),b.id==='archive-json'?'rl-island-notebook.json':'rl-island-notebook.csv',b.id==='archive-json'?'application/json':'text/csv');status.textContent='Validated Notebook export created. CSV carries raw JSON records in quoted cells; use laboratory raw CSV for episode columns. CSV is not an import format. '+learning.message;}if(b.id==='archive-lab-csv')download(exportCsv(records),'rl-island-laboratory-raw.csv','text/csv');if(b.id==='archive-cancel'){version++;pending=null;input.value='';dialog.close();}if(b.id==='archive-confirm'&&pending){const candidate=pending;await store.import(candidate.records,/** @type {HTMLInputElement} */(get('archive-replace')).checked);if(candidate.foundation)foundations.replace(candidate.foundation);if(candidate.learning)await learning.replace(candidate.learning);pending=null;input.value='';dialog.close();await refresh();status.textContent='Validated records imported. '+store.message+' '+(candidate.learning?learning.message:'')+(candidate.foundation?' '+foundations.message:'');}})().catch(error=>{if(!disposed)status.textContent=error.message;});},{signal:abort.signal});
 input.addEventListener('change',()=>{const file=input.files?.[0],load=++version;if(!file)return;void(async()=>{if(file.size>33554432)throw Error('Notebook import exceeds 32 MiB.');const text=await file.text();if(disposed||load!==version)return;pending=notebookImport(text,learning);get('archive-import-summary').textContent=`Validated ${pending.records.length} laboratory records${pending.foundation?', plus lesson progress and agents':''}. Review replacement choice before importing.`;dialog.showModal();})().catch(error=>{if(!disposed){pending=null;status.textContent=error.message;input.value='';}});},{signal:abort.signal});dialog.addEventListener('cancel',()=>{version++;pending=null;input.value='';},{signal:abort.signal});void refresh();return ()=>{disposed=true;abort.abort();dialog.close();deleteDialog.close();};}
