import {parseBoundedJson} from '../persistence/bounded-json.js';
import {hashData} from '../training/config.js';
import {exactRecord} from '../training/validation.js';
import {validateArtifact,evaluationSummary} from './records.js';
/** @typedef {import('./records.js').Artifact} Artifact */
export const ARCHIVE_KEY='rl-island:laboratory-index:v1';
export const MAX_ARCHIVE_BYTES=16777216;
/** @param {Artifact[]} records */
export function exportArchive(records){if(records.length>30)throw Error('Archive limit is 30 records.');const validated=records.map(validateArtifact);const text=JSON.stringify({format:'rl-island-laboratory',schemaVersion:1,kind:'self-reported-evidence',createdAt:new Date().toISOString(),records:validated,digest:hashData(validated)});if(new TextEncoder().encode(text).length>MAX_ARCHIVE_BYTES)throw Error('Export exceeds 16 MiB; export fewer records.');return text;}
/** @param {string} text */
export function importArchive(text){const v=exactRecord(parseBoundedJson(text,MAX_ARCHIVE_BYTES),['format','schemaVersion','kind','createdAt','records','digest']);if(v.format!=='rl-island-laboratory'||v.schemaVersion!==1||v.kind!=='self-reported-evidence'||typeof v.createdAt!=='string'||v.createdAt.length>30||!Array.isArray(v.records)||v.records.length>30)throw Error('Only supported laboratory JSON records can be imported. CSV is export-only.');if(v.digest!==hashData(v.records))throw Error('Archive checksum mismatch (corruption check, not authentication).');const records=v.records.map(validateArtifact);if(new Set(records.map(r=>r.id)).size!==records.length)throw Error('Duplicate record IDs.');return records;}
/** Spreadsheet formula prefixes are escaped; CSV is never imported as executable data.
 * @param {unknown} value */
function csvCell(value){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s)&&typeof value!=='number')s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
/** Long-form rows retain every requested run, failure, raw episode and evaluation.
 * @param {Artifact[]} records */
export function exportCsv(records){const rows=
/** @type {unknown[][]} */([['record','kind','title','metric_kind','method','training_seed','budget','episode_or_checkpoint','evaluation_seed','return','success','length','real_interactions','updates','planning_updates','wall_ms','status','text']]);for(const a of records.map(validateArtifact)){rows.push([a.id,a.kind,a.title,'prediction',a.config.algorithm,a.config.seed,'','','','','','','','','','','',a.prediction],[a.id,a.kind,a.title,'reflection','','','','','','','','','','','','','ungraded',a.reflection]);const add=(
/** @type {import('./records.js').Checkpoint} */ cp,
/** @type {string} */status,
/** @type {number} */wall)=>{for(const r of cp.rows)rows.push([a.id,a.kind,a.title,'training',cp.config.algorithm,cp.config.seed,cp.interactions,r.episode,'',r.return,r.success,r.length,cp.interactions,cp.parameters.updates,cp.parameters.planningUpdates??0,wall,status,'Raw observed episode; interrupted='+r.interrupted]);};const evalRows=(
/** @type {import('./records.js').Evaluation} */e,
/** @type {string} */method,
/** @type {number} */seed,
/** @type {number} */budget,
/** @type {string} */track)=>{for(const [i,r]of e.rows.entries())rows.push([a.id,a.kind,a.title,'frozen-evaluation',method,seed,budget,i+1,r.seed,r.return,r.success,r.length,budget,0,0,'',track,e.rule]);};if(a.checkpoint)add(a.checkpoint,'saved',a.wallMs);a.evaluations.forEach(e=>evalRows(e.result,a.config.algorithm,a.config.seed,e.interactions,'known'));if(a.comparison)for(const r of a.comparison.runs){rows.push([a.id,a.kind,a.title,'replicate',r.method,r.seed,a.comparison.budget,'','','','','',r.checkpoint?.interactions??0,r.checkpoint?.parameters.updates??0,r.checkpoint?.parameters.planningUpdates??0,r.wallMs,r.status,r.error]);if(r.checkpoint)add(r.checkpoint,r.status,r.wallMs);for(const p of r.curve)evalRows(p.evaluation,r.method,r.seed,p.interactions,'comparison');}if(a.expedition?.result){evalRows(a.expedition.result,a.expedition.target.algorithm,a.expedition.target.seed,a.expedition.budget,a.expedition.track);rows.push([a.id,a.kind,a.title,'challenge','','','','','','',evaluationSummary(a.expedition.result).success,'','','','',a.expedition.wallMs,a.expedition.attempts.some(t=>t.passed)?'complete':'incomplete',JSON.stringify(a.expedition.attempts)]);}}return rows.map(r=>r.map(csvCell).join(',')).join('\r\n');}
/** Larger versioned artifacts live in IndexedDB; localStorage contains only a small index.
 * Dependency injection lets tests exercise denied/quota/transaction failures. */
export class LaboratoryStore{
 /** @param {Pick<Storage,'getItem'|'setItem'>} storage @param {IDBFactory|null} [factory] @param {boolean} [memoryOnly] */
 constructor(storage,factory,memoryOnly=false){this.memoryOnly=memoryOnly;if(factory===undefined){try{factory=globalThis.indexedDB??null;}catch{factory=null;}}this.storage=storage;this.factory=factory;this.message='Laboratory records stay on this device. Export a backup.';this.indexBlocked=false;
/** @type {Map<string,Artifact>} */this.memory=new Map();
/** @type {Promise<IDBDatabase>|null} */this.database=null;try{const text=storage.getItem(ARCHIVE_KEY);if(text){const v=exactRecord(parseBoundedJson(text,32768),['schemaVersion','records']);if(v.schemaVersion!==1||!Array.isArray(v.records)||v.records.length>30)throw Error('Unsupported index.');}}catch{this.indexBlocked=true;this.message='Small-record storage could not be read. Existing index preserved; IndexedDB records can still be recovered.';}}
 db(){return this.database??=new Promise((resolve,reject)=>{if(!this.factory){reject(Error('IndexedDB is unavailable.'));return;}const req=this.factory.open('rl-island-laboratory',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('artifacts'))req.result.createObjectStore('artifacts',{keyPath:'id'});};req.onsuccess=()=>{const db=req.result;db.onversionchange=()=>db.close();resolve(db);};req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('Database upgrade blocked; close other RL Island tabs.'));});}
 /** Read only unknown records. Known tab-local records have already been validated;
  * getAll would repeatedly clone every archived trajectory on each save. */
 async refresh(){if(this.memoryOnly)return;try{const db=await this.db();await new Promise((resolve,reject)=>{const tx=db.transaction('artifacts'),store=tx.objectStore('artifacts'),keys=store.getAllKeys();keys.onsuccess=()=>{for(const id of keys.result){if(typeof id==='string'&&this.memory.has(id))continue;const req=store.get(id);req.onsuccess=()=>{try{const a=validateArtifact(req.result);this.memory.set(a.id,a);}catch(error){reject(error);}};req.onerror=()=>reject(req.error);}};keys.onerror=()=>reject(keys.error);tx.oncomplete=()=>resolve(undefined);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??Error('Archive read aborted.'));});}catch(error){this.message='Archive storage unavailable or unsupported: '+(error instanceof Error?error.message:'read failed')+' Keep this tab open and export memory-only records.';}}
 async all(){await this.refresh();return [...this.memory.values()].map(a=>structuredClone(a));}
 /** Dropdowns and save bookkeeping need metadata, never copies of every model. */
 async summaries(){await this.refresh();return [...this.memory.values()].map(a=>({id:a.id,title:a.title,kind:a.kind,updatedAt:a.updatedAt}));}
 /** @param {string} id */async get(id){await this.refresh();const a=this.memory.get(id);return a?structuredClone(a):undefined;}
 /** @param {Artifact} artifact */async put(artifact){await this.import([artifact],true);}
 /** @param {Artifact[]} records @param {boolean} replace */
 async import(records,replace=false){const valid=records.map(validateArtifact),old=await this.summaries(),ids=new Set(old.map(a=>a.id));if(new Set(valid.map(a=>a.id)).size!==valid.length)throw Error('Duplicate record IDs.');if(!replace&&valid.some(a=>ids.has(a.id)))throw Error('An ID already exists. Choose explicit replacement or keep your current records.');valid.forEach(a=>ids.add(a.id));if(ids.size>30)throw Error('Archive limit is 30 records; export and delete records before adding more.');if(this.memoryOnly){for(const a of valid)this.memory.set(a.id,structuredClone(a));this.message='Temporary lecture archive in memory; personal records are unchanged.';return;}try{const db=await this.db();await new Promise((resolve,reject)=>{const tx=db.transaction('artifacts','readwrite');for(const a of valid)tx.objectStore('artifacts').put(a);tx.oncomplete=()=>resolve(undefined);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??Error('Transaction aborted.'));});this.message='Saved to IndexedDB. Export a backup before clearing browser data.';}catch(error){this.message='IndexedDB save failed: '+(error instanceof Error?error.message:'storage error')+' Records remain in memory only; export before closing.';}for(const a of valid)this.memory.set(a.id,structuredClone(a));this.saveIndex();}
 saveIndex(){try{if(this.indexBlocked)throw Error('Existing index is protected.');this.storage.setItem(ARCHIVE_KEY,JSON.stringify({schemaVersion:1,records:[...this.memory.values()].map(a=>({id:a.id,title:a.title,kind:a.kind,updatedAt:a.updatedAt}))}));}catch{this.message+=' Small-record index could not be saved; IndexedDB and JSON export remain separate recovery paths.';}}
 /** @param {string} id */async remove(id){if(this.memoryOnly){this.memory.delete(id);return;}try{const db=await this.db();await new Promise((resolve,reject)=>{const tx=db.transaction('artifacts','readwrite');tx.objectStore('artifacts').delete(id);tx.oncomplete=()=>resolve(undefined);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}catch(error){if(!this.memory.has(id))throw error;this.message='Persistent deletion failed; only the memory copy was removed. Export and check browser storage.';}this.memory.delete(id);this.saveIndex();}
}
