import { learningComplete } from '../lessons/learning-records.js';
import { checkAttempt, completion } from '../lessons/records.js';
import { foundations } from '../content/foundations.js';
import { lessons } from '../content/curriculum.js';
import { escapeHtml as h } from './escape.js';
/** @param {import('../content/curriculum.js').Lesson} lesson */
export function guidedLessonView(lesson) {
  return `<a class="back-link" href="#/island">← All lessons</a><div class="lesson-heading"><div><p class="eyebrow">Lesson ${lesson.id} / 11 · ${lesson.region}</p><h1 tabindex="-1">${lesson.title}</h1></div><span class="badge">Guided lesson · local progress</span></div><div id="lesson-runtime"></div>`;
}
/** @param {import('../content/curriculum.js').Lesson} lesson */
export function unfinishedLessonView(lesson) {
  return `<a class="back-link" href="#/island">← All lessons</a><div class="page-heading"><p class="eyebrow">Lesson ${lesson.id} · ${lesson.region}</p><h1 tabindex="-1">${lesson.title}</h1></div><section class="card empty-state"><span class="badge rose">Not available yet</span><h2>This lesson is unfinished</h2><p>Its activities, checks, and challenge are not implemented. Visiting this page grants no completion. Lessons 01–11 are available.</p><div class="actions"><a class="button primary" href="#/lesson/01">Start lesson 01</a><a class="button secondary" href="#/practice">Open the free manual lab</a></div></section>`;
}
/** @param {import('../persistence/progress.js').Progress} progress */
export function learningNotebookView(progress) {
  return `<div class="page-heading"><p class="eyebrow">Your thinking, collected</p><h1 tabindex="-1">Notebook</h1><p class="lede">Predictions, numerical evidence, and reflections from your activities. Local, self-reported records; not authenticated grades.</p></div>
  <section class="card notebook-card"><div class="notebook-toolbar"><div class="tabs" role="tablist" aria-label="Notebook sections"><button role="tab" id="notes-reflections" aria-selected="true" aria-controls="notebook-entries" data-record-tab="reflections">Reflections</button><button role="tab" id="notes-experiments" aria-selected="false" aria-controls="notebook-entries" tabindex="-1" data-record-tab="experiments">Experiments</button><button role="tab" id="notes-progress" aria-selected="false" aria-controls="notebook-entries" tabindex="-1" data-record-tab="progress">Completion</button></div><button class="button primary" id="export-progress">Export progress</button></div><div id="notebook-entries" role="tabpanel" aria-labelledby="notes-reflections" tabindex="0"></div></section>
  <section class="card progress-transfer"><h2>Foundations backup · lessons 01–03</h2><p>Export a JSON backup for these three lessons. Import validates the schema, environment replay, and numerical evidence before offering replacement. Existing display settings and manual-lab saves are preserved. Files remain on your device.</p><span id="notebook-resume">${progress.lastLesson ? `<a class="button secondary" href="#/lesson/${progress.lastLesson}">Resume lesson ${progress.lastLesson}</a>` : ''}</span>
  <label class="field">Progress JSON file<input type="file" accept=".json,application/json" id="progress-file"></label><p id="transfer-status" role="status"></p></section>
  <dialog id="import-progress-dialog" aria-labelledby="import-progress-title"><h2 id="import-progress-title">Replace saved lesson progress?</h2><p id="import-preview"></p><p>This replaces the three lesson records. Export your current record first if you want to keep it. A checksum checks accidental corruption; it does not authenticate a grade.</p><div class="actions"><button class="button secondary" id="cancel-import">Cancel</button><button class="button primary" id="confirm-import">Replace progress</button></div></dialog>`;
}
/** @param {'reflections'|'experiments'|'progress'} tab @param {import('../persistence/progress.js').Progress} progress @param {import('../persistence/learning-store.js').LearningProgress} [learning] */
export function notebookEntries(tab,progress,learning={schemaVersion:1,lastLesson:null,lessons:{}}) {
  const entries = Object.entries(progress.lessons);
  if (tab === 'reflections') {
    const notes = entries.filter(([,r]) => r.reflection);
    return notes.length ? notes.map(([id,r]) => `<article class="notebook-entry"><p class="eyebrow">Lesson ${id} · saved reflection</p><p class="reflection-text">${h(r.reflection)}</p><small>${h(r.reflectionAt)} · saved, not automatically graded</small></article>`).join('') : '<div class="empty-state"><h2>No reflections yet for lessons 01–03</h2><p>Save a foundation reflection here; lessons 04–11 have their own records below. Free text is not automatically understood or graded.</p></div>';
  }
  if (tab === 'progress') return `<div class="notebook-entry"><h2>Activity completion</h2><p>Based on recorded activities and explicit checks, not stage navigation.</p><ul>${lessons.map((l) => `<li>Lesson ${l.id}: ${l.id in foundations ? completion(/** @type {import('../content/foundations.js').FoundationId} */(l.id),progress.lessons[/** @type {import('../content/foundations.js').FoundationId} */(l.id)]) ? 'Complete' : 'Incomplete' : ['04','05','06','07','08','09','10','11'].includes(l.id) ? learningComplete(/** @type {'04'|'05'|'06'|'07'|'08'|'09'|'10'|'11'} */(l.id),learning.lessons[/** @type {'04'|'05'|'06'|'07'|'08'|'09'|'10'|'11'} */(l.id)]) ? 'Complete' : 'Incomplete' : 'Not available yet'}</li>`).join('')}</ul></div>${entries.filter(([,r]) => r.attempts.length).map(([id,r]) => `<article class="notebook-entry"><h3>Lesson ${id} · explicit check history</h3><p>All attempts are retained. Free-text predictions and reflections are not graded.</p><ol>${r.attempts.map((a) => `<li><strong>${h(a.stage)}: ${checkAttempt(/** @type {import('../content/foundations.js').FoundationId} */(id),r,a) ? 'Correct' : 'Try again'}</strong> — ${a.answers.map(h).join(' · ')}${a.trial !== null && a.trial >= 0 ? ' · experiment ' + (a.trial+1) : ''}<br><small>${h(a.at)}</small></li>`).join('')}</ol></article>`).join('')}`;
  const trials = entries.flatMap(([id,r]) => [
    ...(r.prediction ? [`<article class="notebook-entry"><p class="eyebrow">Lesson ${id} · initial prediction</p><p>${h(r.prediction.answer)}</p><small>Saved ${h(r.prediction.at)}, before results.</small></article>`] : []),
    ...r.experiments.map((t,i) => `<article class="notebook-entry"><p class="eyebrow">Lesson ${id} · experiment ${i+1}</p><h3>Prediction: ${h(t.prediction.answer)}</h3><p>Parameter: ${t.config.parameter} (${id==='02' ? 'slip, fixed right policy and γ=0.9' : 'discount γ'}). ${t.result ? 'Computed result saved.' : 'Not run yet.'}</p>${t.result ? `<dl><dt>Algorithms</dt><dd>${h(t.result.algorithms.join(', '))}</dd><dt>Values</dt><dd><code>${h(JSON.stringify(t.result.values))}</code></dd><dt>Bellman residuals</dt><dd>${h(t.result.residuals.join(', ') || 'Not applicable to a finite reward sequence')}</dd><dt>Value sweeps</dt><dd>${h(t.result.sweeps.join(', ') || 'Not applicable')}</dd><dt>Scenario</dt><dd>${h(t.result.scenarioHash)}</dd><dt>Representation / calculation version</dt><dd>${h(t.result.context.representation)} / ${h(t.result.context.calculationVersion)}</dd><dt>Sampling seed</dt><dd>None: exact calculation, no random sampling</dd></dl>` : ''}<small>Prediction saved ${h(t.prediction.at)}. Exact model calculations use no random sampling.</small></article>`)
  ]);
  return trials.length ? trials.join('') : '<div class="empty-state"><h2>No experiments yet for lessons 01–03</h2><p>Foundation predictions and computed experiments appear here; lessons 04–11 have their own records below.</p></div>';
}

