import {preferences,softmax} from '../agents/policy.js';
import {stateKey,ACTIONS} from '../environment/schema.js';
import {escapeHtml as h} from './escape.js';
/** @param {number} x */
const f=x=>Number(x.toFixed(6)).toString();
/** @param {import('../training/run.js').RunCheckpoint} c @param {import('../environment/types.js').State} state */
export function policyInspector(c,state){const key=stateKey(state),theta=preferences(c.parameters,key),probs=softmax(theta),terminal=c.config.scenario.grid[state.y][state.x]==='G';return `<h3>Actor and critic · actual state ${h(key)}</h3><p>${terminal?'Goal terminal: no further action will be sampled. The stored distribution below is not executed.':'The next action will be sampled from these current probabilities.'} All arrows are probabilities, not action values.</p><div class="policy-compass" role="group" aria-label="Action probabilities around Robo">${probs.map((p,a)=>`<div class="probability-${a}"><strong>${['↑ Up','→ Right','↓ Down','← Left'][a]}</strong><span>${f(p*100)}%</span><meter min="0" max="1" value="${p}" aria-label="${ACTIONS[a]} probability">${p}</meter></div>`).join('')}<div class="probability-robo" aria-label="Robo">Robo<br><svg viewBox="0 0 100 100" aria-hidden="true" focusable="false"><g stroke="#64748b" stroke-width="1.5" fill="#f8fafc"><rect x="27" y="46" width="46" height="39" rx="5"/><rect x="18" y="22" width="64" height="38" rx="6"/></g><rect x="27" y="31" width="46" height="17" rx="4" fill="#1e3a5f"/><g fill="#bfdbfe"><circle cx="39" cy="39" r="4.5"/><circle cx="61" cy="39" r="4.5"/></g><g fill="#2563eb"><rect x="42" y="65" width="16" height="4.5"/><circle cx="50" cy="15" r="4.5"/></g></svg></div></div><p><strong>Actor preferences θ</strong> [${theta.map(f).join(', ')}] · softmax temperature 1. The actor samples; it does not use argmax.</p><p><strong>Critic V(${h(key)})</strong>: ${c.config.algorithm==='reinforce'?'Not used. Baseline is exactly zero.':f(c.parameters.v[key]??0)+' · estimate of discounted future reward under the actor, not a probability or action recommendation.'}</p><p>Critic updates: ${c.parameters.criticUpdates??0}. Incomplete REINFORCE returns skipped: ${c.parameters.skippedPolicy??0}. Skipping capped episodes can bias the retained sample; inspect caps and increase the limit when needed.</p><details><summary>All learned actor preferences and critic values</summary><div class="table-scroll" tabindex="0" role="region" aria-label="Policy parameters"><table><caption>Full precision retained in exports; displayed values rounded to six decimals</caption><thead><tr><th>State</th><th>θ up / right / down / left</th><th>Critic V</th></tr></thead><tbody>${Object.entries(c.parameters.actor??{}).map(([s,v])=>`<tr><th>${h(s)}</th><td>${v.map(f).join(' / ')}</td><td>${c.config.algorithm==='reinforce'?'unused':f(c.parameters.v[s]??0)}</td></tr>`).join('')}</tbody></table></div></details>`;}
/** @param {import('../agents/tabular.js').Update} u */
function updateView(u){const p=u.policy;if(!p)return '';return `<article class="actual-update"><h4>${h(u.method)} · state ${h(u.state)} · ${ACTIONS[u.action??0]} · t=${p.time}</h4><p>${p.kind==='return'?`Actual complete suffix return Gt = ${f(u.target)}. Frozen selection-time baseline = ${f(u.old)}; advantage = ${f(u.error)}.`:`Actual TD target = ${f(u.reward)} + ${f(u.gamma)} × ${f(u.bootstrap)} = ${f(u.target)}. Critic before = ${f(u.old)}; TD error δ = ${f(u.error)}.`} ${u.terminated?'True terminal: no continuation.':u.truncated?'External timeout: critic continuation retained.':''}</p><p>Selection-time probabilities = [${p.probabilities.map(f).join(', ')}].<br>Score ∇logπ = onehot(a) − π = [${p.gradient.map(f).join(', ')}].<br>Actor multiplier α × γ^t × ${p.kind==='return'?'advantage':'δ'} = ${f(p.actorAlpha)} × ${f(p.discount)} × ${f(u.error)}.<br>θ before = [${p.preferencesBefore.map(f).join(', ')}].<br>Δθ = [${p.gradient.map(g=>f(p.actorAlpha*p.discount*u.error*g)).join(', ')}].<br>θ after = [${p.preferencesAfter.map(f).join(', ')}].<br>Softmax after this contribution = [${softmax(p.preferencesAfter).map(f).join(', ')}].</p><p>${p.criticUpdated?`Critic update = ${f(p.criticBefore)} + ${f(u.alpha)} × ${f(u.error)} = ${f(u.next)}. ${p.kind==='return'?'Residual uses the frozen episode baseline; repeated-state contributions accumulate.':''}`:'No critic update: plain REINFORCE baseline is zero.'} The actor treats the sampled signal as a constant.</p></article>`;}
/** @param {import('../training/run.js').LearningTrace|null} trace */
export function policyExplanation(trace){if(!trace)return '<h3>Why this action?</h3><p>No action sampled yet. Step to record a real categorical decision.</p>';const d=trace.decision,t=trace.transition;return `<h3>Why this action?</h3><p>Actor chose <strong>${ACTIONS[d.action]}</strong> at ${h(d.state)} by categorical sampling. Draw ${f(d.actionDraw??0)} falls in the chosen action’s cumulative probability interval. Recorded probabilities [up, right, down, left] = [${d.probabilities.map(f).join(', ')}].</p><p>Actual transition: ${h(d.state)} → ${ACTIONS[d.action]} → reward ${t.reward} → ${h(stateKey(t.nextState))}. Terminated ${t.terminated}; truncated ${t.truncated}.</p><h3>Actual policy update calculation</h3><p class="small">Six-decimal display; exports retain full precision. REINFORCE applies a complete episode gradient as a sum of the recorded selection-time contributions. The final contribution is shown first.</p>${trace.updates.length?updateView(trace.updates[trace.updates.length-1])+ (trace.updates.length>1?`<details><summary>${trace.updates.length-1} earlier contributions from this complete episode</summary>${trace.updates.slice(0,-1).map(updateView).join('')}</details>`:''):`<p>${t.truncated?'Incomplete return skipped; no episodic actor or baseline update.':'REINFORCE is collecting a return. Actor and baseline remain fixed until genuine termination.'}</p>`}`;}
