import {rememberFocus} from '../ui/focus.js';
import {stages} from '../content/curriculum.js';
import {imitationLessons} from '../content/imitation.js';
import {learningComplete,learningCheck,learningRequirements} from '../lessons/learning-records.js';
import {emptyImitation,newSession} from './records.js';
import {DemonstrationRecorder,demonstrationScenario} from './demonstrations.js';
import {exportDataset,importDataset,MAX_DATASET_BYTES,pairs,nextTrajectoryId} from './demonstrations.js';
import {BehaviorCloner} from './cloning.js';
import {newImitationComparison,runImitationComparison} from './experiment.js';
import {datasetView,fitView,imitationComparisonView,table} from './view.js';
import {createIslandRenderer,describeCell} from '../rendering/island-renderer.js';
import {TrainingCoordinator} from '../training/coordinator.js';
import {escapeHtml as h} from '../ui/escape.js';
import {ACTIONS} from '../environment/schema.js';
import {hashData} from '../training/config.js';
import {deriveSeed} from '../environment/rng.js';
/** @param {string} label @param {string} action @param {boolean} [disabled] */
const button=(label,action,disabled=false)=>`<button class="button secondary" data-imitation-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
/** @param {string[]} choices @param {string} name */
const select=(choices,name)=>`<select name="${name}" required><option value="">Choose an answer</option>${choices.map(c=>`<option>${h(c)}</option>`).join('')}</select>`;
/** Six-stage lesson adapter using the common stage names, activity gates and learning backup.
 * @param {HTMLElement} root @param {import('../persistence/learning-store.js').LearningStore} store */
export function mountImitationLesson(root,store){
 const record=store.lesson('11'),imitation=record.imitation??=emptyImitation(),content=imitationLessons['11'],abort=new AbortController();
 let disposed=false,busy=false,cancelled=false,feedback='',workerMode='idle';
 /** @type {DemonstrationRecorder|null} */let recorder=null;
 /** @type {TrainingCoordinator|null} */let coordinator=null;
 /** @type {import('./demonstrations.js').Dataset|null} */let pendingImport=null;
 /** @type {ResizeObserver|null} */let resize=null;
 let fileVersion=0;
 const session=()=>imitation.sessions[imitation.active];
 function restoreRecorder(){const active=session().dataset.trajectories.find(t=>t.end==='active')??session().dataset.trajectories.at(-1);recorder=active?new DemonstrationRecorder(active.split,active.seed,active.id,active):null;}
 restoreRecorder();
 function save(){store.save('11');}
 /** @param {string} selector */
 function element(selector){const e=root.querySelector(selector);if(!(e instanceof HTMLElement))throw Error('Missing imitation element '+selector);return e;}
 function checks(){return learningRequirements('11',record).map(r=>`<li>${r.done?'✓':'○'} ${h(r.label)}</li>`).join('');}
 function stageView(){const s=session();
  if(record.stage===0)return `<h2 id="imitation-stage-title" tabindex="-1">Observe: learn from demonstrated actions</h2><p>${h(content.observe)}</p><p>The goal gives +1 on entry (−0.05 step cost +1.05 bonus); other actions cost −0.05. Only reaching G terminates. An 80-step external cap is recorded separately. Upper-start trajectories are held out before fitting; the layout and state semantics stay identical.</p><p>${h(content.scope)}</p><form data-imitation-form="observe"><label class="field">${h(content.concept)}${select(content.choices,'answer')}</label><button class="button primary">Check understanding</button></form>`;
  if(record.stage===1)return `<h2 id="imitation-stage-title" tabindex="-1">Predict before recording and fitting</h2><p>${h(content.prediction)}</p>${record.prediction?`<p><strong>Saved prediction:</strong> ${h(record.prediction.answer)}</p>`:`<form data-imitation-form="prediction"><label class="field">Your prediction<textarea name="prediction" maxlength="300" rows="3" required></textarea></label><button class="button primary">Save prediction</button></form>`}<p>Exploring later stages does not grant completion. Predictions and reflections are saved without automatic grading.</p>`;
  if(!record.prediction)return '<h2 id="imitation-stage-title" tabindex="-1">Save a prediction first</h2><p>You can explore ahead; record your prediction before any demonstration or fitting results.</p>';
  if(record.stage===2)return `<h2 id="imitation-stage-title" tabindex="-1">Play: teach Robo with your actions</h2><p>Choose Training / lower start, start a trajectory, then use the focused map’s arrow keys or touch buttons. A short lower route is right, right, up. Next choose Held-out / upper start and demonstrate right, right. These are suggestions for your own manual recordings, not supplied training data. You can demonstrate other routes, including mistakes.</p><p>Every action pairs with its observation before movement. Completing, capping or explicitly stopping a trajectory saves it. An active recording resumes after refresh. Record both splits, then fit the policy; fitting locks that dataset version.</p>`;
  if(record.stage===3)return `<h2 id="imitation-stage-title" tabindex="-1">Reveal the mathematics</h2><p>${h(content.math)}</p><div class="inset"><h3>Worked numerical example</h3><p>${h(content.worked)}</p></div><form data-imitation-form="math">${content.questions.map((q,i)=>`<label class="field">${h(q)}<input name="answer${i}" type="number" step="any" required></label>`).join('')}<button class="button primary">Check both calculations</button></form>`;
  if(record.stage===4)return `<h2 id="imitation-stage-title" tabindex="-1">Experiment: compare the cost and the behavior</h2><p>${h(content.experiment)}</p><p>Calibration is concept-based: finish five paired seed runs per initialization and interpret their measured mean return. There is no return threshold or assumed winning method.</p>${!s.fit?'<p>Record both splits and fit the policy below before starting the comparison.</p>':s.comparison?imitationComparisonView(s.comparison):`<form data-imitation-form="compare"><label class="field">New RL interactions per agent<input type="number" name="budget" min="60" max="1500" step="1" value="600" required></label><label class="field">Comparison prediction<textarea name="prediction" maxlength="300" rows="2" required></textarea></label><button class="button primary" ${busy?'disabled':''}>Save prediction and run comparison</button></form>`}<p>Pause/Resume keeps the current worker budget. Cancel retains finished replicates and marks the comparison incomplete. A new experiment preserves this session; it never silently appends incompatible results.</p><div class="actions">${button('Pause','pause',workerMode!=='training')}${button('Resume','resume',workerMode!=='paused')}${button('Cancel comparison','cancel',!busy||!coordinator)}</div>`;
  return `<h2 id="imitation-stage-title" tabindex="-1">Challenge and reflect</h2>${s.comparison?imitationComparisonView(s.comparison):'<p>Finish a comparison before answering the evidence question.</p>'}<form data-imitation-form="challenge"><label class="field">${h(content.challenge)}<select name="winner" required><option value="">Choose from your measured evidence</option><option value="scratch">Scratch actor-critic</option><option value="initialized">Imitation-initialized actor-critic</option><option value="tie">Tie in this comparison</option></select></label><label class="field">${h(content.challengeConcept)}${select(content.challengeChoices,'concept')}</label><button class="button primary">Submit challenge</button></form><div class="completion-summary"><h3>${learningComplete('11',record)?'Lesson complete':'Evidence still needed'}</h3><ul>${checks()}</ul><p>Completion records activities and explicit checks. Local exports are self-reported learning artifacts, not authenticated grades.</p></div><form data-imitation-form="reflection"><label class="field">${h(content.reflection)}<textarea name="reflection" maxlength="2000" rows="3">${h(record.reflection)}</textarea></label><button class="button secondary">Save reflection</button></form>`;
 }
 function labView(){const s=session(),locked=Boolean(s.fit)||busy,active=recorder?.trajectory.end==='active';return `<section class="card imitation-lab"><p class="eyebrow">Manual demonstrations · experiment ${imitation.active+1} / 3</p><h2>Demonstration laboratory</h2><div class="learning-fields"><label class="field">Trajectory split<select id="demo-split" ${locked||active?'disabled':''}><option value="train">Training / lower start (0,1)</option><option value="holdout">Held-out / upper start (0,0)</option></select></label><div class="actions">${button('Start trajectory','start',locked||active||s.dataset.trajectories.length>=16)}${button('Stop and save partial','stop',locked||!active||!recorder?.trajectory.traces.length)}</div></div><div class="imitation-world"><div><div id="demonstration-board" tabindex="0" role="group" aria-label="Manual demonstration map. Arrow keys move Robo; Tab leaves the map."><canvas id="demonstration-canvas" role="img" aria-label="Robo demonstration island; full text map follows"></canvas></div><div class="actions demo-directions">${ACTIONS.map(a=>button('Move '+a,a,locked||!active)).join('')}</div><p id="demonstration-state" role="status"></p><details><summary>Accessible map and actual transition</summary><div id="demonstration-text"></div></details></div><div class="inset"><h3>Capture protocol</h3><p>Training: lower start (0,1). Held-out: upper start (0,0). Complete position observation, four fixed actions, deterministic movement. Separate trajectory IDs and seeds are saved. A goal ends the episode; a stopped or capped recording is labeled.</p><p>At most 16 trajectories / 1,024 actions per dataset. Fitting seals the dataset. Start a new experiment to collect different demonstrations; up to three versions are retained, including old fitting and evaluation results.</p><div class="actions">${button('Export demonstrations','export')}${button('New experiment','new',busy||imitation.sessions.length>=3)}</div><label class="field">Demonstrations JSON<input type="file" accept=".json,application/json" id="demo-import" ${busy||imitation.sessions.length>=3?'disabled':''}></label><p>Import validates the whole bounded file, replays alignment and asks before adding a new experiment. It never executes content. Export the complete learning backup from Notebook to include fitted policies, RL checkpoints, progress and reflections.</p></div></div><div id="demo-dataset">${datasetView(s.dataset)}</div>${!s.fit?`<form data-imitation-form="fit"><div class="learning-fields"><label class="field">Fitting epochs<input type="number" name="epochs" min="1" max="300" step="1" value="120" required></label><label class="field">Supervised step size<input type="number" name="alpha" min="0.01" max="1" step="any" value="0.5" required></label></div><button class="button primary" ${locked||active||!pairs(s.dataset,'train').length||!pairs(s.dataset,'holdout').length?'disabled':''}>Fit behavior cloning</button></form>`:''}${fitView(s)}</section>`;}
 function draw(){const canvas=root.querySelector('#demonstration-canvas');if(!(canvas instanceof HTMLCanvasElement))return;const scenario=recorder?.environment.getScenario()??demonstrationScenario('train'),state=recorder?.environment.getState()??scenario.start;createIslandRenderer(canvas).draw(scenario,state);element('#demonstration-state').textContent=`Actual state (${state.x},${state.y}). ${recorder?`Trajectory ${recorder.trajectory.id} · ${recorder.trajectory.split} · ${recorder.trajectory.end} · ${recorder.trajectory.traces.length} actions`:'Start a trajectory to record.'}`;const t=recorder?.trajectory.traces.at(-1);element('#demonstration-text').innerHTML=`<ul>${scenario.grid.flatMap((row,y)=>[...row].map((_,x)=>`<li>${h(describeCell(scenario,state,x,y))}</li>`)).join('')}</ul>${t?table(['Pre-action observation','Action','Reward','Next observation','Probability'],[[JSON.stringify(t.observation),t.action,String(t.reward),JSON.stringify(t.nextObservation),String(t.probability)]],'Actual latest transition, P(next state | state, action)'):''}`;}
 function status(){const e=root.querySelector('#imitation-status');if(e)e.textContent=(busy?`Working · worker ${workerMode}. `:'')+feedback;for(const a of ['pause','resume','cancel']){const b=root.querySelector(`[data-imitation-action="${a}"]`);if(b instanceof HTMLButtonElement)b.disabled=a==='pause'?workerMode!=='training':a==='resume'?workerMode!=='paused':!busy||!coordinator;}}
 function render(focus=false){const restore=rememberFocus(root);resize?.disconnect();root.innerHTML=`<nav class="lesson-stage-nav" aria-label="Lesson stages">${stages.map((s,i)=>`<button data-imitation-stage="${i}" class="${record.stage===i?'is-current':''}" aria-current="${record.stage===i?'step':'false'}"><span>${i+1}</span>${s}</button>`).join('')}</nav><div class="guided-layout"><aside class="card lesson-roadmap"><p class="eyebrow">Lesson 11 · six stages</p><h2>Learning evidence</h2><ul>${checks()}</ul><p>${h(store.message)}</p><p>Prerequisite: <a href="#/lesson/10">lesson 10</a>. Exploring ahead is allowed.</p><a href="#/notebook">Notebook and complete backup</a></aside><div class="imitation-main"><section class="card lesson-stage">${stageView()}<p id="imitation-status" role="status" aria-live="polite"></p><div class="stage-navigation">${button('Previous stage','previous',record.stage===0)}${button('Next stage','next',record.stage===5)}</div></section>${record.prediction&&record.stage>=2?labView():''}<p class="source-note">Original island activity based on the catalog-verified lesson 11 deck. Locally inspected PDF topics include demonstration trajectories and behavioral cloning versus RL; detailed activity alignment and instructor approval remain pending.</p></div></div><dialog id="demo-import-dialog" aria-labelledby="demo-import-title"><h2 id="demo-import-title">Add validated demonstrations as a new experiment?</h2><p>Your existing datasets and results will be kept. Imported records are self-reported; a checksum does not authenticate who recorded them.</p><div class="actions">${button('Cancel import','cancelImport')}${button('Add imported experiment','confirmImport')}</div></dialog>`;status();const split=root.querySelector('#demo-split');if(split instanceof HTMLSelectElement&&recorder)split.value=recorder.trajectory.split;draw();const canvas=root.querySelector('#demonstration-canvas');if(canvas){resize=new ResizeObserver(draw);resize.observe(canvas);}if(focus)element('#imitation-stage-title').focus({preventScroll:true});else restore();}
 /** @param {import('../environment/types.js').Action} action */
 function move(action){if(busy||session().fit||!recorder||recorder.trajectory.end!=='active')return;if(session().dataset.trajectories.reduce((n,t)=>n+t.traces.length,0)>=1024)throw Error('Dataset action limit reached; stop this recording and export.');recorder.act(action);const index=session().dataset.trajectories.findIndex(t=>t.id===recorder?.trajectory.id);session().dataset.trajectories[index]=structuredClone(recorder.trajectory);save();const focused=document.activeElement?.id==='demonstration-board';render();if(focused)element('#demonstration-board').focus({preventScroll:true});}
 root.addEventListener('keydown',event=>{if(!(event instanceof KeyboardEvent)||event.target!==root.querySelector('#demonstration-board'))return;const action=/** @type {Record<string,import('../environment/types.js').Action>} */({ArrowUp:'up',ArrowRight:'right',ArrowDown:'down',ArrowLeft:'left'})[event.key];if(action){event.preventDefault();try{move(action);}catch(error){feedback=error instanceof Error?error.message:'Movement failed.';status();}}},{signal:abort.signal});
 root.addEventListener('click',event=>{const target=event.target instanceof Element?event.target.closest('button'):null;if(!(target instanceof HTMLButtonElement))return;void(async()=>{if(target.dataset.imitationStage!==undefined){record.stage=Number(target.dataset.imitationStage);save();render(true);return;}const a=target.dataset.imitationAction;if(!a)return;
 if(a==='next'||a==='previous'){record.stage=Math.max(0,Math.min(5,record.stage+(a==='next'?1:-1)));save();render(true);return;}
 if(ACTIONS.includes(/** @type {import('../environment/types.js').Action} */(a))){move(/** @type {import('../environment/types.js').Action} */(a));return;}
 if(a==='start'){if(busy||session().fit||recorder?.trajectory.end==='active')return;const split=/** @type {'train'|'holdout'} */(/** @type {HTMLSelectElement} */(element('#demo-split')).value),id=nextTrajectoryId(session().dataset);recorder=new DemonstrationRecorder(split,deriveSeed(imitation.active+11,'manual-demonstration/'+id),id);session().dataset.trajectories.push(structuredClone(recorder.trajectory));feedback='Recording '+split+' trajectory. Focus the map for arrow keys.';save();render();element('#demonstration-board').focus();return;}
 if(a==='stop'&&recorder){recorder.stop();session().dataset.trajectories[session().dataset.trajectories.findIndex(t=>t.id===recorder?.trajectory.id)]=structuredClone(recorder.trajectory);save();render();return;}
 if(a==='export'){const url=URL.createObjectURL(new Blob([exportDataset(session().dataset)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='rl-island-demonstrations.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);feedback='Demonstrations exported, including declared splits and actual transitions.';status();return;}
 if(a==='new'){if(busy||imitation.sessions.length>=3)return;imitation.sessions.push(newSession());imitation.active++;recorder=null;feedback='New dataset version. Earlier datasets and measured results remain in Notebook and the learning backup.';save();render();return;}
 if(a==='pause'||a==='resume'){await coordinator?.command(a);return;}
 if(a==='cancel'){cancelled=true;await coordinator?.command('cancel');return;}
 if(a==='cancelImport'){pendingImport=null;fileVersion++;/** @type {HTMLDialogElement} */(element('#demo-import-dialog')).close();return;}
 if(a==='confirmImport'&&pendingImport){if(busy||imitation.sessions.length>=3)throw Error('Experiment limit reached; existing records preserved.');const s=newSession();s.dataset=pendingImport;imitation.sessions.push(s);imitation.active++;pendingImport=null;restoreRecorder();save();feedback='Validated demonstrations added in a separate experiment.';render();}
 })().catch(error=>{feedback=error.message;status();});},{signal:abort.signal});
 root.addEventListener('change',event=>{const input=event.target;if(!(input instanceof HTMLInputElement)||input.id!=='demo-import')return;const file=input.files?.[0],version=++fileVersion;if(!file)return;void(async()=>{if(file.size>MAX_DATASET_BYTES)throw Error('Demonstration file exceeds 1.5 MB.');const text=await file.text();if(disposed||version!==fileVersion)return;if(busy||imitation.sessions.length>=3)throw Error('Experiment limit reached; existing records preserved.');pendingImport=importDataset(text);/** @type {HTMLDialogElement} */(element('#demo-import-dialog')).showModal();})().catch(error=>{pendingImport=null;feedback=error.message;status();});},{signal:abort.signal});
 root.addEventListener('submit',event=>{event.preventDefault();const form=event.target;if(!(form instanceof HTMLFormElement))return;void submit(form).catch(error=>{feedback=error.message;status();});},{signal:abort.signal});
 /** @param {HTMLFormElement} form */
 async function submit(form){const data=new FormData(form),kind=form.dataset.imitationForm,now=new Date().toISOString();
  if(kind==='prediction'){const answer=String(data.get('prediction')??'').trim();if(!answer||answer.length>300)throw Error('Write a short prediction.');record.prediction??={answer,at:now};feedback='Prediction saved before results.';save();render();return;}
  if(kind==='reflection'){record.reflection=String(data.get('reflection')??'').slice(0,2000);record.reflectionAt=now;feedback='Reflection saved without automatic grading.';save();status();return;}
  if(['observe','math','challenge'].includes(kind??'')){if(record.attempts.length>=60)throw Error('Check history limit reached; export this record.');const attempt={stage:/** @type {'observe'|'math'|'challenge'} */(kind),answers:kind==='observe'?[String(data.get('answer'))]:kind==='math'?[String(data.get('answer0')),String(data.get('answer1'))]:[String(data.get('winner')),String(data.get('concept'))],comparisonId:session().comparison?hashData(session().comparison):null,at:now};record.attempts.push(attempt);feedback=learningCheck('11',record,attempt)?'Correct. The explicit check is recorded.':'Not yet. Review the example and measured comparison. This attempt is retained.';save();render();return;}
  if(busy)throw Error('Finish or cancel the active experiment first.');if(!record.prediction)throw Error('Save a prediction first.');const s=session();
  if(kind==='fit'){if(s.fit)throw Error('This dataset is already fitted; start a new experiment.');const fit=new BehaviorCloner(s.dataset,Number(data.get('epochs')),Number(data.get('alpha')));busy=true;cancelled=false;feedback='Fitting training labels only…';render();try{while(!fit.done){for(let i=0;i<8&&!fit.done;i++)fit.step();await new Promise(resolve=>setTimeout(resolve,0));if(disposed)return;}s.fit=fit.result();feedback='Supervised fit complete. Held-out metrics were measured separately; inspect unseen states.';save();}finally{busy=false;if(!disposed)render();}return;}
  if(kind==='compare'){if(!s.fit||s.comparison)throw Error('Use a fitted dataset with no previous comparison, or start a new experiment.');const comparison=newImitationComparison(s.dataset,s.fit,Number(data.get('budget')),String(data.get('prediction')??'').trim());s.comparison=comparison;busy=true;cancelled=false;save();try{coordinator=new TrainingCoordinator(message=>{workerMode=message.mode;if(message.snapshot)feedback=`${comparison.runs.length}/10 replicates retained; active agent ${message.snapshot.checkpoint.interactions}/${comparison.budget} RL interactions.`;status();});render();await runImitationComparison(coordinator,comparison,s.dataset,s.fit,()=>cancelled||disposed,()=>{save();if(!disposed)render();});feedback='Comparison complete. Read the measured outcome; no winner was prescribed.';}finally{coordinator?.dispose();coordinator=null;if(comparison.status==='pending')comparison.status='cancelled';workerMode='idle';busy=false;save();if(!disposed)render();}}
 }
 render();save();return ()=>{disposed=true;cancelled=true;fileVersion++;resize?.disconnect();coordinator?.dispose();abort.abort();const c=session().comparison;if(c?.status==='pending')c.status='cancelled';save();};
}
