import {emptyDataset,validateDataset} from './demonstrations.js';
import {BehaviorCloner,initializePolicy} from './cloning.js';
import {imitationWinner,newImitationComparison,evaluateImitation} from './experiment.js';
import {exactRecord} from '../training/validation.js';
import {validateRunCheckpoint} from '../training/run.js';
import {hashData,defaultConfig} from '../training/config.js';
/** @typedef {{dataset:import('./demonstrations.js').Dataset,fit:ReturnType<BehaviorCloner['result']>|null,comparison:import('./experiment.js').ImitationComparison|null}} Session */
/** @typedef {{active:number,sessions:Session[]}} ImitationRecord */
/** @returns {Session} */
export const newSession=()=>({dataset:emptyDataset(),fit:null,comparison:null});
/** @returns {ImitationRecord} */
export const emptyImitation=()=>({active:0,sessions:[newSession()]});
/** @param {import('../lessons/learning-records.js').LearningRecord} record */
export function imitationRequirements(record){const sessions=record.imitation?.sessions??[];return [{label:'Observe concept check',done:record.attempts.some(a=>a.stage==='observe'&&a.answers[0]==='Demonstrated actions')},{label:'Prediction saved before results',done:Boolean(record.prediction)},{label:'Training and held-out demonstrations fitted',done:sessions.some(s=>Boolean(s.fit))},{label:'Two numerical cloning checks',done:record.attempts.some(a=>a.stage==='math'&&a.answers.length===2&&Math.abs(Number(a.answers[0])-.375)<.001&&Math.abs(Number(a.answers[1])+.125)<.001)},{label:'Five agents per RL initialization at equal real budgets',done:sessions.some(s=>s.comparison?.status==='complete'&&s.comparison.runs.length===10)},{label:'Measured comparison and generalization check',done:record.attempts.some(a=>a.stage==='challenge'&&imitationCheck(record,a))}];}
/** @param {import('../lessons/learning-records.js').LearningRecord} record @param {import('../lessons/learning-records.js').LearningAttempt} attempt */
export function imitationCheck(record,attempt){if(attempt.stage==='observe')return attempt.answers[0]==='Demonstrated actions';if(attempt.stage==='math')return attempt.answers.length===2&&attempt.answers.every(a=>a.trim())&&Math.abs(Number(attempt.answers[0])-.375)<.001&&Math.abs(Number(attempt.answers[1])+.125)<.001;const c=record.imitation?.sessions.find(s=>s.comparison&&hashData(s.comparison)===attempt.comparisonId)?.comparison;return Boolean(c?.status==='complete'&&attempt.answers[0]===imitationWinner(c)&&attempt.answers[1]==='Unseen states receive no supervised gradient');}
/** Numeric tolerance permits ordinary JS exp roundoff across browsers. @param {unknown} a @param {unknown} b @returns {boolean} */
function equal(a,b){if(Array.isArray(a)!==Array.isArray(b))return false;if(typeof a==='number'&&typeof b==='number')return Number.isFinite(a)&&Math.abs(a-b)<=1e-10*Math.max(1,Math.abs(b));if(a===null||b===null||typeof a!=='object'||typeof b!=='object')return a===b;const aa=Object.entries(a),bb=Object.entries(b);return aa.length===bb.length&&aa.every(([k,v])=>Object.hasOwn(b,k)&&equal(v,/** @type {Record<string,unknown>} */(b)[k]));}
/** Strict bounded imports; independently recompute fitting and frozen evaluation, then check RL checkpoints.
 * @param {unknown} value @returns {asserts value is ImitationRecord} */
export function validateImitation(value){const r=exactRecord(value,['active','sessions']);if(!Array.isArray(r.sessions)||r.sessions.length<1||r.sessions.length>3||r.active!==r.sessions.length-1)throw Error('Invalid imitation sessions.');for(const raw of r.sessions){const s=exactRecord(raw,['dataset','fit','comparison']),dataset=validateDataset(s.dataset);for(const field of ['fit','comparison'])if(s[field]!==null&&(!s[field]||typeof s[field]!=='object'||Array.isArray(s[field])))throw Error('Invalid imitation result field.');if(s.fit){const f=exactRecord(s.fit,['version','representation','datasetHash','epochs','alpha','examplePasses','actor','history','last']);const fitter=new BehaviorCloner(dataset,Number(f.epochs),Number(f.alpha));while(!fitter.done)fitter.step();const fit=fitter.result();if(!equal(f,fit))throw Error('Supervised fit differs from the recorded training data.');if(s.comparison){const c=/** @type {import('./experiment.js').ImitationComparison} */(exactRecord(s.comparison,['version','status','prediction','budget','seeds','evaluationSeeds','fitHash','datasetHash','demonstrationActions','supervisedPasses','baseline','runs']));const expected=newImitationComparison(dataset,/** @type {ReturnType<BehaviorCloner['result']>} */(f),c.budget,c.prediction);if(!['pending','complete','cancelled'].includes(c.status)||!Array.isArray(c.runs)||c.runs.length>10||c.status==='complete'&&c.runs.length!==10)throw Error('Invalid comparison status.');if(!equal({...c,status:'pending',runs:[]},expected))throw Error('Comparison provenance mismatch.');const keys=new Set();for(const run of c.runs){exactRecord(run,['variant','seed','initialParameterHash','checkpoint','familiar','novel']);if(!['scratch','initialized'].includes(run.variant)||!c.seeds.includes(run.seed)||keys.has(run.variant+run.seed))throw Error('Invalid comparison replicate.');keys.add(run.variant+run.seed);validateRunCheckpoint(run.checkpoint);const initial=initializePolicy(run.variant==='initialized'?/** @type {ReturnType<BehaviorCloner['result']>} */(f):null,{...defaultConfig('11'),seed:run.seed});if(hashData(initial.config)!==hashData(run.checkpoint.config)||run.initialParameterHash!==hashData(initial.parameters)||run.checkpoint.interactions!==c.budget)throw Error('Unequal RL budget or incompatible initialization.');for(const split of /** @type {const} */(['train','holdout']))if(!equal(run[split==='train'?'familiar':'novel'],evaluateImitation(run.checkpoint.parameters,dataset,split,c.evaluationSeeds)))throw Error('Frozen evaluation mismatch.');}}
 }else if(s.comparison)throw Error('Comparison requires a fitted policy.');}}
