import {escapeHtml as h} from '../ui/escape.js';
import {softmax} from '../agents/policy.js';
import {pairs} from './demonstrations.js';
import {imitationSummary} from './experiment.js';
import {stateKey} from '../environment/schema.js';
/** @param {number|null|undefined} n */
const f=n=>n===null||n===undefined?'—':Number(n.toFixed(4)).toString();
/** @param {string[]} headings @param {string[][]} rows @param {string} caption */
export const table=(headings,rows,caption)=>`<p class="small imitation-scroll-hint">Wide tables scroll horizontally. Focus the table region and use arrow keys.</p><div class="table-scroll" tabindex="0" role="region" aria-label="${h(caption)}"><table class="imitation-table"><caption>${h(caption)}</caption><thead><tr>${headings.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>`<${i?'td':'th'}>${h(x)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;
/** @param {import('./demonstrations.js').Dataset} dataset */
export function datasetView(dataset){return `<h3>Recorded trajectories</h3><p>${pairs(dataset,'train').length} training pairs · ${pairs(dataset,'holdout').length} held-out pairs. The split is chosen before recording and locked in each trajectory. A held-out trajectory never supplies fitting gradients. Actions are labels; successor states and rewards are inspection data.</p>${dataset.trajectories.map(t=>`<details ${t.end==='active'?'open':''}><summary>Trajectory ${t.id} · ${t.split} · seed ${t.seed} · ${t.traces.length} actions · ${t.end}</summary>${table(['Step','Pre-action state / observation','Demonstrated action','Reward','Next state','Terminal / cutoff'],t.traces.map((s,i)=>[String(i),JSON.stringify(s.observation),s.action,f(s.reward),JSON.stringify(s.nextObservation),`${s.terminated} / ${s.truncated}`]),'Aligned manual transitions; the action belongs to the pre-action observation')}</details>`).join('')||'<p>No demonstrations recorded yet.</p>'}`;}
/** @param {import('./records.js').Session} s */
export function fitView(s){const fit=s.fit;if(!fit)return '<p>No supervised fit yet.</p>';const known=new Set(pairs(s.dataset,'train').map(x=>x.state));const states=['0,0','1,0','0,1','1,1','2,1'];return `<h3>Supervised fitting · separate from task return</h3><p>Cross-entropy, full-batch gradient descent, ${fit.epochs} epochs, α ${fit.alpha}; ${fit.examplePasses} training-example passes. Deterministic zero preferences at initialization, action order up/right/down/left. Accuracy uses argmax with that tie order. No reward or held-out gradient is used; epochs are fixed before fitting, without held-out early stopping.</p>${table(['Epoch','Train N / loss / accuracy','Held-out N / loss / accuracy'],fit.history.map(r=>[String(r.epoch),`${r.train.count} / ${f(r.train.loss)} / ${f(r.train.accuracy)}`,`${r.holdout.count} / ${f(r.holdout.loss)} / ${f(r.holdout.accuracy)}`]),'Actual unsmoothed supervised measurements; accuracy is a fraction, not success rate')}<h3>Policy coverage and missing states</h3>${table(['State','Demonstrated training state?','Preferences (up/right/down/left)','Action probabilities'],states.map(state=>[state,known.has(state)?'Yes':'No — no supervised gradient',(fit.actor[state]??[0,0,0,0]).map(f).join(', '),softmax(fit.actor[state]??[0,0,0,0]).map(f).join(', ')]),'Cloned softmax policy including every nonterminal state')}<p>Unseen tabular states retain uniform probabilities. Small action mistakes can move Robo away from familiar paths, so fitting the labels alone does not guarantee task success.</p>${fit.last?`<details><summary>Actual last full-batch update</summary><p>State ${h(fit.last.state)}: preferences [${fit.last.before.map(f).join(', ')}] + ${fit.alpha} × mean score gradient [${fit.last.gradient.map(f).join(', ')}] = [${fit.last.after.map(f).join(', ')}]. Gradient contributions were averaged over ${fit.last.normalizer} training pairs. Pre-update probabilities: [${fit.last.probabilities.map(f).join(', ')}].</p></details>`:''}`;}
/** @param {import('./experiment.js').Evaluation} result */
function evaluationView(result){return `${table(['Seed','Return','Discounted return','Length','Goal success','External cutoff','Unseen-state visits'],result.rows.map(r=>[String(r.seed),f(r.return),f(r.discountedReturn),String(r.length),String(r.success),String(r.truncated),String(r.unseenVisits)]),'Frozen '+(result.split==='train'?'familiar lower':'held-out upper')+' start; raw evaluation episodes')}<details><summary>First evaluation trajectory · actual sampled decisions</summary>${table(['State','Missing from demonstrations?','Probabilities up/right/down/left','Draw → action','Reward → next state'],result.trace.map(t=>[t.decision.state,String(t.unseen),t.decision.probabilities.map(f).join(', '),`${f(t.decision.actionDraw)} → ${['up','right','down','left'][t.decision.action]}`,`${f(t.transition?.reward)} → ${t.transition?stateKey(t.transition.nextState):''}`]),'Recorded evaluation behavior; sampling the frozen policy, never fitting held-out labels')}</details>`;}
/** @param {import('./experiment.js').ImitationComparison} c */
export function imitationComparisonView(c){return `<section class="imitation-comparison"><h3>Scratch vs imitation-initialized actor-critic</h3><p><strong>${h(c.status)}</strong> · ${c.runs.length}/10 RL agents · ${c.budget} new real interactions per agent; exactly ${c.budget} actor and critic updates. Training seeds ${c.seeds.join(', ')}; separate evaluation seeds ${c.evaluationSeeds.join(', ')}. All runs use configuration v1: α 0.1, γ 0.9, cap 80, actor-critic policy-v1. Partial last episodes are retained, not counted as terminal.</p><p>Additional imitation cost: ${c.demonstrationActions} training-demonstration actions and ${c.supervisedPasses} supervised-example passes, shared cloned initializer. Scratch uses neither. Equal RL interactions do not mean equal total data or computation. Five independently sampled RL agents per initialization share this one dataset; they are not five independently collected datasets.</p><p>Saved prediction: ${h(c.prediction)}</p><p>${h(c.baseline.novel.rule)}. Evaluation performs zero updates; raw results are separate from fitting and training. No smoothing or required winning method.</p>${table(['Initialization','Independent RL agents','Familiar mean return','Upper-start mean return','Upper-start success fraction'],imitationSummary(c).map(r=>[r.variant,String(r.agents),f(r.familiar),f(r.novel),f(r.success)]),'Measured means over agents; each agent has five evaluation episodes')}<details><summary>Frozen cloned policy before any RL · one fitted policy</summary>${evaluationView(c.baseline.familiar)}${evaluationView(c.baseline.novel)}</details>${c.runs.map(r=>`<details><summary>${r.variant} · seed ${r.seed} · ${r.checkpoint.interactions} real interactions / ${r.checkpoint.parameters.updates} updates</summary><p>Initial parameter digest ${h(r.initialParameterHash)}. Final parameters and every completed/capped training episode are included in the learning backup. ${r.checkpoint.samples.length} transitions in the current rollout; ${r.checkpoint.rows.length} stored episode rows.</p>${table(['Training episode','Reward sum','Discounted return','Length','Terminal / cutoff'],r.checkpoint.rows.map(t=>[String(t.episode),f(t.return),f(t.discountedReturn),String(t.length),`${t.terminated} / ${t.truncated}`]),'Genuine training episodes; no smoothing')}${evaluationView(r.familiar)}${evaluationView(r.novel)}</details>`).join('')}</section>`;}
/** @param {import('./records.js').Session} s */
export function imitationSessionView(s){return datasetView(s.dataset)+fitView(s)+(s.comparison?imitationComparisonView(s.comparison):'');}
