/** @typedef {{status:string,version?:string,total?:number,bytes?:number,error?:string}} CacheStatus */
/** @param {ServiceWorker} worker @returns {Promise<CacheStatus>} */
function ask(worker){return new Promise((resolve,reject)=>{const channel=new MessageChannel(),timer=setTimeout(()=>{channel.port1.close();reject(Error('Offline worker did not respond.'));},15000);channel.port1.onmessage=e=>{clearTimeout(timer);channel.port1.close();resolve(e.data);};worker.postMessage({type:'STATUS'},[channel.port2]);});}
/** @param {HTMLElement} root @param {()=>boolean} busy */
export function mountOffline(root,busy){root.innerHTML='<details><summary>Offline course & updates</summary><p id="offline-status" role="status">Checking offline support…</p><p class="small">Includes local lessons, fonts, maps and lazy neural assets. External lecture PDFs and ACML links require a connection; they are not cached. Browser caches can be evicted. Saved learning data is separate.</p><div class="actions"><button class="button secondary" id="offline-retry">Prepare offline course / check updates</button><button class="button secondary" id="offline-update" hidden>Review update</button></div></details><dialog id="offline-dialog" aria-labelledby="offline-title"><h2 id="offline-title">Apply the cached course update?</h2><p>Save or export typed notes first. This reload ends the current view; stored learning records are preserved. Other open tabs are not automatically reloaded.</p><p id="offline-update-status" role="status"></p><button class="button secondary" id="offline-keep">Keep current page</button><button class="button primary" id="offline-apply">Apply update and reload</button></dialog>';
 const status=/** @type {HTMLElement} */(root.querySelector('#offline-status')),update=/** @type {HTMLButtonElement} */(root.querySelector('#offline-update')),dialog=/** @type {HTMLDialogElement} */(root.querySelector('#offline-dialog')),apply=/** @type {HTMLButtonElement} */(root.querySelector('#offline-apply'));let registration=/** @type {ServiceWorkerRegistration|null} */(null),reload=false,working=false;
 const say=(/** @type {string} */s)=>{status.textContent=s;const label=root.querySelector('summary');if(label)label.textContent=s.startsWith('Complete course offline-ready')?'Offline course · ready':s.includes('update is cached')?'Offline course · update available':/failed|unavailable|incomplete/i.test(s)?'Offline course · not ready':'Offline course · preparing';};
 /** @param {boolean} [repair] */
 async function inspect(repair=false){if(!registration)return;const worker=registration.waiting??registration.active;if(!worker)return;const result=await ask(worker);if(worker!==(registration.waiting??registration.active)){await inspect(repair);return;}if(result.status!=='ready'){if(repair){say('Rebuilding incomplete course cache…');worker.postMessage({type:'REPAIR',version:result.version});return;}say('Offline cache is incomplete or unavailable. Reconnect and retry; complete-course offline readiness is not established.');return;}if(registration.waiting===worker){update.hidden=false;say('A complete course update is cached and waiting. Your current page and training are unchanged.');}else {update.hidden=true;say(`Complete course offline-ready: ${result.total} verified local assets (${((result.bytes??0)/1048576).toFixed(2)} MiB), build ${result.version}. External PDFs are not included.`);const pageVersion=document.querySelector('meta[name="rl-build"]')?.getAttribute('content');if(pageVersion===result.version)worker.postMessage({type:'PRUNE',version:pageVersion});}}
 async function prepare(){if(working)return;working=true;try{if(!('serviceWorker' in navigator)||!window.isSecureContext)throw Error('Service workers require a supported browser and HTTPS or localhost.');if(import.meta.env.DEV){say('Offline caching is available in the production build, served under /rl-island/.');return;}say('Preparing the complete local course cache…');registration=await navigator.serviceWorker.register('/rl-island/sw.js',{scope:'/rl-island/',updateViaCache:'none'});if(new URL(registration.scope).pathname!=='/rl-island/')throw Error('Unexpected worker scope.');registration.onupdatefound=()=>{const worker=registration?.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed')void inspect().catch(e=>say(e.message));if(worker.state==='redundant')say('Offline cache installation failed. The current app and saved work remain available; reconnect and retry.');});};if(registration.active||registration.waiting)await inspect(true);await registration.update();}catch(error){say('Offline cache unavailable: '+(error instanceof Error?error.message:'browser storage error')+' Current learning still works while its assets are available.');}finally{working=false;}}
 if('serviceWorker' in navigator){navigator.serviceWorker.addEventListener('message',event=>{const m=event.data;if(m?.source!=='rl-island-offline')return;if(m.status==='caching')say(`Caching full course: ${m.done} / ${m.total} assets. Not offline-ready yet.`);if(m.status==='failed')say('Offline caching failed: '+m.error+'. Reconnect and retry; saved learning data is unchanged.');if(m.status==='cached')void inspect().catch(e=>say(e.message));});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reload)location.reload();else void inspect().catch(e=>say(e.message));});}
 root.querySelector('#offline-retry')?.addEventListener('click',()=>void prepare());update.addEventListener('click',()=>{dialog.showModal();apply.disabled=busy();/** @type {HTMLElement} */(root.querySelector('#offline-update-status')).textContent=busy()?'Finish or cancel the running/paused job before updating.':'No active worker job. Save any typed notes before continuing.';});root.querySelector('#offline-keep')?.addEventListener('click',()=>dialog.close());apply.addEventListener('click',()=>{void(async()=>{if(busy()){apply.disabled=true;return;}const worker=registration?.waiting;if(!worker)return;apply.disabled=true;const result=await ask(worker);if(result.status!=='ready'||registration?.waiting!==worker)throw Error('Update changed or its cache is incomplete. Close and review the update again.');if(busy())throw Error('Finish or cancel the active job first.');reload=true;worker.postMessage({type:'ACTIVATE',version:result.version});})().catch(error=>{reload=false;apply.disabled=false;const text=root.querySelector('#offline-update-status');if(text)text.textContent=error.message;});});
 const start=()=>void prepare();if(document.readyState==='complete')start();else window.addEventListener('load',start,{once:true});window.addEventListener('online',()=>{if(registration)void inspect().catch(e=>say(e.message));});
 return {refresh:()=>inspect().catch(e=>say(e.message))};
}
