import {validateImitation} from '../imitation/records.js';
import {validateComparison} from '../evaluation/comparison-validation.js';
import { record } from '../environment/schema.js';
import { parseBoundedJson } from './bounded-json.js';
import { hashData } from '../training/config.js';
import { validateRunCheckpoint } from '../training/run.js';
import { exactRecord,validateEvaluation } from '../training/validation.js';
import { emptyLearningRecord, learningComplete } from '../lessons/learning-records.js';
/** @typedef {import('../content/model-free.js').LearningId} LearningId */
/** @typedef {{schemaVersion:1,lastLesson:LearningId|null,lessons:Partial<Record<LearningId,import('../lessons/learning-records.js').LearningRecord>>}} LearningProgress */
const KEY='rl-island:model-free-progress:v1';
export const MAX_LEARNING_EXPORT_BYTES=16777216;
/** @returns {LearningProgress} */
const empty=()=>({schemaVersion:1,lastLesson:null,lessons:{}});
/** @param {unknown} value @param {number} [depth] */
function finiteData(value,depth=0){if(depth>30)throw Error('Record nesting limit exceeded.');if(typeof value==='number'&&!Number.isFinite(value))throw Error('Nonfinite record.');if(value&&typeof value==='object')for(const [key,v]of Object.entries(value)){if(['__proto__','constructor','prototype'].includes(key))throw Error('Unsupported record key.');finiteData(v,depth+1);}}
/** @param {unknown} value @param {number} max */
function boundedText(value,max){if(typeof value!=='string'||value.length>max)throw Error('Invalid or oversized text.');return value;}
/** @param {unknown} value @returns {LearningProgress} */
export function validateLearningProgress(value){
 const p=record(value,['schemaVersion','lastLesson','lessons']);if(p.schemaVersion!==1||!['04','05','06','07','08','09','10','11',null].includes(/** @type {LearningId|null} */(p.lastLesson)))throw Error('Unsupported learning progress.');
 const lessons=record(p.lessons,['04','05','06','07','08','09','10','11']);finiteData(p);
 const runIds=Object.values(lessons).flatMap(r=>r&&typeof r==='object'&&'runIds' in r&&Array.isArray(r.runIds)?r.runIds:[]);if(new Set(runIds).size!==runIds.length)throw Error('Duplicate run IDs across lessons.');
 if(JSON.stringify(p).length>12582912)throw Error('Learning progress exceeds its history limit.');
 for(const [id,entry]of Object.entries(lessons)){
  const r=exactRecord(entry,['stage','prediction','attempts','play','comparisons','evaluations','reflection','reflectionAt','activeRunId','runIds','configVersion','completedAt',...(id==='11'&&entry&&typeof entry==='object'&&'imitation' in entry?['imitation']:[])]);
  if(r.imitation){if(id!=='11')throw Error('Imitation record on another lesson.');validateImitation(r.imitation);if(!r.prediction&&r.imitation.sessions.some(s=>s.fit||s.dataset.trajectories.length))throw Error('Demonstrations require a saved prediction.');}
  if(id==='11'&&([r.comparisons,r.runIds,r.evaluations].some(x=>Array.isArray(x)&&x.length)||r.play))throw Error('Unexpected general learning evidence on imitation lesson.');
  if(!Number.isInteger(r.stage)||Number(r.stage)<0||Number(r.stage)>5||!Number.isInteger(r.configVersion)||Number(r.configVersion)<0)throw Error('Invalid lesson stage/version.');
  if(r.prediction){const prediction=record(r.prediction,['answer','at']);if(!boundedText(prediction.answer,300).trim())throw Error('Empty prediction.');boundedText(prediction.at,30);}
  if(!Array.isArray(r.attempts)||r.attempts.length>60||!Array.isArray(r.comparisons)||r.comparisons.length>3||!Array.isArray(r.runIds)||r.runIds.length>4||new Set(r.runIds).size!==r.runIds.length)throw Error('Learning history limit exceeded.');
  r.runIds.forEach(v=>boundedText(v,100));if(r.activeRunId!==null&&!r.runIds.includes(r.activeRunId))throw Error('Missing active run.');
  boundedText(r.reflection,2000);for(const key of ['reflectionAt','completedAt'])if(r[key]!==null)boundedText(r[key],30);
  if(r.prediction!==null&&!r.prediction)throw Error('Invalid prediction.');
  if(!Array.isArray(r.evaluations)||r.evaluations.length>10)throw Error('Evaluation history limit exceeded.');
  for(const raw of r.evaluations){const e=exactRecord(raw,['runId','result']);if(!r.runIds.includes(e.runId))throw Error('Unknown evaluation experiment.');validateEvaluation(e.result);}
  for(const attempt of r.attempts){const a=record(attempt,['stage','answers','comparisonId','at']);if(!['observe','math','challenge'].includes(String(a.stage))||!Array.isArray(a.answers)||a.answers.length>2)throw Error('Invalid check attempt.');a.answers.forEach(v=>boundedText(v,300));boundedText(a.at,30);}
  for(const raw of r.comparisons)validateComparison(raw,id);
  if(r.play){const play=exactRecord(r.play,['interactions','updates','episodes','configHash']);for(const k of ['interactions','updates','episodes'])if(!Number.isInteger(play[k])||Number(play[k])<0)throw Error('Invalid learning evidence.');boundedText(play.configHash,30);}
  if(!r.prediction&&(r.play||r.comparisons.length))throw Error('Learning evidence requires a saved prediction.');
  if(Boolean(r.completedAt)!==learningComplete(/** @type {LearningId} */(id),/** @type {import('../lessons/learning-records.js').LearningRecord} */(r)))throw Error('Completion differs from activity evidence.');
 }
 return structuredClone(/** @type {LearningProgress} */(p));
}
/** IDB holds checkpoints; small lesson evidence has its own key, preserving task-03 records. */
export class LearningStore {
 /** @param {Pick<Storage,'getItem'|'setItem'>} storage @param {{memoryOnly?:boolean}} [options] */
 constructor(storage,{memoryOnly=false}={}){this.memoryOnly=memoryOnly;this.storage=storage;this.data=empty();this.message='Learning records stay on this device; export a backup.';this.blocked=false;this.large=false;this.ready=Promise.resolve();this.persistQueue=Promise.resolve();
/** @type {Set<(message:string)=>void>} */this.listeners=new Set();
  /** @type {Map<string,import('../training/run.js').RunCheckpoint>} */this.memory=new Map();
  /** @type {Promise<IDBDatabase>|null} */this.database=null;
  try{const saved=storage.getItem(KEY);if(saved){const value=parseBoundedJson(saved,12582912);if(value?.schemaVersion===2){const marker=exactRecord(value,['schemaVersion','storage','recordKey']);if(marker.storage!=='indexeddb'||marker.recordKey!=='lesson-progress')throw Error('Unsupported progress pointer.');this.large=true;this.ready=this.hydrate();}else this.data=validateLearningProgress(value);}for(const lesson of Object.values(this.data.lessons)){for(const comparison of lesson.comparisons)if(comparison.status==='pending')comparison.status='cancelled';for(const session of lesson.imitation?.sessions??[])if(session.comparison?.status==='pending')session.comparison.status='cancelled';}}catch{this.blocked=true;this.message='Learning progress could not be read. Existing data is preserved; new work stays in memory.';}
 }
 /** @param {LearningId} id */lesson(id){return this.data.lessons[id]??=emptyLearningRecord();}
 /** @param {LearningId} id */save(id){const r=this.lesson(id);if(learningComplete(id,r)&&!r.completedAt)r.completedAt=new Date().toISOString();this.data.lastLesson=id;const text=JSON.stringify(this.data);if(this.memoryOnly){this.message='Temporary lecture records in memory; personal saves are unchanged.';this.notify();return Promise.resolve();}if(this.large||text.length>65536){this.large=true;const snapshot=structuredClone(this.data);this.message='Saving larger lesson records to IndexedDB…';this.notify();this.persistQueue=this.persistQueue.then(async()=>{try{if(this.blocked)throw Error('Existing records are protected.');const db=await this.db();await new Promise((resolve,reject)=>{const tx=db.transaction('progress','readwrite');tx.objectStore('progress').put(snapshot,'lesson-progress');tx.oncomplete=()=>resolve(undefined);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??Error('Transaction aborted.'));});this.storage.setItem(KEY,JSON.stringify({schemaVersion:2,storage:'indexeddb',recordKey:'lesson-progress'}));this.message='Lesson records saved to IndexedDB. Export a backup.';}catch{this.message='Large lesson records could not be saved. Current data stays in memory; export before closing. Earlier saved data is preserved.';}this.notify();});return this.persistQueue;}try{if(this.blocked)throw Error('Blocked');this.storage.setItem(KEY,text);}catch{this.message='Could not save learning progress. Keep this tab open and export your memory-only records.';}this.notify();return Promise.resolve();}
 notify(){for(const listener of this.listeners)listener(this.message);}
 async hydrate(){try{const db=await this.db();const value=await new Promise((resolve,reject)=>{const request=db.transaction('progress').objectStore('progress').get('lesson-progress');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});this.data=validateLearningProgress(value);for(const lesson of Object.values(this.data.lessons)){for(const c of lesson.comparisons)if(c.status==='pending')c.status='cancelled';for(const s of lesson.imitation?.sessions??[])if(s.comparison?.status==='pending')s.comparison.status='cancelled';}this.message='Larger lesson records restored from IndexedDB.';}catch{this.blocked=true;this.message='Saved lesson records could not be loaded from IndexedDB. Existing storage is protected; current work is memory-only. Import a backup or restore database access.';}this.notify();}

 db(){return this.database??=new Promise((resolve,reject)=>{try{const request=indexedDB.open('rl-island-learning-v1',2);request.onupgradeneeded=()=>{for(const name of ['checkpoints','progress'])if(!request.result.objectStoreNames.contains(name))request.result.createObjectStore(name);};request.onsuccess=()=>{request.result.onversionchange=()=>request.result.close();resolve(request.result);};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('Learning database upgrade blocked.'));}catch(e){reject(e);}});}
 /** @param {string} id @param {import('../training/run.js').RunCheckpoint} checkpoint */
 async putRun(id,checkpoint){this.memory.set(id,structuredClone(checkpoint));if(this.memoryOnly){this.message='Temporary lecture model in memory.';this.notify();return;}try{const db=await this.db();await new Promise((resolve,reject)=>{const transaction=db.transaction('checkpoints','readwrite');transaction.objectStore('checkpoints').put(checkpoint,id);transaction.oncomplete=()=>resolve(undefined);transaction.onerror=()=>reject(transaction.error);});}catch{this.message='Learning checkpoint storage is unavailable. Current model stays in memory; export before closing.';}this.notify();}
 /** @param {string} id */async getRun(id){if(this.memory.has(id))return this.memory.get(id);if(this.memoryOnly)return undefined;try{const db=await this.db();const value=await new Promise((resolve,reject)=>{const req=db.transaction('checkpoints').objectStore('checkpoints').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(value){validateRunCheckpoint(value);this.memory.set(id,value);return value;}}catch{this.message='Saved model unavailable; recorded activities remain. Create a new experiment to train.';}return undefined;}
 async export(){const runs={},missing=[];for(const r of Object.values(this.data.lessons))for(const id of r.runIds){const checkpoint=await this.getRun(id);if(checkpoint)Object.assign(runs,{[id]:checkpoint});else missing.push(id);}if(missing.length){this.message='Incomplete agent backup: '+missing.length+' saved model(s) unavailable. Activity records are retained; unavailable agents are omitted. Missing IDs: '+missing.join(', ');this.notify();}return JSON.stringify({format:'rl-island-learning',schemaVersion:1,kind:'self-reported-learning-artifact',createdAt:new Date().toISOString(),progress:this.data,runs,digest:hashData({progress:this.data,runs})});}
 /** @param {string} text */parseImport(text){if(new TextEncoder().encode(text).length>MAX_LEARNING_EXPORT_BYTES)throw Error('Learning backup exceeds 16 MiB.');const v=record(parseBoundedJson(text,MAX_LEARNING_EXPORT_BYTES),['format','schemaVersion','kind','createdAt','progress','runs','digest']);if(v.format!=='rl-island-learning'||v.schemaVersion!==1||v.kind!=='self-reported-learning-artifact')throw Error('Unsupported learning backup.');if(v.digest!==hashData({progress:v.progress,runs:v.runs}))throw Error('Learning backup checksum mismatch.');const progress=validateLearningProgress(v.progress),keys=Object.values(progress.lessons).flatMap(r=>r.runIds),runs=record(v.runs,keys);for(const [id,c] of Object.entries(runs)){validateRunCheckpoint(c);const lesson=Object.entries(progress.lessons).find(([,r])=>r.runIds.includes(id))?.[0];if(c.config.lesson!==lesson)throw Error('Checkpoint assigned to the wrong lesson.');}return {progress,runs:/** @type {Record<string,import('../training/run.js').RunCheckpoint>} */(runs)};}
 /** @param {ReturnType<LearningStore['parseImport']>} value */async replace(value){const merged=validateLearningProgress({...value.progress,lessons:{...this.data.lessons,...value.progress.lessons}});for(const [id,checkpoint]of Object.entries(value.runs))await this.putRun(id,checkpoint);this.data=merged;this.blocked=false;for(const id of Object.keys(this.data.lessons))await this.save(/** @type {LearningId} */(id));}
}
