import {laboratoryConfig,validateLaboratoryConfig} from '../laboratory/config.js';
export const LECTURE_KEY='rl-island:presentation:v1';
/** @param {Pick<Storage,'getItem'>} storage */
export function readLecture(storage){try{const text=storage.getItem(LECTURE_KEY);if(!text||text.length>128)return false;const v=JSON.parse(text);return v?.schemaVersion===1&&v.lecture===true&&Object.keys(v).length===2;}catch{return false;}}
/** @param {Pick<Storage,'setItem'>} storage @param {boolean} lecture */
export function saveLecture(storage,lecture){try{storage.setItem(LECTURE_KEY,JSON.stringify({schemaVersion:1,lecture}));return '';}catch{return 'Presentation preference could not be saved; this session still works.';}}
export function memoryStorage(){const data=new Map();return {getItem:(/** @type {string} */key)=>data.get(key)??null,setItem:(/** @type {string} */key,/** @type {string} */value)=>{data.set(key,value);}};}
export const PRESETS=[['deterministic','Deterministic navigation · Q-learning'],['slippery','Slippery navigation · SARSA'],['planning','Real versus simulated updates · Dyna-Q'],['features','Map-aware features · linear SARSA']];
/** Presets are configurations, never recorded successful runs. @param {string} id @param {number} seed */
export function lecturePreset(id,seed=11){if(!PRESETS.some(p=>p[0]===id))throw Error('Unknown teaching preset.');const c=laboratoryConfig(id==='slippery'?'sarsa':id==='planning'?'dyna':id==='features'?'linear-sarsa':'q');c.seed=seed;c.scenario.name='Lecture · '+id;if(id==='slippery')c.scenario.slip=.2;if(id==='features')c.representation='local-goal';return validateLaboratoryConfig(c);}
/** @param {HTMLElement} root @param {{active:()=>boolean,busy:()=>boolean,switchMode:()=>Promise<string>,preset:(id:string,seed:number)=>Promise<void>}} options */
export function mountLecture(root,options){root.innerHTML=`<button class="button secondary" id="lecture-toggle" aria-pressed="false">Enter lecture mode</button><div id="lecture-tools" hidden><p><strong>Lecture mode · temporary teaching session</strong>. Personal notes and student progress are hidden. Algorithms and RNG rules are unchanged. Reloading discards this temporary session.</p><div class="actions"><label class="field">Reproducible teaching preset<select id="lecture-preset">${PRESETS.map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label><label class="field">Preset root seed<input id="lecture-seed" type="number" min="0" max="4294967295" step="1" value="11"></label><button class="button primary" id="lecture-start">Start fresh preset</button></div><p>No trained checkpoint is supplied. Every preset starts at zero interactions; Step and Train collect real experience.</p></div><p id="lecture-status" role="status"></p><dialog id="lecture-dialog" aria-labelledby="lecture-title"><h2 id="lecture-title">Switch presentation session?</h2><p>Save or export any typed notes first. Entering creates a temporary teaching session with no personal notes or student progress. Leaving discards the teaching session and restores your saved work.</p><button class="button secondary" id="lecture-keep">Keep current session</button><button class="button primary" id="lecture-confirm">Switch session</button></dialog>`;
 const toggle=/** @type {HTMLButtonElement} */(root.querySelector('#lecture-toggle')),tools=/** @type {HTMLElement} */(root.querySelector('#lecture-tools')),status=/** @type {HTMLElement} */(root.querySelector('#lecture-status')),dialog=/** @type {HTMLDialogElement} */(root.querySelector('#lecture-dialog'));
 function refresh(){const active=options.active();document.documentElement.dataset.lecture=String(active);toggle.setAttribute('aria-pressed',String(active));toggle.textContent=active?'Exit lecture mode':'Enter lecture mode';tools.hidden=!active;}
 toggle.addEventListener('click',()=>{if(options.busy()){status.textContent='Finish or cancel the active/paused job before switching teaching sessions.';return;}dialog.showModal();});root.querySelector('#lecture-keep')?.addEventListener('click',()=>dialog.close());root.querySelector('#lecture-confirm')?.addEventListener('click',()=>{void(async()=>{if(options.busy())throw Error('Finish or cancel the active job first.');dialog.close();status.textContent=await options.switchMode();refresh();toggle.focus();})().catch(e=>status.textContent=e.message);});root.querySelector('#lecture-start')?.addEventListener('click',()=>{void(async()=>{if(options.busy())throw Error('Finish or cancel the active job first.');await options.preset(/** @type {HTMLSelectElement} */(root.querySelector('#lecture-preset')).value,Number(/** @type {HTMLInputElement} */(root.querySelector('#lecture-seed')).value));status.textContent='Fresh preset loaded with the declared seed. No learning result is supplied.';})().catch(e=>status.textContent=e.message);});refresh();return {refresh};
}
