import {imitationLessons} from './imitation.js';
import {deepLessons} from './deep-learning.js';
import {policyLessons} from './policy-methods.js';
import {advancedLessons} from './approximation-planning.js';
import { capabilities } from '../agents/tabular.js';
/** @typedef {'04'|'05'|'06'|'07'|'08'|'09'|'10'|'11'} LearningId */
export const learningLessons={...imitationLessons,...deepLessons,...advancedLessons,...policyLessons,
 '04':{title:'Model-free prediction',prerequisite:'03',source:'files/rl_course/5.pdf',missions:['Keep the policy fixed','Trace two prediction updates','Compare independent estimates'],observe:'Robo follows a specified right or uniform policy. First-visit Monte Carlo (MC) and TD(0) estimate its state values; neither improves the behavior policy. The corridor has slip 0.2, action cost −1 and goal-entry reward 5. State is fully observed position. The learners receive sampled transitions only.',concept:'What do these prediction methods change?',choices:['Value estimates for the specified policy','The policy after every update','The true transition probabilities'],correct:'Value estimates for the specified policy',prediction:'Which method can update before the episode ends? Predict how complete-return MC and one-step TD will differ on the same fixed policy.',math:'TD(0): V(s) ← V(s) + α[r + γV(s′) − V(s)]. True termination makes the bootstrap zero; an external cap does not. First-visit MC updates only the earliest occurrence of each state in a genuinely complete episode, using its discounted suffix return and sample-average step size 1/N. Capped or interrupted episodes are omitted from MC updates, not assigned a zero tail. Frequent caps can bias the retained complete-return sample; inspect the skipped count and increase the cap when appropriate.',worked:'For V=2, r=1, V′=4, γ=0.9 and α=0.1: target=4.6, error=2.6, new V=2.26. For complete rewards [0,0,5], γ=0.9, the return at the first state is 4.05.',questions:['TD fixture: what is the new V?','MC fixture: what is the return from [0,0,5] at γ=0.9?'],answers:[2.26,4.05],experiment:'Train MC and TD independently for five seed replicates each, with the same map, fixed policy, discount and episode budget. Compare their value error against an explicit known-model reference for that exact task/policy. Evaluation returns describe the fixed policy, not prediction accuracy.',challenge:'Which method has the lower observed mean prediction RMSE in your completed comparison?',challengeConcept:'How should first-visit MC handle an externally capped, incomplete episode?',challengeChoices:['Skip its return update; no complete return was observed','Pretend its unobserved tail is zero','Improve the policy instead'],challengeCorrect:'Skip its return update; no complete return was observed',reflection:'Compare MC and TD error ranges across the five independently trained agents. What evidence supports your explanation? Free text is saved, not graded.'},
 '05':{title:'Model-free control',prerequisite:'04',source:'files/rl_course/6.pdf',missions:['Record exploration decisions','Trace on/off-policy targets','Compare cliff behavior and frozen evaluation'],observe:'SARSA and Q-learning learn action values and a control policy. The cliff-like strip uses −1 per action and an additional −20 on every hazard visit; reaching G terminates. Hazards do not teleport or terminate the episode in this declared variant. There is a safe detour above the strip. Constant epsilon-greedy training explores uniformly among all four actions.',concept:'Which next-action value does SARSA use?',choices:['The next action actually selected by the behavior policy','Always the maximum next Q-value','The immediate reward only'],correct:'The next action actually selected by the behavior policy',prediction:'Predict how SARSA and Q-learning targets differ when the next behavior action is exploratory. Do not assume which method will win the cliff comparison.',math:'SARSA: Q(s,a) ← Q(s,a) + α[r + γQ(s′,a′) − Q(s,a)], where a′ is the actual next behavior action selected before the update. Q-learning replaces that continuation with max_b Q(s′,b). Both mask true termination; both retain the appropriate bootstrap at an external timeout. Epsilon-greedy ties use up, right, down, left. An exploration draw can coincidentally choose the greedy action.',worked:'With Q=3.12, reward=5, γ=0.9, α=0.1, next chosen Q=1 and max next Q=4.2: SARSA target=5.9 and new Q=3.398; Q-learning target=8.78 and new Q=3.686. At true termination both targets are 5 and new Q is 3.308.',questions:['SARSA fixture: what is the new Q?','Q-learning fixture: what is the new Q?'],answers:[3.398,3.686],experiment:'Compare SARSA and Q-learning under the same constant epsilon, alpha, gamma, map and per-agent episode cap/budget. Five independent training seeds per method and a shared fresh evaluation seed suite are recorded. Training behavior and frozen greedy evaluation are separate. No method is guaranteed to win.',challenge:'Which method has the higher observed mean frozen-evaluation return in your completed comparison?',challengeConcept:'What changes when Evaluate runs?',challengeChoices:['Learning freezes and the control policy acts greedily with epsilon 0','Training continues with a lower alpha','Training returns are relabeled as evaluation'],challengeCorrect:'Learning freezes and the control policy acts greedily with epsilon 0',reflection:'Compare training returns, hazard visits and frozen evaluation across seeds. Explain the selected-action versus maximum target without claiming a universal winner. This reflection is not automatically graded.'}
};
/** @param {LearningId} id */
export const methodsFor=(id)=>Object.entries(capabilities).filter(([key])=>(id==='04'?['mc','td']:id==='05'?['sarsa','q']:id==='06'?['linear-td','linear-sarsa','td','sarsa']:id==='07'?['dyna','q']:id==='09'?['dqn','q']:id==='10'?['dqn']:['reinforce','reinforce-baseline','actor-critic']).includes(key));
