import {validateLaboratoryConfig} from '../laboratory/config.js';
import {validateDeepConfig} from '../agents/deep/schema.js';
import { ACTIONS, record, scenarioHash, validateScenario } from '../environment/schema.js';
import { validateSeed } from '../environment/rng.js';
/** @typedef {'mc'|'td'|'sarsa'|'q'|'linear-td'|'linear-sarsa'|'dyna'|'reinforce'|'reinforce-baseline'|'actor-critic'|'dqn'} Algorithm */
/** @typedef {{schemaVersion:1,algorithmVersion:'tabular-v1'|'features-planning-v1'|'policy-v1'|'deep-v1',experimentVersion:number,lesson:'04'|'05'|'06'|'07'|'08'|'09'|'10'|'11'|'lab',algorithm:Algorithm,policy:'right'|'uniform',gamma:number,alpha:number,epsilon:number,epsilonSchedule:'constant',seed:number,rolloutLimit:number,allowUnreachable?:boolean,representation?:import('../agents/features.js').Representation,planningSteps?:number,deep?:import('../agents/deep/schema.js').DeepConfig,scenario:import('../environment/types.js').Scenario}} Config */
/** @param {'04'|'05'|'06'|'07'|'08'|'09'|'10'|'11'} lesson */
export function learningScenario(lesson) {
 if(lesson==='11')return validateScenario({schemaVersion:1,id:'learning-11',name:'Demonstration village',description:'Same-layout start split: demonstrations below; held-out trajectories above.',grid:['..G','...'],start:{x:0,y:1},slip:0,rewards:{step:-.05,collision:0,goal:1.05,hazard:0,collectible:0},features:{collectibles:false,battery:null,horizon:null},observation:'full'});
 if(['09','10'].includes(lesson))return validateScenario({schemaVersion:1,id:'learning-'+lesson,name:'Deep mountains',description:'Small vector-observation map; known-map evaluation, not transfer to new layouts.',grid:['..G','...'],start:{x:0,y:1},slip:.1,rewards:{step:-.05,collision:0,goal:1.05,hazard:0,collectible:0},features:{collectibles:false,battery:null,horizon:null},observation:'full'});
 if(lesson==='08')return validateScenario({schemaVersion:1,id:'learning-08',name:'Policy summit',description:'Deterministic movement; stochastic learned actor. Position is the complete task state.',grid:['..G','...'],start:{x:0,y:1},slip:0,rewards:{step:-1,collision:0,goal:11,hazard:0,collectible:0},features:{collectibles:false,battery:null,horizon:null},observation:'full'});
 if(lesson==='06'||lesson==='07')return validateScenario({schemaVersion:1,id:'learning-'+lesson,name:lesson==='06'?'Inventory features':'Planning marsh',description:lesson==='06'?'Full position and consumed-collectible state; compare explicit representations.':'Stationary deterministic maze; learned model contains sampled transitions only.',grid:lesson==='06'?['.CG','...']:['...G','.#..','.#..','....'],start:lesson==='06'?{x:0,y:0}:{x:0,y:3},slip:0,rewards:{step:-1,collision:0,goal:11,hazard:0,collectible:6},features:{collectibles:lesson==='06',battery:null,horizon:null},observation:'full'});
  return validateScenario({schemaVersion:1,id:'learning-'+lesson,name:lesson==='04'?'Prediction corridor':'Cliff detour',description:lesson==='04'?'Fixed policy on a slippery corridor.':'Hazard strip: each hazard visit costs 21 including step; no teleport or extra termination.',grid:lesson==='04'?['..G','###']:['......','......','......','.HHHHG'],start:lesson==='04'?{x:0,y:0}:{x:0,y:3},slip:lesson==='04'?.2:0,rewards:{step:-1,collision:0,goal:lesson==='04'?6:0,hazard:lesson==='04'?0:-20,collectible:0},features:{collectibles:false,battery:null,horizon:null},observation:'full'});
}
/** @param {'04'|'05'|'06'|'07'|'08'|'09'|'10'|'11'} lesson @returns {Config} */
export function defaultConfig(lesson) { if(lesson==='11')return {schemaVersion:1,algorithmVersion:'policy-v1',experimentVersion:1,lesson,algorithm:'actor-critic',policy:'uniform',gamma:.9,alpha:.1,epsilon:0,epsilonSchedule:'constant',seed:11,rolloutLimit:80,scenario:learningScenario(lesson)}; if(lesson==='09'||lesson==='10')return {schemaVersion:1,algorithmVersion:'deep-v1',experimentVersion:1,lesson,algorithm:'dqn',policy:'uniform',gamma:.9,alpha:.03,epsilon:.2,epsilonSchedule:'constant',seed:11,rolloutLimit:60,deep:{replay:true,target:true,capacity:256,batch:16,targetEvery:40},scenario:learningScenario(lesson)}; if(lesson==='08')return {schemaVersion:1,algorithmVersion:'policy-v1',experimentVersion:1,lesson,algorithm:'reinforce-baseline',policy:'uniform',gamma:.9,alpha:.05,epsilon:0,epsilonSchedule:'constant',seed:11,rolloutLimit:80,scenario:learningScenario(lesson)}; if(lesson==='06'||lesson==='07')return {schemaVersion:1,algorithmVersion:'features-planning-v1',experimentVersion:1,lesson,algorithm:lesson==='06'?'linear-td':'dyna',policy:'uniform',gamma:.9,alpha:lesson==='06'?.1:.2,epsilon:.2,epsilonSchedule:'constant',seed:11,rolloutLimit:80,scenario:learningScenario(lesson),...(lesson==='06'?{representation:'informative'}:{planningSteps:5})};return {schemaVersion:1,algorithmVersion:'tabular-v1',experimentVersion:1,lesson,algorithm:lesson==='04'?'td':'sarsa',policy:'right',gamma:.9,alpha:.1,epsilon:.15,epsilonSchedule:'constant',seed:11,rolloutLimit:lesson==='04'?80:120,scenario:learningScenario(lesson)}; }
/** @param {unknown} input @returns {Config} */
export function validateConfig(input) {
  if(input&&typeof input==='object'&&'lesson' in input&&input.lesson==='lab')return validateLaboratoryConfig(input);
  const c=record(input,['schemaVersion','algorithmVersion','experimentVersion','lesson','algorithm','policy','gamma','alpha','epsilon','epsilonSchedule','seed','rolloutLimit','scenario',...(input&&typeof input==='object'&&'lesson' in input&&['09','10'].includes(String(input.lesson))?['deep']:[]),...(input&&typeof input==='object'&&'lesson' in input&&input.lesson==='06'?['representation']:input&&typeof input==='object'&&'lesson' in input&&input.lesson==='07'?['planningSteps']:[])]);
  if(c.schemaVersion!==1 || c.algorithmVersion!==(['09','10'].includes(String(c.lesson))?'deep-v1':['08','11'].includes(String(c.lesson))?'policy-v1':['06','07'].includes(String(c.lesson))?'features-planning-v1':'tabular-v1') || !['04','05','06','07','08','09','10','11'].includes(String(c.lesson)) || !Number.isInteger(c.experimentVersion) || Number(c.experimentVersion)<1 || Number(c.experimentVersion)>1000000) throw Error('Unsupported learning configuration.');
  if(!(c.lesson==='04'?['mc','td']:c.lesson==='05'?['sarsa','q']:c.lesson==='06'?['linear-td','linear-sarsa','td','sarsa']:c.lesson==='07'?['dyna','q']:['08','11'].includes(String(c.lesson))?['reinforce','reinforce-baseline','actor-critic']:c.lesson==='09'?['dqn','q']:['dqn']).includes(String(c.algorithm)) || !['right','uniform'].includes(String(c.policy)) || c.epsilonSchedule!=='constant') throw Error('Algorithm/policy incompatible with this lesson.');
  for(const [key,min,max] of /** @type {[string,number,number][]} */([['gamma',0,.99],['alpha',.001,1],['epsilon',0,1]])) if(typeof c[key]!=='number' || !Number.isFinite(c[key]) || Number(c[key])<min || Number(c[key])>max) throw Error('Invalid '+key+'.');
  if(c.lesson==='06'&&!['informative','aliased'].includes(String(c.representation)))throw Error('Declare a feature representation.');
  if(c.lesson==='07'&&(!Number.isInteger(c.planningSteps)||Number(c.planningSteps)<0||Number(c.planningSteps)>20||c.algorithm==='q'&&c.planningSteps!==0))throw Error('Planning steps must be 0–20; Q-learning uses zero.');
  if(['08','11'].includes(String(c.lesson))&&(c.epsilon!==0||c.policy!=='uniform'))throw Error('Policy methods sample learned softmax; epsilon is unused and must be zero.');
  if(['09','10'].includes(String(c.lesson)))validateDeepConfig(/** @type {import('../agents/deep/schema.js').DeepConfig} */(c.deep));
  validateSeed(c.seed);
  if(!Number.isInteger(c.rolloutLimit) || Number(c.rolloutLimit)<1 || Number(c.rolloutLimit)>1000) throw Error('Episode cap must be 1–1000.');
  const scenario=validateScenario(c.scenario);
  if(JSON.stringify(scenario)!==JSON.stringify(learningScenario(/** @type {'04'|'05'|'06'|'07'|'08'|'09'|'10'|'11'} */(c.lesson)))) throw Error('This milestone supports the declared lesson maps only.');
  return structuredClone(/** @type {Config} */({...c,scenario}));
}
/** Canonical configuration identity, separate from presentation speed. @param {unknown} value */
export function hashData(value) {
  /** @param {unknown} item @returns {unknown} */
  const sort=(item)=>Array.isArray(item)?item.map(sort):item && typeof item==='object'?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sort(v)])):item;
  let hash=2166136261;for(const c of JSON.stringify(sort(value)))hash=Math.imul(hash^c.charCodeAt(0),16777619)>>>0;
  return 'fnv1a32-'+hash.toString(16).padStart(8,'0');
}
/** @param {Config} c */
export const experimentIdentity=(c)=>({configHash:hashData(c),scenarioHash:scenarioHash(c.scenario),representation:c.representation??(c.lesson==='lab'&&c.scenario.observation==='position'?'position-observation':['04','05'].includes(c.lesson)?'full-position':'full-state'),actionOrder:[...ACTIONS],algorithmVersion:c.algorithmVersion,epsilonSchedule:c.epsilonSchedule});
