import {describe,test,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {featureEncoder,actionFeatures,dot,linearEstimate,stateTableSize} from '../../src/agents/features.js';
import {LinearLearner,linearBackup} from '../../src/agents/linear.js';
import {DynaLearner,learnModel} from '../../src/agents/dyna.js';
import {defaultConfig,hashData} from '../../src/training/config.js';
import {TrainingRun,validateRunCheckpoint} from '../../src/training/run.js';
import {FrozenEvaluation,evaluationSeeds} from '../../src/evaluation/frozen.js';
import {WorkerHost} from '../../src/training/worker-host.js';
import {LearningStore} from '../../src/persistence/learning-store.js';
import {newComparison,runComparison,comparisonSummary,observedWinner} from '../../src/evaluation/comparison.js';
import {validateComparison} from '../../src/evaluation/comparison-validation.js';
const c6=()=>defaultConfig('06'),c7=()=>defaultConfig('07');
const sample={state:'0,0|c=0',action:1,reward:1,next:'1,0|c=1',terminated:false,truncated:false,nextAction:2};
const advance=(run,n)=>{for(let i=0;i<n;i++)run.step();return run;};
const config=algorithm=>({...defaultConfig(algorithm==='dyna'?'07':'06'),algorithm});
export function workerHarness(config){const queue=[],messages=[];let commandId=0,time=0;const host=new WorkerHost(m=>messages.push(m),{schedule:f=>queue.push(f),now:()=>time+=.1});const request=(command,payload={})=>host.handle({protocol:1,runId:'fixture',configHash:hashData(config),commandId:++commandId,command,payload});request('initialize',{config});return {host,queue,messages,request,drain:()=>{let n=0;while(queue.length){queue.shift()();if(++n>30000)throw Error('unbounded');}if(messages.at(-1)?.event==='error')throw Error(messages.at(-1).error);}};}
/** Exercises the production worker state machine with a deterministic test scheduler. */
function comparisonWorker(){let h;return {initialize:async(c)=>{h=workerHarness(c);return h.messages.at(-1);},command:async(command,payload)=>{h.request(command,payload);h.drain();return h.messages.at(-1);}};}

describe('explicit features and numerical linear approximation',()=>{
 test('dimensions, norms and action blocks are explicit; inventory distinguishes otherwise equal states',()=>{const e=featureEncoder(c6().scenario),s={x:0,y:0,collected:0},t={...s,collected:1};expect(e.dimension).toBe(6);expect(e.names).toHaveLength(6);expect(e.encode(s)).not.toEqual(e.encode(t));const a=featureEncoder(c6().scenario,'aliased');expect(a.encode(s)).toEqual(a.encode(t));const phi=e.encode({x:2,y:1,collected:1});expect(dot(phi,phi)).toBeCloseTo(1,14);const block=actionFeatures(phi,2);expect(block).toHaveLength(24);expect(block.slice(12,18)).toEqual(phi);expect(block.slice(0,12)).toEqual(Array(12).fill(0));expect(()=>dot([0],phi)).toThrow();expect(()=>actionFeatures(phi,4)).toThrow();});
 test('battery and finite task time are encoded when enabled, unlike deliberate ablation',()=>{const scenario={...c6().scenario,features:{collectibles:true,battery:8,horizon:10}},e=featureEncoder(scenario),s={x:0,y:0,collected:0,battery:8,remaining:10};expect(e.dimension).toBe(8);expect(e.encode(s).slice(-2)).toEqual([1/Math.sqrt(8),1/Math.sqrt(8)]);expect(e.encode({...s,battery:4,remaining:5})).not.toEqual(e.encode(s));expect(featureEncoder(scenario,'aliased').encode(s).slice(-2)).toEqual([0,0]);});
 test('state table calculator counts all enabled combinations using exact integers',()=>{const result=stateTableSize({width:3,height:2,walls:0,collectibles:1,battery:null,horizon:null,actions:4});expect(result.states).toBe(12n);expect(result.entries).toBe(48n);expect(result.bytes).toBe(384n);expect(stateTableSize({width:3,height:2,walls:1,collectibles:2,battery:2,horizon:3,actions:4}).states).toBe(240n);expect(()=>stateTableSize({width:3,height:2,walls:6,collectibles:1,battery:null,horizon:null,actions:4})).toThrow();});
 test('hand fixture: target 1.36, delta 1.21, weights .321/-.0395, prediction .30125',()=>{const u=linearBackup([.2,-.1],[1,.5],1+.9*.4,.1);expect(u.old).toBeCloseTo(.15,14);expect(u.error).toBeCloseTo(1.21,14);expect(u.after[0]).toBeCloseTo(.321,14);expect(u.after[1]).toBeCloseTo(-.0395,14);expect(u.next).toBeCloseTo(.30125,14);expect(()=>linearBackup([0],[1],Infinity,.1)).toThrow();});
 test.each(['linear-td','linear-sarsa'])('%s computes actual semi-gradient and preserves terminal/cap distinction',algorithm=>{const c=config(algorithm),make=()=>{const l=new LinearLearner(c);l.parameters.weights=l.parameters.weights.map((_,i)=>(i+1)/100);return l;};const l=make(),before=l.snapshot(),phi=featureEncoder(c.scenario).encode({x:0,y:0,collected:0}),features=algorithm==='linear-td'?phi:actionFeatures(phi,1),next=linearEstimate(c,before,sample.next,algorithm==='linear-sarsa'?2:undefined);const u=l.observe({...sample,truncated:true})[0];expect(u.target).toBeCloseTo(1+c.gamma*next,14);u.weightsAfter.forEach((w,i)=>expect(w).toBeCloseTo(before.weights[i]+c.alpha*u.error*features[i],14));expect(make().observe({...sample,terminated:true})[0].bootstrap).toBe(0);expect(make().observe({...sample,truncated:true})[0].bootstrap).not.toBe(0);});
 test('shared features change an unvisited state estimate and preserve the full observation',()=>{const r=new TrainingRun(c6()),key='0,1|c=0';const before=linearEstimate(r.config,r.learner.parameters,key);r.step();expect(linearEstimate(r.config,r.learner.parameters,key)).not.toBe(before);expect(r.environment.getObservation()).toHaveProperty('collected');expect(r.learner.parameters.visits[key]).toBeUndefined();});
 test('linear SARSA executes the next action actually used in its target',()=>{const r=new TrainingRun({...c6(),algorithm:'linear-sarsa',epsilon:1}),a=r.step(),b=r.step();expect(a.nextDecision).toEqual(b.decision);expect(a.updates[0].nextAction).toBe(b.decision.action);});
});

describe('observed deterministic model and Dyna planning',()=>{
 test('hand fixture: one real terminal reward 2 gives Q=1, one plan gives Q=1.5; real visits remain one',()=>{const l=new DynaLearner({...c7(),alpha:.5,planningSteps:1});const updates=l.observe({state:'0,3',action:1,reward:2,next:'1,3',terminated:true,truncated:false});expect(updates.map(u=>u.next)).toEqual([1,1.5]);expect(updates.map(u=>u.origin)).toEqual(['real','planning']);expect(l.parameters.updates).toBe(2);expect(l.parameters.planningUpdates).toBe(1);expect(l.parameters.visits['0,3']).toEqual([0,1,0,0]);expect(Object.keys(l.parameters.model)).toEqual(['0,3 / 1']);});
 test('model remembers repeated observations, rejects conflicts, and does not store rollout cutoff as terminal',()=>{const m={},s={state:'0,3',action:1,reward:-1,next:'1,3',terminated:false,truncated:true};learnModel(m,s);learnModel(m,{...s,truncated:false});expect(m['0,3 / 1'].visits).toBe(2);expect(m['0,3 / 1'].terminated).toBe(false);expect(m['0,3 / 1']).not.toHaveProperty('truncated');expect(()=>learnModel(m,{...s,reward:9})).toThrow(/Conflicting/);});
 test('zero planning exactly matches ordinary Q-learning values, decisions, visits, interactions',()=>{const a=new TrainingRun({...c7(),planningSteps:0}),b=new TrainingRun({...c7(),algorithm:'q',planningSteps:0});for(let i=0;i<350;i++){const x=a.step(),y=b.step();expect(x.decision).toEqual(y.decision);expect(x.transition).toEqual(y.transition);}expect(a.learner.parameters.q).toEqual(b.learner.parameters.q);expect(a.learner.parameters.visits).toEqual(b.learner.parameters.visits);expect(a.learner.parameters.planningUpdates).toBe(0);});
 test.each([0,1,5,20])('%i plans per real step has exact counters and samples only observed pairs',n=>{const r=advance(new TrainingRun({...c7(),planningSteps:n}),12),p=r.learner.parameters;expect(r.interactions).toBe(12);expect(p.updates).toBe(12*(1+n));expect(p.planningUpdates).toBe(12*n);expect(Object.values(p.model).reduce((s,e)=>s+e.visits,0)).toBe(12);for(const u of r.last.updates.filter(u=>u.origin==='planning'))expect(p.model[u.modelKey].next).toBeDefined();expect(()=>validateRunCheckpoint(r.checkpoint())).not.toThrow();});
 test('planning RNG is independent; changing its seed changes neither environment nor agent RNG after a forced action',()=>{const a=new TrainingRun(c7()),b=TrainingRun.restore(a.checkpoint());b.learner.parameters.planningRng.state=123;const x=a.step(),y=b.step();expect(x.decision).toEqual(y.decision);expect(x.transition).toEqual(y.transition);expect(a.agentRng.snapshot()).toEqual(b.agentRng.snapshot());});
});

describe('advanced runtime, budgets and backward compatibility',()=>{
 test.each(['linear-td','linear-sarsa','dyna'])('%s save/load, frozen evaluation, episode reset and animation scheduling preserve parameters',algorithm=>{const r=advance(new TrainingRun(config(algorithm)),37),before=r.checkpoint(),copy=TrainingRun.restore(before);const evaluation=new FrozenEvaluation(r.config,r.learner.snapshot(),evaluationSeeds(3));while(!evaluation.done)evaluation.step();expect(r.checkpoint()).toEqual(before);for(let i=0;i<40;i++){expect(r.step()).toEqual(copy.step());copy.snapshot();copy.snapshot();}const parameters=r.learner.snapshot();r.resetEpisode();expect(r.learner.snapshot()).toEqual(parameters);expect(TrainingRun.restore(r.checkpoint()).checkpoint()).toEqual(r.checkpoint());});
 test.each(['linear-td','linear-sarsa','dyna'])('%s chunk pause/resume preserves exact real interaction budget including partial rollout',algorithm=>{const c=config(algorithm),h=workerHarness(c);h.request('trainInteractions',{interactions:113});h.queue.shift()();h.request('pause');const paused=h.host.run.checkpoint();h.drain();expect(h.host.run.checkpoint()).toEqual(paused);h.request('resume');h.drain();expect(h.host.run.checkpoint()).toEqual(advance(new TrainingRun(c),113).checkpoint());expect(h.host.run.interactions).toBe(113);h.request('trainInteractions',{interactions:500});h.queue.shift()();h.request('cancel');const cancelled=h.host.run.checkpoint();h.drain();expect(h.host.run.checkpoint()).toEqual(cancelled);});
 test.each(['06','07'])('lesson %s compares equal real budgets and retains unsmoothed checkpoints',async id=>{const c=newComparison(defaultConfig(id),60,'fixture prediction');await runComparison(comparisonWorker(),c,()=>false,()=>{});expect(c.runs).toHaveLength(id==='06'?15:10);expect(c.runs.every(r=>r.interactions===60)).toBe(true);expect(c.runs.every(r=>r.curve.map(p=>p.interactions).join(',')==='20,40,60')).toBe(true);expect(()=>validateComparison(c,id)).not.toThrow();expect(comparisonSummary(c,20).every(s=>s.n===5)).toBe(true);expect(observedWinner(c)).not.toBe('unavailable');const bad=structuredClone(c);bad.runs[0].interactions++;expect(()=>validateComparison(bad,id)).toThrow();const unfair=structuredClone(c);unfair.runs[0].curve[0].planningUpdates++;expect(()=>validateComparison(unfair,id)).toThrow();},30000);
 test('legacy task-04 browser backup is readable without migration and import preserves newer lessons',async()=>{const store=new LearningStore({getItem:()=>null,setItem:()=>{}}),text=readFileSync('evidence/task-04/browser-qa-learning.json','utf8'),legacy=JSON.parse(text),parsed=store.parseImport(text);expect(parsed.progress).toEqual(legacy.progress);expect(parsed.runs).toEqual(legacy.runs);store.lesson('06').reflection='A new lesson record survives importing an older file';await store.replace(parsed);expect(store.lesson('06').reflection).toContain('survives');for(const c of Object.values(parsed.runs)){const restored=TrainingRun.restore(c);expect(restored.checkpoint()).toEqual(c);expect(()=>restored.step()).not.toThrow();}});
 test('linear and model tampering are rejected before import',()=>{for(const algorithm of ['linear-td','linear-sarsa','dyna']){const c=advance(new TrainingRun(config(algorithm)),5).checkpoint();if(algorithm==='dyna')Object.values(c.parameters.model)[0].reward=9;else c.parameters.weights.push(0);expect(()=>validateRunCheckpoint(c)).toThrow();}});
});
