import {describe,test,expect,beforeAll} from 'vitest';
import {readFileSync,writeFileSync} from 'node:fs';
import {defaultConfig,hashData} from '../../src/training/config.js';
import {prepareLearner} from '../../src/agents/registry.js';
import {TrainingRun,validateRunCheckpoint} from '../../src/training/run.js';
import {FrozenEvaluation,evaluationSeeds} from '../../src/evaluation/frozen.js';
import {Network,initialWeights,tensorMemory,DqnLearner} from '../../src/agents/deep/learner.js';
import {ReplayBuffer,tdTarget,vectorEncoder,expectedUpdates} from '../../src/agents/deep/schema.js';
import {createRng} from '../../src/environment/rng.js';
import {WorkerHost} from '../../src/training/worker-host.js';
import {LearningStore} from '../../src/persistence/learning-store.js';
import {comparisonVariants,newComparison,runComparison} from '../../src/evaluation/comparison.js';
import {validateComparison} from '../../src/evaluation/comparison-validation.js';
const config=()=>defaultConfig('09');
const advance=(r,n)=>{for(let i=0;i<n;i++)r.step();return r;};
const sample=(i=0)=>({state:'0,1',action:1,reward:-.05,next:'1,1',terminated:false,truncated:false,id:i});
beforeAll(()=>prepareLearner(config()));
function harness(c){const queue=[],messages=[];let id=0,t=0;const host=new WorkerHost(m=>messages.push(m),{schedule:f=>queue.push(f),now:()=>t+=.5});const request=(command,payload={})=>host.handle({protocol:1,runId:'deep-fixture',configHash:hashData(c),commandId:++id,command,payload});const drain=()=>{let n=0;while(queue.length){queue.shift()();if(++n>50000)throw Error('Unbounded worker');}if(messages.at(-1)?.error)throw Object.assign(Error(messages.at(-1).error),{checkpoint:messages.at(-1).snapshot?.checkpoint});};request('initialize',{config:c});return {host,queue,messages,request,drain};}
describe('neural targets, replay and representation',()=>{
 test('terminal reward only; external cutoff retains continuation',()=>{expect(tdTarget(1,true,.9,100)).toBe(1);expect(tdTarget(1,false,.9,.5)).toBe(1.45);expect(tdTarget(-.05,false,0,100)).toBe(-.05);});
 test('vector includes all enabled task state variables',()=>{const scenario={...config().scenario,grid:['.CG','...'],features:{collectibles:true,battery:8,horizon:10}};const enc=vectorEncoder(scenario);expect(enc.dimension).toBe(5);expect(enc.encode('0,1|c=1|b=4|t=5')).toEqual([-1,1,1,.5,.5]);expect(()=>enc.encode('0,1')).toThrow();});
 test('bounded ring replaces oldest, preserves cursor and uniform seeded replay',()=>{const b=new ReplayBuffer(32);for(let i=0;i<100;i++)b.push(sample());expect(b.state.items).toHaveLength(32);expect(b.state.seen).toBe(100);expect(b.state.cursor).toBe(4);expect(Math.min(...b.state.items.map(s=>s.id))).toBe(69);const r=createRng(10),saved=r.snapshot(),a=b.sample(32,r,true);r.restore(saved);expect(new ReplayBuffer(32,b.snapshot()).sample(32,r,true)).toEqual(a);const counts=new Map();for(let i=0;i<32000;i++){const id=b.sample(1,r,true)[0].id;counts.set(id,(counts.get(id)??0)+1);}expect([...counts.values()].every(n=>Math.abs(n/32000-1/32)<.004)).toBe(true);expect(()=>b.sample(33,r)).toThrow();});
 test('no replay uses a chronological matched-size batch without consuming replay randomness',()=>{const b=new ReplayBuffer(32),r=createRng(5);for(let i=0;i<40;i++)b.push(sample());const before=r.snapshot();expect(b.sample(4,r,false).map(s=>s.id)).toEqual([37,38,39,40]);expect(r.snapshot()).toEqual(before);});
 test('seeded initialization is deterministic and differs across roots',()=>{expect(initialWeights(2,4)).toEqual(initialWeights(2,4));expect(initialWeights(2,5)).not.toEqual(initialWeights(2,4));expect(initialWeights(2,4).flat()).toHaveLength(388);});
});
describe('real TensorFlow autodiff and optimizer',()=>{
 test('backprop matches central differences across every layer',()=>{const weights=initialWeights(2,44);weights[1].fill(.2);weights[3].fill(.2);const n=new Network(2,weights),vectors=[[.3,.7],[-.2,.4]],actions=[1,2],targets=[.8,-.2],grad=n.gradient(vectors,actions,targets),base=n.weights(),eps=.001;try{for(const [layer,index]of [[0,3],[1,3],[2,38],[3,4],[4,19],[5,1]]){const plus=structuredClone(base),minus=structuredClone(base);plus[layer][index]+=eps;minus[layer][index]-=eps;n.assign(plus);const high=n.gradient(vectors,actions,targets).loss;n.assign(minus);const low=n.gradient(vectors,actions,targets).loss;expect(grad.gradients[layer][index]).toBeCloseTo((high-low)/(2*eps),3);}expect(grad.gradients.flat().some(n=>n!==0)).toBe(true);}finally{n.dispose();}});
 test('half-squared loss and SGD output-bias fixture, frozen bootstrap, true terminal',()=>{const c={...config(),alpha:.1,deep:{...config().deep,batch:4,targetEvery:2}},l=new DqnLearner(c);try{const zero=initialWeights(2,1).map(w=>w.map(()=>0));zero[5].fill(.2);l.online.assign(zero);const target=structuredClone(zero);target[5].fill(.5);l.target.assign(target);const s={state:'0,1',action:1,reward:1,next:'1,1',terminated:false,truncated:true};for(let i=0;i<3;i++)expect(l.observe(s)).toEqual([]);const u=l.observe(s)[0];expect(u.target).toBe(1.45);expect(u.deep.loss).toBeCloseTo(.78125,6);expect(l.online.weights()[5][1]).toBeCloseTo(.325,6);expect(l.target.weights()).toEqual(target);expect(u.deep.gradientNorm).toBeCloseTo(1.25,6);expect(l.parameters.updates).toBe(1);l.observe({...s,terminated:true,truncated:false});expect(l.deep.targetCopies).toBe(1);expect(l.target.weights()).toEqual(l.online.weights());}finally{l.dispose();}});
 test('actual terminal minibatches mask optimistic next values; online-bootstrap ablation uses online values',()=>{for(const terminal of [true,false]){const c={...config(),alpha:.1,deep:{...config().deep,batch:4,target:terminal}},l=new DqnLearner(c);try{const online=initialWeights(2,1).map(w=>w.map(()=>0));online[5].fill(.2);const target=structuredClone(online);target[5].fill(100);l.online.assign(online);l.target.assign(target);const s={state:'1,0',action:1,reward:1,next:'2,0',terminated:terminal,truncated:!terminal};let update;for(let i=0;i<4;i++)update=l.observe(s)[0];expect(update.target).toBeCloseTo(terminal?1:1.18,6);expect(update.bootstrap).toBeCloseTo(terminal?0:.2,6);expect(l.online.weights()[5][1]).toBeCloseTo(terminal?.28:.298,6);}finally{l.dispose();}}});
 test('no-target variant has no hard copies and retains detached semi-gradient targets',()=>{const c={...config(),deep:{...config().deep,target:false,batch:4}},r=advance(new TrainingRun(c),100);try{expect(r.learner.parameters.deep.targetCopies).toBe(0);expect(()=>validateRunCheckpoint(r.checkpoint())).not.toThrow();expect(r.learner.parameters.updates).toBe(97);}finally{r.dispose();}});
 test('nonfinite update preserves last finite parameters and recorded failure',()=>{const l=new DqnLearner({...config(),deep:{...config().deep,batch:4}}),before=l.online.weights();try{for(let i=0;i<4;i++)l.observe({state:'0,1',action:1,reward:1e300,next:'1,1',terminated:true,truncated:false});expect(l.deep.failure.reason).toMatch(/Nonfinite/);expect(l.online.weights()).toEqual(before);expect(l.parameters.updates).toBe(0);expect(l.buffer.state.seen).toBe(4);expect(()=>l.observe(sample())).toThrow();}finally{l.dispose();}});
});
describe('neural runtime persistence, budgets, isolation and memory',()=>{
 test('exact seeded continuation across save/load including optimizer, replay and target state',()=>{const r=advance(new TrainingRun(config()),121),cp=r.checkpoint();validateRunCheckpoint(cp);const copy=TrainingRun.restore(cp);try{for(let i=0;i<30;i++)expect(r.step()).toEqual(copy.step());expect(r.checkpoint()).toEqual(copy.checkpoint());const parameters=r.learner.snapshot();r.resetEpisode();expect(r.learner.snapshot()).toEqual(parameters);validateRunCheckpoint(r.checkpoint());}finally{r.dispose();copy.dispose();}});
 test('frozen greedy neural evaluation changes no parameter, replay, target, RNG or optimizer',()=>{const r=advance(new TrainingRun(config()),150),before=r.checkpoint(),memory=tensorMemory(),e=new FrozenEvaluation(r.config,r.learner.snapshot(),evaluationSeeds(12));try{while(!e.done)e.step();expect(e.result().rule).toContain('Frozen greedy policy; epsilon 0');expect(e.result().trainingUpdates).toBe(0);expect(r.checkpoint()).toEqual(before);}finally{e.dispose();expect(tensorMemory()).toEqual(memory);r.dispose();}});
 test('pause/resume/cancel, replacement and dispose preserve deterministic work and release tensors',()=>{const base=tensorMemory(),c=config(),h=harness(c),reference=advance(new TrainingRun(c),83);try{h.request('trainInteractions',{interactions:83});h.queue.shift()();h.request('pause');const stopped=h.host.run.checkpoint();h.drain();expect(h.host.run.checkpoint()).toEqual(stopped);h.request('resume');h.drain();expect(h.host.run.checkpoint()).toEqual(reference.checkpoint());h.request('trainInteractions',{interactions:300});h.queue.shift()();h.request('cancel');const cancelled=h.host.run.checkpoint();h.drain();expect(h.host.run.checkpoint()).toEqual(cancelled);h.request('evaluate');h.queue.shift()();h.request('cancel');h.request('initialize',{config:c});h.request('dispose');}finally{reference.dispose();h.host.run?.dispose();}expect(tensorMemory()).toEqual(base);});
 test('invalid concurrent commands do not abandon the running budget; mismatched resume frees temporary tensors',()=>{const base=tensorMemory(),c=config(),h=harness(c);try{h.request('trainInteractions',{interactions:50});h.queue.shift()();h.request('step');expect(h.messages.at(-1).event).toBe('error');expect(h.host.mode).toBe('training');h.drain();expect(h.host.run.interactions).toBe(50);const checkpoint=h.host.run.checkpoint(),memory=tensorMemory();checkpoint.config.seed=21;const other=advance(new TrainingRun({...c,seed:21}),50);h.request('initialize',{config:c,checkpoint:other.checkpoint()});expect(h.messages.at(-1).error).toMatch(/configuration mismatch/);other.dispose();expect(tensorMemory()).toEqual(memory);}finally{h.host.run?.dispose();}expect(tensorMemory()).toEqual(base);});
 test('worker preserves a finite failure checkpoint and can reset from it',()=>{const c={...config(),deep:{...config().deep,batch:4}},h=harness(c);try{const high=initialWeights(2,1).map(w=>w.map(()=>0));high[5].fill(100000);h.host.run.learner.online.assign(high);h.host.run.learner.target.assign(high);h.host.run.learner.refresh();h.request('trainInteractions',{interactions:40});expect(()=>h.drain()).toThrow(/excessive Q/);const event=h.messages.at(-1),cp=event.snapshot.checkpoint;expect(event.event).toBe('error');expect(cp.interactions).toBe(4);expect(cp.parameters.updates).toBe(0);expect(cp.parameters.deep.failure.interaction).toBe(4);validateRunCheckpoint(cp);const copy=TrainingRun.restore(cp);try{expect(()=>copy.step()).toThrow(/excessive Q/);}finally{copy.dispose();}h.request('initialize',{config:c});h.request('trainInteractions',{interactions:20});h.drain();expect(h.host.run.learner.parameters.deep.failure).toBeNull();}finally{h.host.run?.dispose();}});
 test('cancelled failed comparison retains the failed seed and checkpoint without claiming completion',async()=>{let active;const worker={initialize:async c=>{active?.host.run?.dispose();active=harness(c);const high=initialWeights(2,1).map(w=>w.map(()=>0));high[5].fill(100000);active.host.run.learner.online.assign(high);active.host.run.learner.target.assign(high);active.host.run.learner.refresh();return active.messages.at(-1);},command:async(command,payload)=>{active.request(command,payload);active.drain();return active.messages.at(-1);}};const c=newComparison(defaultConfig('10'),60,'Fault-injection fixture, not natural performance');try{await expect(runComparison(worker,c,()=>false,()=>{})).rejects.toThrow();expect(c.status).toBe('cancelled');expect(c.failures).toHaveLength(1);validateComparison(c,'10');expect(c.runs).toHaveLength(0);}finally{active?.host.run?.dispose();}});
 test('repeated runs keep live tensor count constant and release all tensors after disposal',()=>{const baseline=tensorMemory(),rows=[];for(let i=0;i<5;i++){const r=new TrainingRun({...config(),seed:i});advance(r,40);const warm=tensorMemory();advance(r,80);expect(tensorMemory()).toEqual(warm);const e=new FrozenEvaluation(r.config,r.learner.snapshot(),evaluationSeeds(i));while(!e.done)e.step();e.dispose();expect(tensorMemory()).toEqual(warm);r.dispose();expect(tensorMemory()).toEqual(baseline);rows.push({run:i,warm,after:tensorMemory()});}writeFileSync('evidence/task-11/tensor-memory-unit.json',JSON.stringify({source:'Actual TensorFlow.js CPU backend in Node/Vitest; not browser heap measurements',baseline,rows},null,2));},20000);
 test.each(['shape','replay','optimizer','copies','loss','trace'])('rejects malformed %s checkpoint',kind=>{const r=advance(new TrainingRun(config()),30),cp=r.checkpoint();r.dispose();if(kind==='shape')cp.parameters.deep.online[0].pop();if(kind==='replay')cp.parameters.deep.replay.items[0].reward=77;if(kind==='optimizer')cp.parameters.deep.optimizer.iterations++;if(kind==='copies')cp.parameters.deep.targetCopies++;if(kind==='loss')cp.parameters.deep.metrics.at(-1).update++;if(kind==='trace')cp.last.updates[0].target++;expect(()=>validateRunCheckpoint(cp)).toThrow();});
 test('controlled ablations match everything except their declared single factor',()=>{const variants=comparisonVariants(defaultConfig('10'));expect(variants).toHaveLength(3);for(const v of variants)expect({...v.config,deep:{...v.config.deep,replay:true,target:true}}).toEqual(variants[0].config);expect(variants[1].config.deep.replay).toBe(false);expect(variants[2].config.deep.target).toBe(false);});
 test('five-seed controlled comparison has exact real/update budgets and validated saved evidence',async()=>{let active;const worker={initialize:async c=>{active?.host.run?.dispose();await prepareLearner(c);active=harness(c);return active.messages.at(-1);},command:async(command,payload)=>{active.request(command,payload);active.drain();return active.messages.at(-1);}};const comparison=newComparison(defaultConfig('10'),60,'Developer QA prior prediction');try{await runComparison(worker,comparison,()=>false,()=>{});validateComparison(comparison,'10');expect(comparison.runs).toHaveLength(15);for(const r of comparison.runs){expect(r.interactions).toBe(60);expect(r.updates).toBe(expectedUpdates(r.config,60));expect(r.planningUpdates).toBe(0);expect(r.curve.map(p=>p.interactions)).toEqual([20,40,60]);}}finally{active?.host.run?.dispose();}},60000);
 test('legacy task-06 backup preserved while lessons 09/10 can be added',async()=>{const store=new LearningStore({getItem:()=>null,setItem:()=>{}}),raw=readFileSync('evidence/task-06/browser-qa-policy.json','utf8'),old=JSON.parse(raw),parsed=store.parseImport(raw);expect(parsed.progress).toEqual(old.progress);expect(parsed.runs).toEqual(old.runs);store.lesson('09').reflection='New ungraded reflection';await store.replace(parsed);expect(store.lesson('09').reflection).toBe('New ungraded reflection');});
});
