import {TrainingCoordinator} from '../../src/training/coordinator.js';
import {rawTrainingTable} from '../../src/laboratory/view.js';
import {describe,it,expect} from 'vitest';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {createHash,webcrypto} from 'node:crypto';
import {lecturePreset,readLecture,saveLecture,memoryStorage,LECTURE_KEY} from '../../src/app/lecture.js';
import {LearningStore} from '../../src/persistence/learning-store.js';
import {LaboratoryStore} from '../../src/laboratory/store.js';
import {newArtifact} from '../../src/laboratory/records.js';
import {TrainingRun} from '../../src/training/run.js';
import {hashData} from '../../src/training/config.js';
import {defaultConfig} from '../../src/training/config.js';
import {isTrainingActive,setTrainingActive} from '../../src/app/activity.js';
function harness({scope='/rl-island/',bad=false,quota=false}={}){const blobs=new Map([['/rl-island/index.html','<html>Local course</html>'],['/rl-island/assets/lazy-neural.js','export const neural=true;']]),entries=[...blobs].map(([url,body])=>({url,bytes:body.length,sha256:createHash('sha256').update(body).digest('hex')})),manifest={schemaVersion:1,base:'/rl-island/',version:'qa1',entries},data=new Map(),events={},messages=[],clients=[{id:'app',url:'https://qa.invalid/rl-island/#/lesson/01',postMessage:m=>messages.push(m)},{id:'root',url:'https://qa.invalid/',postMessage:()=>{throw Error('Root messaging forbidden');}}];let activated=0,claimed=0;const caches={keys:async()=>[...data.keys()],delete:async n=>data.delete(n),open:async n=>{if(!data.has(n))data.set(n,new Map());const rows=data.get(n);return {match:async url=>rows.get(url)?.clone(),put:async(url,response)=>{if(quota)throw Error('QuotaExceededError');rows.set(url,response.clone());}};}};const self={location:{origin:'https://qa.invalid'},registration:{scope:'https://qa.invalid'+scope},clients:{matchAll:async()=>clients,claim:async()=>{claimed++;}},skipWaiting:async()=>{activated++;},addEventListener:(name,fn)=>events[name]=fn};const source=readFileSync('src/offline/service-worker.js','utf8').replace('/*__MANIFEST__*/null',JSON.stringify(manifest));vm.runInNewContext(source,{self,caches,URL,Response,crypto:webcrypto,fetch:async url=>new Response(bad?'changed':blobs.get(typeof url==='string'?url:new URL(url.url).pathname)??'network')});const event=async(name,extra={})=>{let job;events[name]({waitUntil:p=>{job=p;},...extra});await job;};const message=async(type,extra={})=>{let result;await event('message',{source:clients[0],data:{type,version:'qa1',...extra},ports:[{postMessage:m=>{result=m;}}]});return result;};return {event,message,data,events,messages,clients,counts:()=>({activated,claimed})};}
describe('projection isolation and reproducible configurations',()=>{
 it('uses only a versioned presentation preference, leaving personal keys intact',()=>{const s=memoryStorage();s.setItem('private-notes','secret');expect(readLecture(s)).toBe(false);saveLecture(s,true);expect(readLecture(s)).toBe(true);expect(s.getItem('private-notes')).toBe('secret');s.setItem(LECTURE_KEY,'{"schemaVersion":9,"lecture":true}');expect(readLecture(s)).toBe(false);});
 it('reports denied presentation storage without changing defaults',()=>{const s={getItem:()=>{throw Error('denied');},setItem:()=>{throw Error('quota');}};expect(readLecture(s)).toBe(false);expect(saveLecture(s,true)).toContain('could not');});
 for(const id of ['deterministic','slippery','planning','features'])it(id+' preserves exact seeded numerical behavior',()=>{const a=new TrainingRun(lecturePreset(id,29)),b=new TrainingRun(lecturePreset(id,29));for(let i=0;i<90;i++){a.step();b.step();}expect(a.checkpoint()).toEqual(b.checkpoint());a.dispose();b.dispose();});
 it('rejects unknown or invalid preset seeds',()=>{expect(()=>lecturePreset('unknown',11)).toThrow();expect(()=>lecturePreset('planning',-1)).toThrow();});
 it('keeps lecture models and records entirely separate from student storage',async()=>{const privateStorage=memoryStorage(),lectureStorage=memoryStorage();privateStorage.setItem('rl-island:model-free-progress:v1','private fixture');const learning=new LearningStore(lectureStorage,{memoryOnly:true}),archive=new LaboratoryStore(lectureStorage,null,true),r=new TrainingRun(defaultConfig('04'));r.step();await learning.putRun('lecture-agent',r.checkpoint());await learning.save('04');const artifact=newArtifact(lecturePreset('planning'));await archive.put(artifact);expect(await archive.all()).toEqual([artifact]);expect(hashData(await learning.getRun('lecture-agent'))).toBe(hashData(r.checkpoint()));expect(privateStorage.getItem('rl-island:model-free-progress:v1')).toBe('private fixture');expect(learning.database).toBeNull();expect(archive.database).toBeNull();r.dispose();});
 it('activity guard tracks all jobs and releases disposed owners',()=>{const a={},b={};setTrainingActive(a,true);setTrainingActive(b,true);setTrainingActive(a,false);expect(isTrainingActive()).toBe(true);setTrainingActive(b,false);expect(isTrainingActive()).toBe(false);});
});
describe('scoped complete-course offline worker',()=>{
 it('verifies and caches the lazy module before marking readiness; never auto-activates an update',async()=>{const h=harness();await h.event('install');expect((await h.message('STATUS')).status).toBe('ready');expect(h.data.values().next().value.has('/rl-island/assets/lazy-neural.js')).toBe(true);expect(h.counts().activated).toBe(0);await h.message('ACTIVATE');expect(h.counts().activated).toBe(1);});
 it('rejects a root-scoped registration',async()=>{const h=harness({scope:'/'});await expect(h.event('install')).rejects.toThrow('Unsafe');expect(h.data.size).toBe(0);});
 for(const options of [{bad:true},{quota:true}])it('does not claim readiness after '+JSON.stringify(options),async()=>{const h=harness(options);await expect(h.event('install')).rejects.toThrow();expect(h.messages.some(m=>m.status==='failed')).toBe(true);expect((await h.message('STATUS')).status).toBe('incomplete');});
 it('detects partial eviction of the lazy module',async()=>{const h=harness();await h.event('install');h.data.values().next().value.delete('/rl-island/assets/lazy-neural.js');expect((await h.message('STATUS')).status).toBe('incomplete');await h.message('ACTIVATE');expect(h.counts().activated).toBe(0);await h.message('REPAIR');expect((await h.message('STATUS')).status).toBe('ready');});
 it('does not intercept ACML root, external PDFs, POST or unrelated files',async()=>{const h=harness();await h.event('install');for(const [url,method]of [['https://qa.invalid/','GET'],['https://course.invalid/deck.pdf','GET'],['https://qa.invalid/rl-island/notes.json','GET'],['https://qa.invalid/rl-island/index.html','POST']]){let intercepted=false;h.events.fetch({request:{url,method,mode:'navigate'},respondWith:()=>{intercepted=true;}});expect(intercepted).toBe(false);}});
 it('returns the cached local document offline',async()=>{const h=harness();await h.event('install');let response;h.events.fetch({request:{url:'https://qa.invalid/rl-island/#/lesson/11',method:'GET',mode:'navigate'},respondWith:p=>{response=p;}});expect(await (await response).text()).toContain('Local course');});
 it('keeps old caches for other tabs and never deletes unrelated host caches',async()=>{const h=harness();await h.event('install');h.data.set('host-cache',new Map());h.data.set('rl-island:/rl-island/:course:v1-old',new Map());h.clients.push({id:'older',url:'https://qa.invalid/rl-island/',postMessage:()=>{}});await h.message('PRUNE');expect(h.data.has('rl-island:/rl-island/:course:v1-old')).toBe(true);h.clients.pop();await h.message('PRUNE');expect(h.data.has('rl-island:/rl-island/:course:v1-old')).toBe(false);expect(h.data.has('host-cache')).toBe(true);});
});

describe('bounded raw table rendering',()=>{it('pages genuine rows without changing or hiding export data',()=>{const r=new TrainingRun({...lecturePreset('deterministic'),rolloutLimit:1});for(let i=0;i<1900;i++)r.step();const rows=r.checkpoint().rows,before=JSON.stringify(rows);const first=rawTrainingTable(rows,0),last=rawTrainingTable(rows,18);expect((first.match(/<tr>/g)??[])).toHaveLength(101);expect(first).toContain('1–100 of 1900');expect(last).toContain('1801–1900 of 1900');expect(last).toContain('data-raw-page="19" disabled');expect(JSON.stringify(rows)).toBe(before);r.dispose();});});

it('a command queued after disposal cannot leave presentation/update guards busy',async()=>{const coordinator=new TrainingCoordinator(()=>{},{addEventListener:()=>{},terminate:()=>{},postMessage:()=>{}});coordinator.dispose();await expect(coordinator.command('train',{episodes:1})).rejects.toThrow('disposed');expect(isTrainingActive()).toBe(false);});
