import {describe,it,expect} from 'vitest';
import {DemonstrationRecorder,emptyDataset,pairs,validateDataset,exportDataset,importDataset,nextTrajectoryId} from '../../src/imitation/demonstrations.js';
import {BehaviorCloner,initializePolicy,supervisedMetrics} from '../../src/imitation/cloning.js';
import {evaluateImitation,newImitationComparison,runImitationComparison,imitationWinner} from '../../src/imitation/experiment.js';
import {validateImitation,imitationRequirements,imitationCheck} from '../../src/imitation/records.js';
import {TrainingRun,validateRunCheckpoint} from '../../src/training/run.js';
import {defaultConfig,hashData} from '../../src/training/config.js';
import {softmax} from '../../src/agents/policy.js';
import {emptyLearningRecord} from '../../src/lessons/learning-records.js';
import {LearningStore,validateLearningProgress} from '../../src/persistence/learning-store.js';
import {readFileSync} from 'node:fs';
const trajectory=(split,actions,seed=11,id=1)=>{const r=new DemonstrationRecorder(split,seed,id);for(const a of actions)r.act(a);r.stop();return r.trajectory;};
const dataset=()=>({...emptyDataset(),trajectories:[trajectory('train',['right','right','up']),trajectory('holdout',['right','right'],12,2)]});
const fitted=(d=dataset(),epochs=120)=>{const b=new BehaviorCloner(d,epochs);while(!b.done)b.step();return b.result();};
const alter=(text,f)=>{const e=JSON.parse(text);f(e.dataset);e.digest=hashData(e.dataset);return JSON.stringify(e);};
class LocalCoordinator{async initialize(config,c){this.run=TrainingRun.restore(c);}async command(name,payload){expect(name).toBe('trainInteractions');for(let i=0;i<payload.interactions;i++)this.run.step();return {event:'completed',snapshot:this.run.snapshot()};}}

describe('manual demonstrations and bounded data',()=>{
 it('aligns labels with pre-action observations, not successors',()=>{const d=dataset(),t=d.trajectories[0];expect(t.traces.map(x=>[x.observation.x,x.observation.y,x.action,x.nextObservation.x,x.nextObservation.y])).toEqual([[0,1,'right',1,1],[1,1,'right',2,1],[2,1,'up',2,0]]);expect(pairs(d,'train')).toEqual([{state:'0,1',action:1},{state:'1,1',action:1},{state:'2,1',action:0}]);expect(t.end).toBe('terminated');expect(()=>new DemonstrationRecorder('train',11,1,t).act('up')).toThrow();});
 it('records collisions and true termination separately from capped or stopped recordings',()=>{const r=new DemonstrationRecorder('train',2,1);const t=r.act('left');expect(t.collision).toBe(true);expect(t.state).toEqual(t.nextState);for(let i=1;i<80;i++)r.act('left');expect(r.trajectory.end).toBe('truncated');expect(r.trajectory.traces.at(-1).terminated).toBe(false);expect(trajectory('train',['right']).end).toBe('stopped');});
 it('resumes an active demonstration with exact environment randomness',()=>{const a=new DemonstrationRecorder('train',9,1);a.act('right');const b=new DemonstrationRecorder('train',9,1,a.trajectory);expect(b.act('up')).toEqual(a.act('up'));});
 it('continues recording with bounded unique IDs after a high-ID import',()=>{const d=dataset();d.trajectories[0].id=10000;d.trajectories[1].id=7;const imported=importDataset(exportDataset(d));const id=nextTrajectoryId(imported);expect(id).toBe(1);imported.trajectories.push(trajectory('train',['right'],13,id));expect(()=>validateDataset(imported)).not.toThrow();});
 it('round trips the complete dataset without losing held-out labels',()=>{const d=dataset();expect(importDataset(exportDataset(d))).toEqual(d);});
 it.each(['observation','state','nextState'])('rejects misaligned %s even with a recomputed checksum',field=>{expect(()=>importDataset(alter(exportDataset(dataset()),d=>{d.trajectories[0].traces[0][field].x=2;}))).toThrow(/alignment/);});
 it('rejects relabeling the held-out start as training',()=>expect(()=>importDataset(alter(exportDataset(dataset()),d=>{d.trajectories[1].split='train';}))).toThrow(/alignment/));
 it('rejects a false terminal marker, duplicate IDs, unknown schema and excessive data',()=>{const d=dataset();d.trajectories[0]=trajectory('train',['right']);d.trajectories[0].end='terminated';expect(()=>validateDataset(d)).toThrow();const copy=dataset();copy.trajectories[1].id=1;expect(()=>validateDataset(copy)).toThrow(/Duplicate/);expect(()=>importDataset(exportDataset(dataset()).replace('"schemaVersion":1','"schemaVersion":2'))).toThrow();expect(()=>importDataset(' '.repeat(1500001))).toThrow();});
 it('rejects prototype keys and incompatible action order',()=>{expect(()=>importDataset('{"__proto__":{}}')).toThrow();expect(()=>importDataset(alter(exportDataset(dataset()),d=>{d.actions.reverse();}))).toThrow();});
});
describe('genuine behavior cloning',()=>{
 it('matches the one-example cross-entropy step exactly',()=>{const d=dataset();d.trajectories[0]=trajectory('train',['right']);const b=new BehaviorCloner(d,1,.5);expect(b.metrics().train.loss).toBeCloseTo(Math.log(4),14);b.step();expect(b.actor['0,1']).toEqual([-.125,.375,-.125,-.125]);expect(softmax(b.actor['0,1'])[1]).toBeCloseTo(.3546612444,9);expect(b.metrics().train.loss).toBeCloseTo(1.0365921862,9);});
 it('reduces actual supervised loss and learns labels',()=>{const f=fitted();expect(f.history.at(-1).train.loss).toBeLessThan(.1);expect(f.history.at(-1).train.accuracy).toBe(1);expect(f.examplePasses).toBe(360);expect(f.actor['0,0']).toBeUndefined();expect(f.history.at(-1).holdout.loss).toBeCloseTo(Math.log(4));});
 it('matches the averaged gradient with central finite differences',()=>{const d=dataset(),b=new BehaviorCloner(d,1,.5);b.actor={'0,1':[.2,-.1,.3,.4]};const before=structuredClone(b.actor);b.step();for(let i=0;i<4;i++){const plus=structuredClone(before),minus=structuredClone(before);plus['0,1'][i]+=1e-5;minus['0,1'][i]-=1e-5;const numerical=(supervisedMetrics(plus,b.train).loss-supervisedMetrics(minus,b.train).loss)/2e-5;expect((b.actor['0,1'][i]-before['0,1'][i])/.5).toBeCloseTo(-numerical,9);}});
 it('never trains on held-out labels or uses them for stopping',()=>{const a=dataset(),b=dataset();b.trajectories[1]=trajectory('holdout',['left','down','right','up','right'],12,2);const fa=fitted(a),fb=fitted(b);expect(fa.actor).toEqual(fb.actor);expect(fa.history.map(x=>x.train)).toEqual(fb.history.map(x=>x.train));expect(fa.history.at(-1).holdout).not.toEqual(fb.history.at(-1).holdout);});
 it('requires both splits, rejects active recording and bounds computation',()=>{const d=dataset();d.trajectories.pop();expect(()=>new BehaviorCloner(d)).toThrow(/separate/);d.trajectories.push(new DemonstrationRecorder('holdout',4,2).trajectory);expect(()=>new BehaviorCloner(d)).toThrow(/active/);expect(()=>new BehaviorCloner(dataset(),301)).toThrow();});
 it('copies compatible preferences only and resets critic and RL counters',()=>{const f=fitted(),c=initializePolicy(f);expect(c.parameters.actor).toEqual(f.actor);expect(c.parameters.v).toEqual({});expect(c.parameters.visits).toEqual({});expect(c.parameters.updates).toBe(0);expect(c.interactions).toBe(0);validateRunCheckpoint(c);const run=TrainingRun.restore(c);run.step();expect(run.learner.parameters.updates).toBe(1);expect(f.actor).toEqual(c.parameters.actor);expect(()=>initializePolicy(f,{...defaultConfig('11'),algorithm:'q'})).toThrow();expect(()=>initializePolicy({...f,representation:'neural-vector'})).toThrow();});
});
describe('frozen behavior and explicit budgets',()=>{
 it('evaluation leaves parameters and counters untouched and exposes unseen-state behavior',()=>{const d=dataset(),c=initializePolicy(fitted(d)),before=hashData(c),r=evaluateImitation(c.parameters,d,'holdout',[701,709]);expect(hashData(c)).toBe(before);expect(r.trainingUpdates).toBe(0);expect(r.trace[0].unseen).toBe(true);expect(r.trace[0].decision.probabilities).toEqual([.25,.25,.25,.25]);expect(r.trace[0].transition.state).toEqual({x:0,y:0});expect(r.rows[0].unseenVisits).toBeGreaterThan(0);expect(r.rows.every(x=>x.terminated||x.truncated)).toBe(true);});
 it('is seeded, separate from fitting, and does not relabel accuracy as success',()=>{const d=dataset(),p=initializePolicy(fitted(d)).parameters;expect(evaluateImitation(p,d,'holdout',[701])).toEqual(evaluateImitation(p,d,'holdout',[701]));expect(evaluateImitation(p,d,'train',[701]).scenarioHash).not.toBe(evaluateImitation(p,d,'holdout',[701]).scenarioHash);});
 it('uses exactly equal new real interactions and records all additional imitation cost',async()=>{const d=dataset(),f=fitted(d),c=newImitationComparison(d,f,60,'QA prediction');await runImitationComparison(new LocalCoordinator(),c,d,f,()=>false,()=>{});expect(c.status).toBe('complete');expect(c.runs).toHaveLength(10);expect(c.runs.every(r=>r.checkpoint.interactions===60&&r.checkpoint.parameters.updates===60&&r.familiar.trainingUpdates===0&&r.novel.trainingUpdates===0)).toBe(true);expect(c.demonstrationActions).toBe(3);expect(c.supervisedPasses).toBe(360);expect(['scratch','initialized','tie']).toContain(imitationWinner(c));validateImitation({active:0,sessions:[{dataset:d,fit:f,comparison:c}]});});
 it('retains cancelled status and excludes incomplete replicates',async()=>{const d=dataset(),f=fitted(d),c=newImitationComparison(d,f,60,'QA');await expect(runImitationComparison(new LocalCoordinator(),c,d,f,()=>true,()=>{})).rejects.toThrow(/cancelled/);expect(c.status).toBe('cancelled');expect(c.runs).toHaveLength(0);});
});
describe('activity progress and safe persistence',()=>{
 it('stage navigation alone never completes any imitation activity',()=>{const r=emptyLearningRecord();r.stage=5;expect(imitationRequirements(r).some(x=>x.done)).toBe(false);});
 it('validates fit arithmetic and rejects fabricated fitting history',()=>{const s={dataset:dataset(),fit:fitted(),comparison:null};validateImitation({active:0,sessions:[s]});s.fit.actor['0,1'][0]+=1;expect(()=>validateImitation({active:0,sessions:[s]})).toThrow(/fit differs/);});
 it('rejects numeric-key objects masquerading as saved arrays',()=>{for(const field of ['history','actor']){const s={dataset:dataset(),fit:fitted(),comparison:null};if(field==='history')s.fit.history=Object.fromEntries(s.fit.history.map((v,i)=>[i,v]));else s.fit.actor['0,1']=Object.fromEntries(s.fit.actor['0,1'].map((v,i)=>[i,v]));expect(()=>validateImitation({active:0,sessions:[s]})).toThrow(/fit differs/);}});
 it('round trips fitted policies and manual records in the existing additive backup',async()=>{const storage=new Map(),store=new LearningStore({getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)}),r=store.lesson('11');r.prediction={answer:'QA text <img src=x onerror=alert(1)>',at:new Date().toISOString()};r.imitation={active:0,sessions:[{dataset:dataset(),fit:fitted(),comparison:null}]};store.save('11');expect(store.parseImport(await store.export()).progress).toEqual(store.data);expect(new LearningStore(store.storage).data).toEqual(store.data);});
 it('preserves old lessons 04–10 and accepts their task-07 backup without migration',()=>{const store=new LearningStore({getItem:()=>null,setItem:()=>{}});const old=store.parseImport(readFileSync('evidence/task-07/browser-qa-deep.json','utf8'));expect(Object.keys(old.progress.lessons)).toEqual(['10','04','05','06','07','08','09']);expect(old.progress.lessons['11']).toBeUndefined();},15000);
 it('does not allow completion without activity evidence or grade reflections',()=>{const r=emptyLearningRecord();r.stage=5;r.reflection='I know everything';r.completedAt=new Date().toISOString();expect(()=>validateLearningProgress({schemaVersion:1,lastLesson:'11',lessons:{'11':r}})).toThrow(/Completion/);expect(imitationCheck(r,{stage:'challenge',answers:['initialized','Unseen states receive no supervised gradient'],comparisonId:null,at:''})).toBe(false);});
});
