import {tensorMemory} from '../../src/agents/deep/learner.js';
import {describe,it,expect} from 'vitest';
import {laboratoryConfig,reachableGoal,taskSize,validateTrack} from '../../src/laboratory/config.js';
import {TrainingRun,validateRunCheckpoint} from '../../src/training/run.js';
import {FrozenEvaluation,evaluationSeeds} from '../../src/evaluation/frozen.js';
import {newArtifact,newComparison,runComparison,validateArtifact,transferCheckpoint,challengePass,statistics} from '../../src/laboratory/records.js';
import {exportArchive,importArchive,exportCsv,LaboratoryStore,ARCHIVE_KEY} from '../../src/laboratory/store.js';
import {hashData,validateConfig} from '../../src/training/config.js';
import {WorkerHost} from '../../src/training/worker-host.js';
import {prepareLearner} from '../../src/agents/registry.js';
const advance=(run,n)=>{for(let i=0;i<n;i++)run.step();return run.checkpoint();};
function evaluated(config,parameters){const e=new FrozenEvaluation(config,parameters,evaluationSeeds(7001));while(!e.done)e.step();const result=e.result();e.dispose();return result;}
function worker(){let host,queue,messages,id,config;return {initialize:async(c,checkpoint)=>{host?.run?.dispose();config=c;queue=[];messages=[];id=0;await prepareLearner(c);host=new WorkerHost(m=>messages.push(m),{schedule:f=>queue.push(f),now:()=>0});host.handle({protocol:1,runId:'laboratory-test',configHash:hashData(c),commandId:++id,command:'initialize',payload:{config:c,...(checkpoint?{checkpoint}:{})}});if(messages.at(-1)?.error)throw Error(messages.at(-1).error);return messages.at(-1);},command:async(command,payload={})=>{host.handle({protocol:1,runId:'laboratory-test',configHash:hashData(config),commandId:++id,command,payload});let count=0;while(queue.length){queue.shift()();if(++count>20000)throw Error('Queue bound');}const result=messages.at(-1);if(result.error)throw Error(result.error);return result;},dispose:()=>host?.run?.dispose()};}
const memory=()=>{const m=new Map();return {m,getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};};
describe('bounded map and learner contracts',()=>{
 it('round trips a user map, rewards and state choices through the canonical engine config',()=>{const c=laboratoryConfig();c.scenario.grid=['.CG','...'];c.scenario.start={x:0,y:1};c.scenario.features={collectibles:true,battery:12,horizon:15};c.scenario.rewards.hazard=-2;expect(validateConfig(JSON.parse(JSON.stringify(c)))).toEqual(c);expect(taskSize(c.scenario).states).toBe(2496n);});
 it('rejects invalid shape, rewards and oversized combinatorial state before training',()=>{for(const modify of [c=>c.scenario.grid=['.G','...'],c=>c.scenario.rewards.goal=101,c=>c.scenario.features={collectibles:false,battery:10000,horizon:10000},c=>c.scenario.grid=['.'.repeat(13),'G'.repeat(13)]]){const c=laboratoryConfig();modify(c);expect(()=>validateConfig(c)).toThrow();}});
 it('requires explicit intent for unreachable goals',()=>{const c=laboratoryConfig();c.scenario.grid=['G#..','####','....'];expect(reachableGoal(c.scenario)).toBe(false);expect(()=>validateConfig(c)).toThrow(/No geometric path/);c.allowUnreachable=true;expect(validateConfig(c)).toEqual(c);});
 it('rejects deterministic-model use with slip and prediction methods in a control comparison',()=>{const c=laboratoryConfig('dyna');c.scenario.slip=.2;expect(()=>validateConfig(c)).toThrow(/deterministic/);expect(()=>newComparison([laboratoryConfig('q'),laboratoryConfig('td')],[1,2],60)).toThrow(/Prediction/);});
 for(const method of ['q','sarsa','td','mc','actor-critic'])it(method+' uses observation keys without leaking hidden inventory and saves exactly',()=>{const c=laboratoryConfig(method);c.scenario.grid=['.CG','...'];c.scenario.start={x:0,y:1};c.scenario.features.collectibles=true;c.scenario.observation='position';const r=new TrainingRun(c);advance(r,90);expect(Object.keys(r.learner.parameters.visits).some(k=>k.includes('|'))).toBe(false);const cp=r.checkpoint();validateRunCheckpoint(cp);const restored=TrainingRun.restore(cp);expect(advance(restored,20)).toEqual(advance(r,20));r.dispose();restored.dispose();});
 it('rejects partial dynamic inputs for linear, Dyna and neural implementations',()=>{for(const method of ['linear-sarsa','dyna','dqn']){const c=laboratoryConfig(method);c.scenario.features.battery=4;c.scenario.observation='position';expect(()=>validateConfig(c)).toThrow();}});
 for(const feature of ['battery','horizon'])it(feature+' is real termination without falsely reporting goal success',()=>{const c=laboratoryConfig();c.scenario.features[feature]=1;const r=new TrainingRun(c);advance(r,4);expect(r.rows.every(x=>x.terminated&&!x.success&&!x.truncated)).toBe(true);validateRunCheckpoint(r.checkpoint());const a=newArtifact(c);a.checkpoint=r.checkpoint();a.evaluations=[{result:evaluated(c,a.checkpoint.parameters),interactions:r.interactions,updates:r.learner.parameters.updates,wallMs:1}];expect(a.evaluations[0].result.rows.every(x=>!x.success&&x.terminated)).toBe(true);validateArtifact(a);r.dispose();});
 it('linear and Dyna full-state dynamic maps keep meaningful state variables',()=>{for(const method of ['linear-sarsa','dyna']){const c=laboratoryConfig(method);c.scenario.grid=['.CG','...'];c.scenario.start={x:0,y:1};c.scenario.features.collectibles=true;const r=new TrainingRun(c);advance(r,80);validateRunCheckpoint(r.checkpoint());expect(Object.keys(r.learner.parameters.visits).some(k=>k.includes('|c='))).toBe(true);r.dispose();}});
 it('supports bounded custom-map DQN through the CPU learner and disposes tensors',async()=>{const baseline=tensorMemory();const c=laboratoryConfig('dqn');await prepareLearner(c);const r=new TrainingRun(c);advance(r,20);validateRunCheckpoint(r.checkpoint());expect(r.learner.parameters.updates).toBe(5);r.dispose();expect(tensorMemory()).toEqual(baseline);},15000);
});
describe('independent comparison, budgets and frozen evidence',()=>{
 for(const cancelAtBoundary of [false,true])it('pauses at the training/evaluation boundary and '+(cancelAtBoundary?'cancels without new work':'resumes exact budgets'),async()=>{
  const c=newComparison([laboratoryConfig('q'),laboratoryConfig('sarsa')],[11,29],60),w=worker();let cancelled=false,release,arrived,gates=0;
  const held=new Promise(r=>{release=r;}),reached=new Promise(r=>{arrived=r;}),commands=[],original=w.command;
  w.command=async(command,payload)=>{commands.push(command);return original(command,payload);};
  const running=runComparison(w,c,()=>cancelled,()=>{},async()=>{if(++gates===3){arrived();await held;}});
  await reached;expect(commands).toEqual(['trainInteractions']);expect(c.runs[0].checkpoint.interactions).toBe(20);expect(c.runs[0].curve).toEqual([]);
  await Promise.resolve();expect(commands).toEqual(['trainInteractions']);cancelled=cancelAtBoundary;release();await running;
  if(cancelAtBoundary){expect(commands).toEqual(['trainInteractions']);expect(c.status).toBe('cancelled');expect(c.runs.every(r=>r.status==='cancelled')).toBe(true);}
  else {expect(c.status).toBe('complete');expect(c.runs.every(r=>r.checkpoint.interactions===60&&r.curve.length===3)).toBe(true);}
  w.dispose();
 });
 it('runs every requested method/seed independently and keeps three actual budget checkpoints',async()=>{const configs=['q','sarsa','dyna'].map(m=>laboratoryConfig(m)),c=newComparison(configs,[11,29],90),w=worker();await runComparison(w,c,()=>false,()=>{});w.dispose();expect(c.runs).toHaveLength(6);for(const rep of c.runs){expect(rep.status).toBe('complete');expect(rep.curve.map(p=>p.interactions)).toEqual([30,60,90]);const direct=new TrainingRun({...configs.find(c=>c.algorithm===rep.method),seed:rep.seed});expect(rep.checkpoint).toEqual(advance(direct,90));direct.dispose();}const a=newArtifact(configs[0],'comparison');a.comparison=c;validateArtifact(a);expect(c.runs.filter(r=>r.method==='dyna').every(r=>r.checkpoint.parameters.planningUpdates===450)).toBe(true);},30000);
 it('records a failed replicate without dropping any requested seeds',async()=>{const c=newComparison([laboratoryConfig('q'),laboratoryConfig('sarsa')],[11,29],60),w=worker(),original=w.initialize;w.initialize=async config=>{if(config.seed===29)throw Error('Labeled injected failure');return original(config);};await runComparison(w,c,()=>false,()=>{});expect(c.runs.map(r=>r.status)).toEqual(['complete','failed','complete','failed']);expect(c.status).toBe('complete');const a=newArtifact(c.configs[0],'comparison');a.comparison=c;validateArtifact(a);w.dispose();});
 it('cancellation leaves explicit cancelled slots and no completed-only selection',async()=>{const c=newComparison([laboratoryConfig('q'),laboratoryConfig('sarsa')],[1,2],60),w=worker();await runComparison(w,c,()=>true,()=>{});expect(c.status).toBe('cancelled');expect(c.runs.every(r=>r.status==='cancelled')).toBe(true);w.dispose();});
 it('rejects mixed tasks, duplicate methods/seeds and altered budgets',()=>{const c=laboratoryConfig('sarsa');c.scenario.rewards.step=-.1;expect(()=>newComparison([laboratoryConfig('q'),c],[1,2],60)).toThrow(/same scenario/);expect(()=>newComparison([laboratoryConfig(),laboratoryConfig()],[1,2],60)).toThrow(/distinct/);expect(()=>newComparison([laboratoryConfig(),laboratoryConfig('sarsa')],[1,1],60)).toThrow(/distinct/);});
 it('evaluation leaves parameters, environment and training RNG untouched',()=>{const r=new TrainingRun(laboratoryConfig());advance(r,80);const before=r.checkpoint();evaluated(r.config,r.learner.parameters);expect(r.checkpoint()).toEqual(before);r.dispose();});
 it('computes variability over agent summaries with a sample SD',()=>{expect(statistics([1,2,3])).toEqual({n:3,mean:2,sd:1,min:1,max:3});});
});
describe('expedition tracks and honest challenge',()=>{
 it('rejects coordinate-table new-map transfer for both adaptation and zero-shot',()=>{const c=laboratoryConfig(),target=structuredClone(c);target.scenario.grid=['...G','..#.','....'];for(const track of ['adaptation','zero-shot'])expect(()=>validateTrack(c,target,track)).toThrow(/Coordinate Q-tables/);});
 it('copies only compatible linear weights and resets all target-learning counters',()=>{const c={...laboratoryConfig('linear-sarsa'),representation:'local-goal'},r=new TrainingRun(c),source=advance(r,90),target=structuredClone(c);target.scenario.grid=['...G','..#.','....'];target.seed=7002;const cp=transferCheckpoint(source,target,'adaptation');expect(cp.parameters.weights).toEqual(source.parameters.weights);expect(cp.parameters.visits).toEqual({});expect(cp.parameters.updates).toBe(0);expect(cp.interactions).toBe(0);expect(cp.config.scenario).toEqual(target.scenario);validateRunCheckpoint(cp);r.dispose();});
 it('zero-shot evaluates unchanged weights with zero target-map updates',()=>{const c={...laboratoryConfig('linear-sarsa'),representation:'local-goal'},r=new TrainingRun(c),source=advance(r,90),target=structuredClone(c);target.scenario.grid=['...G','..#.','....'];const cp=transferCheckpoint(source,target,'zero-shot'),a=newArtifact(c,'expedition');a.checkpoint=source;a.expedition={track:'zero-shot',target,budget:0,sourceHash:hashData(source.parameters),checkpoint:cp,result:evaluated(target,cp.parameters),wallMs:1,attempts:[]};validateArtifact(a);expect(cp.parameters.weights).toEqual(source.parameters.weights);expect(cp.interactions).toBe(0);r.dispose();});
 it('rejects incompatible linear dimensions and changed transfer reward semantics',()=>{const c={...laboratoryConfig('linear-sarsa'),representation:'local-goal'},target=structuredClone(c);target.scenario.grid=['...G','....'];target.scenario.start.y=1;expect(()=>validateTrack(c,target,'zero-shot')).toThrow(/identical dimensions/);target.scenario=structuredClone(c.scenario);target.scenario.grid=['...G','..#.','....'];target.scenario.rewards.goal=4;expect(()=>validateTrack(c,target,'adaptation')).toThrow(/rewards/);});
 it('requires real performance, minimum work and concept checks; reflection is ungraded',()=>{const c=laboratoryConfig(),r=new TrainingRun(c),a=newArtifact(c,'expedition');a.prediction='QA prior prediction';a.reflection='I know everything';a.checkpoint=advance(r,600);a.expedition={track:'known',target:c,budget:0,sourceHash:hashData(a.checkpoint.parameters),checkpoint:structuredClone(a.checkpoint),result:evaluated(c,a.checkpoint.parameters),wallMs:1,attempts:[]};const answers=['Learning is frozen','All enabled task variables','Same trained task'];expect(challengePass(a,['bad',...answers.slice(1)])).toBe(false);expect(challengePass(a,answers)).toBe(true);a.expedition.attempts.push({answers,passed:true,at:new Date().toISOString()});validateArtifact(a);a.expedition.result.rows.forEach(r=>r.success=false);expect(()=>validateArtifact(a)).toThrow(/Challenge/);r.dispose();});
});
describe('versioned persistence, imports and storage failures',()=>{
 it('round trips scenario and trained agent artifacts without changing unrelated storage',async()=>{const storage=memory();storage.setItem('acml:unrelated','keep');const store=new LaboratoryStore(storage,null),r=new TrainingRun(laboratoryConfig()),a=newArtifact(r.config);a.checkpoint=advance(r,30);await store.put(a);const imported=importArchive(exportArchive(await store.all()));expect(imported).toEqual([a]);expect(storage.getItem('acml:unrelated')).toBe('keep');expect(JSON.parse(storage.getItem(ARCHIVE_KEY)).records[0]).not.toHaveProperty('checkpoint');expect(store.message).toContain('memory');r.dispose();});
 it('returns independent summaries and checkpoints without cloning unrelated archive data',async()=>{const store=new LaboratoryStore(memory(),null,true),a=newArtifact(laboratoryConfig()),b=newArtifact(laboratoryConfig());b.title='Another experiment';await store.import([a,b]);const list=await store.summaries();expect(list).toEqual([a,b].map(({id,title,kind,updatedAt})=>({id,title,kind,updatedAt})));list[0].title='Mutated summary';const copy=await store.get(a.id);copy.title='Mutated checkpoint';expect((await store.get(a.id)).title).toBe(a.title);expect(await store.get('missing')).toBeUndefined();expect(await store.all()).toEqual([a,b]);});
 it('reports unavailable and quota-failing localStorage and IndexedDB without losing memory exports',async()=>{const store=new LaboratoryStore({getItem:()=>{throw Error('denied');},setItem:()=>{throw Error('QuotaExceeded');}},null),a=newArtifact(laboratoryConfig());await store.put(a);expect(store.message).toContain('memory only');expect(store.message).toContain('index could not');expect(importArchive(exportArchive(await store.all()))).toEqual([a]);});
 it('rejects unsupported versions, duplicate IDs/fields, bad arrays, malformed keys and oversize imports',()=>{const a=newArtifact(laboratoryConfig()),valid=JSON.parse(exportArchive([a]));for(const mutate of [v=>v.schemaVersion=2,v=>v.records.push(a),v=>v.records[0].evaluations={},v=>v.records[0].config.scenario.start.x=Infinity]){const v=structuredClone(valid);mutate(v);v.digest=hashData(v.records);expect(()=>importArchive(JSON.stringify(v))).toThrow();}expect(()=>importArchive('{"format":1,"format":2}')).toThrow(/Duplicate/);const v=structuredClone(valid);v.records[0].__proto__={x:1};v.records[0].unknown='code';v.digest=hashData(v.records);expect(()=>importArchive(JSON.stringify(v))).toThrow();expect(()=>importArchive(' '.repeat(16777217))).toThrow(/size limit/);});
 it('never silently replaces duplicate IDs and leaves records unchanged on rejected import',async()=>{const store=new LaboratoryStore(memory(),null),a=newArtifact(laboratoryConfig());await store.put(a);const changed={...a,title:'Replacement'};await expect(store.import([changed],false)).rejects.toThrow(/explicit replacement/);expect((await store.get(a.id)).title).toBe(a.title);await store.import([changed],true);expect((await store.get(a.id)).title).toBe('Replacement');});
 it('keeps hostile notes as text and escapes CSV spreadsheet formulas',()=>{const a=newArtifact(laboratoryConfig());a.prediction='=HYPERLINK("https://invalid")';a.reflection='<img src=x onerror=alert(1)>';const saved=importArchive(exportArchive([a]))[0];expect(saved.reflection).toBe(a.reflection);expect(exportCsv([a])).toContain("'=HYPERLINK");expect(exportCsv([a])).toContain('ungraded');});
});

// Notebook envelopes preserve the existing lesson formats as validated components.
import {ProgressStore} from '../../src/persistence/progress.js';
import {LearningStore} from '../../src/persistence/learning-store.js';
import {notebookExport,notebookImport,notebookCsv} from '../../src/laboratory/notebook.js';
describe('unified notebook validation',()=>{
 it('round trips supported lesson components and laboratory records in one backup',async()=>{const p=new ProgressStore(memory()),l=new LearningStore(memory()),a=newArtifact(laboratoryConfig());a.prediction='=SUM(1,2)';a.reflection='QA ungraded';const text=await notebookExport(p,l,[a]),v=notebookImport(text,l);expect(v.records).toEqual([a]);expect(v.foundation).toEqual(p.data);expect(v.learning.progress).toEqual(l.data);expect(notebookCsv(text,l)).toContain('validated_raw_json');expect(notebookCsv(text,l)).toContain('QA ungraded');});
 it('rejects unsupported component formats before any records are applied',async()=>{const p=new ProgressStore(memory()),l=new LearningStore(memory()),text=await notebookExport(p,l,[]),v=JSON.parse(text);v.payload.learning.schemaVersion=999;v.digest=hashData(v.payload);expect(()=>notebookImport(JSON.stringify(v),l)).toThrow(/Unsupported/);expect(l.data.lessons).toEqual({});});
 it('records each frozen evaluation budget separately from subsequent training',()=>{const r=new TrainingRun(laboratoryConfig()),a=newArtifact(r.config);advance(r,60);const result=evaluated(r.config,r.learner.parameters);a.evaluations.push({result,interactions:60,updates:r.learner.parameters.updates,wallMs:2});a.checkpoint=advance(r,90);validateArtifact(a);const rows=exportCsv([a]).split('\r\n').filter(x=>x.includes('frozen-evaluation'));expect(rows.every(x=>x.includes(',"60",'))).toBe(true);expect(a.checkpoint.interactions).toBe(150);r.dispose();});
});

import {readFileSync} from 'node:fs';
describe('large legacy progress storage',()=>{
 it('keeps the old localStorage backup if IndexedDB migration fails',async()=>{const storage=memory(),source=JSON.parse(readFileSync('evidence/task-08/browser-qa-imitation.json','utf8'));storage.setItem('rl-island:model-free-progress:v1',JSON.stringify(source.progress));const old=storage.getItem('rl-island:model-free-progress:v1'),store=new LearningStore(storage);await store.ready;await store.save('11');expect(store.large).toBe(true);expect(store.message).toContain('could not be saved');expect(storage.getItem('rl-island:model-free-progress:v1')).toBe(old);expect(store.data.lessons['11']).toEqual(source.progress.lessons['11']);},30000);
 it('protects a versioned pointer when the large progress database is unavailable',async()=>{const storage=memory(),pointer={schemaVersion:2,storage:'indexeddb',recordKey:'lesson-progress'};storage.setItem('rl-island:model-free-progress:v1',JSON.stringify(pointer));const store=new LearningStore(storage);await store.ready;expect(store.blocked).toBe(true);await store.save('04');expect(JSON.parse(storage.getItem('rl-island:model-free-progress:v1'))).toEqual(pointer);expect(store.message).toContain('memory');});
});

import {featureEncoder} from '../../src/agents/features.js';
describe('task-aware local-goal representation',()=>{
 it('encodes the actual goal direction, walls and hazards with a fixed dimension',()=>{const s=laboratoryConfig().scenario,e=featureEncoder(s,'local-goal'),phi=e.encode(s.start).map(x=>x/e.scale);expect(e.dimension).toBe(12);expect(phi.slice(0,4)).toEqual([1,1,-1,1]);expect(phi.slice(4,8)).toEqual([0,0,1,1]);expect(phi.slice(8)).toEqual([0,0,0,0]);});
 it('changes the observation when the local layout or goal changes at the same coordinate',()=>{const s=laboratoryConfig().scenario,t=structuredClone(s);t.grid=['G...','.#..','...H'];const a=featureEncoder(s,'local-goal').encode({x:2,y:2}),b=featureEncoder(t,'local-goal').encode({x:2,y:2});expect(a).not.toEqual(b);expect(a).toHaveLength(b.length);});
 it('rejects plain coordinate linear weights and dynamic hidden features for transfer',()=>{const c=laboratoryConfig('linear-sarsa'),t=structuredClone(c);t.scenario.grid=['...G','..#.','....'];expect(()=>validateTrack(c,t,'zero-shot')).toThrow(/local-goal/);c.representation='local-goal';c.scenario.features.battery=10;expect(()=>validateConfig(c)).toThrow(/static/);});
});

import {defaultConfig} from '../../src/training/config.js';
it('escapes formula-prefixed legacy agent IDs in the combined Notebook CSV',async()=>{const p=new ProgressStore(memory()),l=new LearningStore(memory()),r=l.lesson('04'),id='=QA(1)',run=new TrainingRun(defaultConfig('04'));r.runIds=[id];r.activeRunId=id;l.memory.set(id,run.checkpoint());const text=await notebookExport(p,l,[]);expect(notebookCsv(text,l)).toContain('"\'=QA(1)"');run.dispose();});

it("reports unavailable legacy agents in a partial backup without dropping activity records",async()=>{const l=new LearningStore(memory()),r=l.lesson("04");r.runIds=["missing-model"];r.activeRunId="missing-model";l.getRun=async()=>undefined;const text=await l.export(),backup=l.parseImport(text);expect(backup.progress.lessons["04"].runIds).toEqual(["missing-model"]);expect(backup.runs).toEqual({});expect(l.message).toContain("Incomplete agent backup");expect(l.message).toContain("missing-model");});
