import {describe,test,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {softmax,scoreGradient,samplePolicy,PolicyLearner,policyDecision} from '../../src/agents/policy.js';
import {createRng} from '../../src/environment/rng.js';
import {defaultConfig,hashData} from '../../src/training/config.js';
import {TrainingRun,validateRunCheckpoint} from '../../src/training/run.js';
import {FrozenEvaluation,evaluationSeeds} from '../../src/evaluation/frozen.js';
import {WorkerHost} from '../../src/training/worker-host.js';
import {newComparison,runComparison,comparisonSummary} from '../../src/evaluation/comparison.js';
import {validateComparison} from '../../src/evaluation/comparison-validation.js';
import {LearningStore} from '../../src/persistence/learning-store.js';
const config=(algorithm='reinforce-baseline')=>({...defaultConfig('08'),algorithm});
const advance=(r,n)=>{for(let i=0;i<n;i++)r.step();return r;};
const sample=(extra={})=>({state:'0,1',action:1,reward:1,next:'1,1',terminated:false,truncated:false,policy:{probabilities:[.25,.25,.25,.25],baseline:.5,time:1},...extra});
function harness(c){const queue=[],messages=[];let id=0,t=0;const host=new WorkerHost(m=>messages.push(m),{schedule:f=>queue.push(f),now:()=>t+=.1});const request=(command,payload={})=>host.handle({protocol:1,runId:'policy-fixture',configHash:hashData(c),commandId:++id,command,payload});const drain=()=>{let n=0;while(queue.length){queue.shift()();if(++n>50000)throw Error('Unbounded worker');}if(messages.at(-1)?.error)throw Error(messages.at(-1).error);};request('initialize',{config:c});return {host,queue,messages,request,drain};}
function worker(){let h;return {initialize:async c=>{h=harness(c);return h.messages.at(-1);},command:async(command,payload)=>{h.request(command,payload);h.drain();return h.messages.at(-1);}};}
describe('stable categorical policy and genuine score gradients',()=>{
 test('normalizes large logits, is translation invariant, rejects nonfinite input',()=>{for(const xs of [[0,0,0,0],[10000,9999,-10000,0],[-1e308,1e308,1e308,-1e308]]){const p=softmax(xs);expect(p.every(Number.isFinite)).toBe(true);expect(p.reduce((a,b)=>a+b,0)).toBeCloseTo(1,15);}expect(softmax([1000,1001,1002,1003])).toEqual(softmax([0,1,2,3]));expect(()=>softmax([NaN])).toThrow();expect(()=>softmax([])).toThrow();});
 test('CDF boundaries skip zero mass and samples match the declared distribution',()=>{expect(samplePolicy([0,.25,.5,.25],0)).toBe(1);expect(samplePolicy([0,.25,.5,.25],.25)).toBe(2);expect(samplePolicy([0,.25,.5,.25],.75)).toBe(3);expect(()=>samplePolicy([.2,.2],.5)).toThrow();expect(()=>samplePolicy([1,0],1)).toThrow();const p=softmax([-.4,.7,1.2,-2]),rng=createRng(99),counts=[0,0,0,0];for(let i=0;i<20000;i++)counts[samplePolicy(p,rng.next())]++;counts.forEach((n,i)=>expect(Math.abs(n/20000-p[i])).toBeLessThan(.015));});
 test.each([0,1,2,3])('log probability gradient for action %i matches central finite differences',a=>{const theta=[-.7,.8,1.1,-.2],eps=1e-6,g=scoreGradient(softmax(theta),a);theta.forEach((_,i)=>{const plus=[...theta],minus=[...theta];plus[i]+=eps;minus[i]-=eps;expect(g[i]).toBeCloseTo((Math.log(softmax(plus)[a])-Math.log(softmax(minus)[a]))/(2*eps),8);});expect(g.reduce((s,x)=>s+x,0)).toBeCloseTo(0,14);});
 test('two-step discounted objective gradient includes outer gamma^t; baseline has zero expected score contribution',()=>{
  const theta=[.2,-.4,.7,0,-.3,.2,.1,.8],r0=[1,-2,0,3],r1=[-1,4,2,0],gamma=.6;
  const objective=x=>{const p=softmax(x.slice(0,4)),q=softmax(x.slice(4));return p.reduce((sum,pa,a)=>sum+q.reduce((v,qb,b)=>v+pa*qb*(r0[a]+gamma*r1[b]),0),0);};
  const p=softmax(theta.slice(0,4)),q=softmax(theta.slice(4)),gradient=Array(8).fill(0);
  for(let a=0;a<4;a++)for(let b=0;b<4;b++){const mass=p[a]*q[b];scoreGradient(p,a).forEach((g,i)=>gradient[i]+=mass*(r0[a]+gamma*r1[b]-2.7)*g);scoreGradient(q,b).forEach((g,i)=>gradient[4+i]+=mass*gamma*(r1[b]+1.3)*g);}
  theta.forEach((_,i)=>{const plus=[...theta],minus=[...theta];plus[i]+=1e-6;minus[i]-=1e-6;expect(gradient[i]).toBeCloseTo((objective(plus)-objective(minus))/2e-6,8);});
 });
});
describe('policy numerical updates and terminal conventions',()=>{
 test('REINFORCE hand fixture changes preferences, not Q; chosen probability becomes .289335756',()=>{const l=new PolicyLearner({...config('reinforce'),alpha:.1}),s=sample({reward:2,terminated:true,policy:{probabilities:[.25,.25,.25,.25],baseline:0,time:0}});expect(l.observe(s)).toEqual([]);const [u]=l.endEpisode([s],true);u.policy.preferencesAfter.forEach((v,i)=>expect(v).toBeCloseTo([-.05,.15,-.05,-.05][i],14));expect(softmax(l.parameters.actor[s.state])[1]).toBeCloseTo(.2893357559401649,14);expect(l.parameters.q).toEqual({});expect(l.parameters.v).toEqual({});expect(l.parameters.criticUpdates).toBe(0);});
 test('actor-critic hand fixture: delta .86, V .586, right preference change .05805 at t=1',()=>{const l=new PolicyLearner({...config('actor-critic'),alpha:.1});l.parameters.v={'0,1':.5,'1,1':.4};const [u]=l.observe(sample());expect(u.error).toBeCloseTo(.86,14);expect(u.next).toBeCloseTo(.586,14);expect(u.policy.preferencesAfter[1]).toBeCloseTo(.05805,14);expect(l.parameters.updates).toBe(1);expect(l.parameters.criticUpdates).toBe(1);});
 test('episodic baseline and actor use frozen collection-time values and sum all contributions',()=>{const l=new PolicyLearner({...config(),alpha:.1}),a=sample({policy:{probabilities:[.25,.25,.25,.25],baseline:.5,time:0}}),b=sample({reward:2,terminated:true,policy:{probabilities:[.25,.25,.25,.25],baseline:.5,time:1}});l.parameters.v[a.state]=.5;l.observe(a);l.observe(b);expect(l.parameters.v[a.state]).toBe(.5);const us=l.endEpisode([a,b],true);expect(us.map(u=>u.target)).toEqual([2.8,2]);expect(l.parameters.v[a.state]).toBeCloseTo(.5+.1*(2.3+1.5),14);expect(l.parameters.actor[a.state][1]).toBeCloseTo(.1*.75*(2.3+.9*1.5),14);expect(us[1].policy.probabilities).toEqual([.25,.25,.25,.25]);});
 test('terminal masks bootstrap; external cutoff retains critic value and skips incomplete REINFORCE',()=>{const make=()=>{const l=new PolicyLearner(config('actor-critic'));l.parameters.v={'0,1':.5,'1,1':4};return l;};expect(make().observe(sample({terminated:true}))[0].target).toBe(1);expect(make().observe(sample({truncated:true}))[0].target).toBe(4.6);for(const algorithm of ['reinforce','reinforce-baseline']){const l=new PolicyLearner(config(algorithm)),s=sample({truncated:true,policy:{probabilities:[.25,.25,.25,.25],baseline:0,time:0}});l.observe(s);expect(l.endEpisode([s],false)).toEqual([]);expect(l.parameters.actor).toEqual({});expect(l.parameters.skippedPolicy).toBe(1);}});
 test('zero gamma suppresses all actor contributions after t=0 without erasing critic learning',()=>{const l=new PolicyLearner({...config('actor-critic'),gamma:0});const [u]=l.observe(sample());expect(u.policy.preferencesAfter).toEqual([0,0,0,0]);expect(u.next).not.toBe(0);});
});
describe('policy runtime, workers, frozen evaluation and persistence',()=>{
 test.each(['reinforce','reinforce-baseline','actor-critic'])('%s save/load preserves partial episodes and identical seeded continuation',algorithm=>{const r=advance(new TrainingRun(config(algorithm)),17),copy=TrainingRun.restore(r.checkpoint());for(let i=0;i<100;i++){expect(r.step()).toEqual(copy.step());expect(()=>validateRunCheckpoint(r.checkpoint())).not.toThrow();}expect(copy.checkpoint()).toEqual(r.checkpoint());const before=r.learner.snapshot();r.resetEpisode();expect(r.learner.parameters.actor).toEqual(before.actor);expect(r.learner.parameters.v).toEqual(before.v);expect(()=>validateRunCheckpoint(r.checkpoint())).not.toThrow();});
 test.each(['reinforce','reinforce-baseline','actor-critic'])('%s frozen evaluation samples softmax and changes no training state',algorithm=>{const r=advance(new TrainingRun(config(algorithm)),120),before=r.checkpoint(),e=new FrozenEvaluation(r.config,r.learner.parameters,evaluationSeeds(8));while(!e.done)e.step();expect(r.checkpoint()).toEqual(before);expect(e.result().rule).toContain('Frozen learned softmax');expect(e.result().trainingUpdates).toBe(0);const d=policyDecision(r.learner.parameters,'0,1',createRng(42),true);expect(d.branch).toBe('policy-sample');expect(d.probabilities).toEqual(softmax(r.learner.parameters.actor['0,1']??[0,0,0,0]));expect(d.explorationDraw).toBeNull();});
 test.each(['reinforce','reinforce-baseline','actor-critic'])('%s chunked pause/resume/cancel is identical to synchronous stepping',algorithm=>{const c=config(algorithm),h=harness(c);h.request('trainInteractions',{interactions:153});h.queue.shift()();h.request('pause');const stopped=h.host.run.checkpoint();h.drain();expect(h.host.run.checkpoint()).toEqual(stopped);h.request('resume');h.drain();expect(h.host.run.checkpoint()).toEqual(advance(new TrainingRun(c),153).checkpoint());h.request('train',{episodes:300});h.queue.shift()();h.request('cancel');const cancelled=h.host.run.checkpoint();h.drain();expect(h.host.run.checkpoint()).toEqual(cancelled);});
 test('policy gradient, decision and update tampering is rejected',()=>{const r=new TrainingRun(config('actor-critic'));r.step();for(const mutate of [c=>c.parameters.actor['0,1'].push(0),c=>c.last.updates[0].policy.preferencesAfter[0]+=1,c=>c.last.decision.probabilities[0]+=.1,c=>c.samples[0].policy.time++,c=>c.parameters.criticUpdates++]){const c=r.checkpoint();mutate(c);expect(()=>validateRunCheckpoint(c)).toThrow();}});
 test('three real methods, five seeds each, discounted evaluation summary and strict import',async()=>{const comparison=newComparison(config(),20,'Developer fixture prior prediction');await runComparison(worker(),comparison,()=>false,()=>{});expect(comparison.runs).toHaveLength(15);expect(()=>validateComparison(comparison,'08')).not.toThrow();const summary=comparisonSummary(comparison);for(const s of summary){const runs=comparison.runs.filter(r=>r.algorithm===s.algorithm);expect(s.mean).toBe(runs.reduce((total,r)=>total+r.evaluation.rows.reduce((sum,e)=>sum+e.discountedReturn,0)/5,0)/5);}expect(comparison.runs.every(r=>r.parameters.q&&Object.keys(r.parameters.q).length===0)).toBe(true);},30000);
 test('task-05 backup remains byte-equivalent in data and preserves new lesson on import',async()=>{const store=new LearningStore({getItem:()=>null,setItem:()=>{}}),raw=readFileSync('evidence/task-05/browser-qa-advanced.json','utf8'),old=JSON.parse(raw),parsed=store.parseImport(raw);expect(parsed.progress).toEqual(old.progress);expect(parsed.runs).toEqual(old.runs);store.lesson('08').reflection='Preserved ungraded note';await store.replace(parsed);expect(store.lesson('08').reflection).toBe('Preserved ungraded note');});
});
